WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'com.atlassian.auiplugin:jquery-ui-widgets', location = 'node_modules/@atlassian/aui/src/js-vendor/jquery/jquery-ui/jquery.ui.accordion.js' */
(function(d){d.widget("ui.accordion",{options:{active:0,animated:"slide",autoHeight:!0,clearStyle:!1,collapsible:!1,event:"click",fillSpace:!1,header:"> li > :first-child,> :not(li):even",icons:{header:"ui-icon-triangle-1-e",headerSelected:"ui-icon-triangle-1-s"},navigation:!1,navigationFilter:function(){return this.href.toLowerCase()===location.href.toLowerCase()}},_create:function(){var a=this,b=a.options;a.running=0;a.element.addClass("ui-accordion ui-widget ui-helper-reset").children("li").addClass("ui-accordion-li-fix");
a.headers=a.element.find(b.header).addClass("ui-accordion-header ui-helper-reset ui-state-default ui-corner-all").bind("mouseenter.accordion",function(){b.disabled||d(this).addClass("ui-state-hover")}).bind("mouseleave.accordion",function(){b.disabled||d(this).removeClass("ui-state-hover")}).bind("focus.accordion",function(){b.disabled||d(this).addClass("ui-state-focus")}).bind("blur.accordion",function(){b.disabled||d(this).removeClass("ui-state-focus")});a.headers.next().addClass("ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom");
if(b.navigation){var c=a.element.find("a").filter(b.navigationFilter).eq(0);if(c.length){var f=c.closest(".ui-accordion-header");a.active=f.length?f:c.closest(".ui-accordion-content").prev()}}a.active=a._findActive(a.active||b.active).addClass("ui-state-default ui-state-active").toggleClass("ui-corner-all").toggleClass("ui-corner-top");a.active.next().addClass("ui-accordion-content-active");a._createIcons();a.resize();a.element.attr("role","tablist");a.headers.attr("role","tab").bind("keydown.accordion",
function(b){return a._keydown(b)}).next().attr("role","tabpanel");a.headers.not(a.active||"").attr({"aria-expanded":"false","aria-selected":"false",tabIndex:-1}).next().hide();a.active.length?a.active.attr({"aria-expanded":"true","aria-selected":"true",tabIndex:0}):a.headers.eq(0).attr("tabIndex",0);d.browser.safari||a.headers.find("a").attr("tabIndex",-1);b.event&&a.headers.bind(b.event.split(" ").join(".accordion ")+".accordion",function(b){a._clickHandler.call(a,b,this);b.preventDefault()})},_createIcons:function(){var a=
this.options;a.icons&&(d("<span></span>").addClass("ui-icon "+a.icons.header).prependTo(this.headers),this.active.children(".ui-icon").toggleClass(a.icons.header).toggleClass(a.icons.headerSelected),this.element.addClass("ui-accordion-icons"))},_destroyIcons:function(){this.headers.children(".ui-icon").remove();this.element.removeClass("ui-accordion-icons")},destroy:function(){var a=this.options;this.element.removeClass("ui-accordion ui-widget ui-helper-reset").removeAttr("role");this.headers.unbind(".accordion").removeClass("ui-accordion-header ui-accordion-disabled ui-helper-reset ui-state-default ui-corner-all ui-state-active ui-state-disabled ui-corner-top").removeAttr("role").removeAttr("aria-expanded").removeAttr("aria-selected").removeAttr("tabIndex");
this.headers.find("a").removeAttr("tabIndex");this._destroyIcons();var b=this.headers.next().css("display","").removeAttr("role").removeClass("ui-helper-reset ui-widget-content ui-corner-bottom ui-accordion-content ui-accordion-content-active ui-accordion-disabled ui-state-disabled");(a.autoHeight||a.fillHeight)&&b.css("height","");return d.Widget.prototype.destroy.call(this)},_setOption:function(a,b){d.Widget.prototype._setOption.apply(this,arguments);"active"==a&&this.activate(b);"icons"==a&&(this._destroyIcons(),
b&&this._createIcons());if("disabled"==a)this.headers.add(this.headers.next())[b?"addClass":"removeClass"]("ui-accordion-disabled ui-state-disabled")},_keydown:function(a){if(!this.options.disabled&&!a.altKey&&!a.ctrlKey){var b=d.ui.keyCode,c=this.headers.length,f=this.headers.index(a.target),g=!1;switch(a.keyCode){case b.RIGHT:case b.DOWN:g=this.headers[(f+1)%c];break;case b.LEFT:case b.UP:g=this.headers[(f-1+c)%c];break;case b.SPACE:case b.ENTER:this._clickHandler({target:a.target},a.target),a.preventDefault()}return g?
(d(a.target).attr("tabIndex",-1),d(g).attr("tabIndex",0),g.focus(),!1):!0}},resize:function(){var a=this.options,b;if(a.fillSpace){if(d.browser.msie){var c=this.element.parent().css("overflow");this.element.parent().css("overflow","hidden")}b=this.element.parent().height();d.browser.msie&&this.element.parent().css("overflow",c);this.headers.each(function(){b-=d(this).outerHeight(!0)});this.headers.next().each(function(){d(this).height(Math.max(0,b-d(this).innerHeight()+d(this).height()))}).css("overflow",
"auto")}else a.autoHeight&&(b=0,this.headers.next().each(function(){b=Math.max(b,d(this).height("").height())}).height(b));return this},activate:function(a){this.options.active=a;a=this._findActive(a)[0];this._clickHandler({target:a},a);return this},_findActive:function(a){return a?"number"===typeof a?this.headers.filter(":eq("+a+")"):this.headers.not(this.headers.not(a)):!1===a?d([]):this.headers.filter(":eq(0)")},_clickHandler:function(a,b){var c=this.options;if(!c.disabled)if(a.target){var f=d(a.currentTarget||
b),g=f[0]===this.active[0];c.active=c.collapsible&&g?!1:this.headers.index(f);if(!(this.running||!c.collapsible&&g)){var i=this.active,e=f.next(),h=this.active.next(),k={options:c,newHeader:g&&c.collapsible?d([]):f,oldHeader:this.active,newContent:g&&c.collapsible?d([]):e,oldContent:h},j=this.headers.index(this.active[0])>this.headers.index(f[0]);this.active=g?d([]):f;this._toggle(e,h,k,g,j);i.removeClass("ui-state-active ui-corner-top").addClass("ui-state-default ui-corner-all").children(".ui-icon").removeClass(c.icons.headerSelected).addClass(c.icons.header);
g||(f.removeClass("ui-state-default ui-corner-all").addClass("ui-state-active ui-corner-top").children(".ui-icon").removeClass(c.icons.header).addClass(c.icons.headerSelected),f.next().addClass("ui-accordion-content-active"))}}else if(c.collapsible){this.active.removeClass("ui-state-active ui-corner-top").addClass("ui-state-default ui-corner-all").children(".ui-icon").removeClass(c.icons.headerSelected).addClass(c.icons.header);this.active.next().addClass("ui-accordion-content-active");var h=this.active.next(),
k={options:c,newHeader:d([]),oldHeader:c.active,newContent:d([]),oldContent:h},e=this.active=d([]);this._toggle(e,h,k)}},_toggle:function(a,b,c,f,g){var i=this,e=i.options;i.toShow=a;i.toHide=b;i.data=c;var h=function(){if(i)return i._completed.apply(i,arguments)};i._trigger("changestart",null,i.data);i.running=0===b.size()?a.size():b.size();if(e.animated){c={};c=e.collapsible&&f?{toShow:d([]),toHide:b,complete:h,down:g,autoHeight:e.autoHeight||e.fillSpace}:{toShow:a,toHide:b,complete:h,down:g,autoHeight:e.autoHeight||
e.fillSpace};e.proxied||(e.proxied=e.animated);e.proxiedDuration||(e.proxiedDuration=e.duration);e.animated=d.isFunction(e.proxied)?e.proxied(c):e.proxied;e.duration=d.isFunction(e.proxiedDuration)?e.proxiedDuration(c):e.proxiedDuration;var f=d.ui.accordion.animations,k=e.duration,j=e.animated;j&&(!f[j]&&!d.easing[j])&&(j="slide");f[j]||(f[j]=function(a){this.slide(a,{easing:j,duration:k||700})});f[j](c)}else e.collapsible&&f?a.toggle():(b.hide(),a.show()),h(!0);b.prev().attr({"aria-expanded":"false",
"aria-selected":"false",tabIndex:-1}).blur();a.prev().attr({"aria-expanded":"true","aria-selected":"true",tabIndex:0}).focus()},_completed:function(a){this.running=a?0:--this.running;this.running||(this.options.clearStyle&&this.toShow.add(this.toHide).css({height:"",overflow:""}),this.toHide.removeClass("ui-accordion-content-active"),this.toHide.length&&(this.toHide.parent()[0].className=this.toHide.parent()[0].className),this._trigger("change",null,this.data))}});d.extend(d.ui.accordion,{version:"1.8.24",
animations:{slide:function(a,b){a=d.extend({easing:"swing",duration:300},a,b);if(a.toHide.size())if(a.toShow.size()){var c=a.toShow.css("overflow"),f=0,g={},i={},e,h=a.toShow;e=h[0].style.width;h.width(h.parent().width()-parseFloat(h.css("paddingLeft"))-parseFloat(h.css("paddingRight"))-(parseFloat(h.css("borderLeftWidth"))||0)-(parseFloat(h.css("borderRightWidth"))||0));d.each(["height","paddingTop","paddingBottom"],function(b,c){i[c]="hide";var e=(""+d.css(a.toShow[0],c)).match(/^([\d+-.]+)(.*)$/);
g[c]={value:e[1],unit:e[2]||"px"}});a.toShow.css({height:0,overflow:"hidden"}).show();a.toHide.filter(":hidden").each(a.complete).end().filter(":visible").animate(i,{step:function(b,c){"height"==c.prop&&(f=0===c.end-c.start?0:(c.now-c.start)/(c.end-c.start));a.toShow[0].style[c.prop]=f*g[c.prop].value+g[c.prop].unit},duration:a.duration,easing:a.easing,complete:function(){a.autoHeight||a.toShow.css("height","");a.toShow.css({width:e,overflow:c});a.complete()}})}else a.toHide.animate({height:"hide",
paddingTop:"hide",paddingBottom:"hide"},a);else a.toShow.animate({height:"show",paddingTop:"show",paddingBottom:"show"},a)},bounceslide:function(a){this.slide(a,{easing:a.down?"easeOutBounce":"swing",duration:a.down?1E3:200})}}})})(jQuery);
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.auiplugin:jquery-ui-widgets', location = 'node_modules/@atlassian/aui/src/js-vendor/jquery/jquery-ui/jquery.ui.autocomplete.js' */
(function(d){var c=0;d.widget("ui.autocomplete",{options:{appendTo:"body",autoFocus:!1,delay:300,minLength:1,position:{my:"left top",at:"left bottom",collision:"none"},source:null},pending:0,_create:function(){var a=this,b=this.element[0].ownerDocument,c;this.isMultiLine=this.element.is("textarea");this.element.addClass("ui-autocomplete-input").attr("autocomplete","off").attr({role:"textbox","aria-autocomplete":"list","aria-haspopup":"true"}).bind("keydown.autocomplete",function(b){if(!a.options.disabled&&
!a.element.propAttr("readOnly")){c=!1;var f=d.ui.keyCode;switch(b.keyCode){case f.PAGE_UP:a._move("previousPage",b);break;case f.PAGE_DOWN:a._move("nextPage",b);break;case f.UP:a._keyEvent("previous",b);break;case f.DOWN:a._keyEvent("next",b);break;case f.ENTER:case f.NUMPAD_ENTER:a.menu.active&&(c=!0,b.preventDefault());case f.TAB:if(!a.menu.active)break;a.menu.select(b);break;case f.ESCAPE:a.element.val(a.term);a.close(b);break;default:clearTimeout(a.searching),a.searching=setTimeout(function(){a.term!=
a.element.val()&&(a.selectedItem=null,a.search(null,b))},a.options.delay)}}}).bind("keypress.autocomplete",function(a){c&&(c=!1,a.preventDefault())}).bind("focus.autocomplete",function(){a.options.disabled||(a.selectedItem=null,a.previous=a.element.val())}).bind("blur.autocomplete",function(b){a.options.disabled||(clearTimeout(a.searching),a.closing=setTimeout(function(){a.close(b);a._change(b)},150))});this._initSource();this.menu=d("<ul></ul>").addClass("ui-autocomplete").appendTo(d(this.options.appendTo||
"body",b)[0]).mousedown(function(b){var c=a.menu.element[0];d(b.target).closest(".ui-menu-item").length||setTimeout(function(){d(document).one("mousedown",function(b){b.target!==a.element[0]&&(b.target!==c&&!d.ui.contains(c,b.target))&&a.close()})},1);setTimeout(function(){clearTimeout(a.closing)},13)}).menu({focus:function(b,d){var c=d.item.data("item.autocomplete");!1!==a._trigger("focus",b,{item:c})&&/^key/.test(b.originalEvent.type)&&a.element.val(c.value)},selected:function(c,d){var e=d.item.data("item.autocomplete"),
h=a.previous;a.element[0]!==b.activeElement&&(a.element.focus(),a.previous=h,setTimeout(function(){a.previous=h;a.selectedItem=e},1));!1!==a._trigger("select",c,{item:e})&&a.element.val(e.value);a.term=a.element.val();a.close(c);a.selectedItem=e},blur:function(){a.menu.element.is(":visible")&&a.element.val()!==a.term&&a.element.val(a.term)}}).zIndex(this.element.zIndex()+1).css({top:0,left:0}).hide().data("menu");d.fn.bgiframe&&this.menu.element.bgiframe();a.beforeunloadHandler=function(){a.element.removeAttr("autocomplete")};
d(window).bind("beforeunload",a.beforeunloadHandler)},destroy:function(){this.element.removeClass("ui-autocomplete-input").removeAttr("autocomplete").removeAttr("role").removeAttr("aria-autocomplete").removeAttr("aria-haspopup");this.menu.element.remove();d(window).unbind("beforeunload",this.beforeunloadHandler);d.Widget.prototype.destroy.call(this)},_setOption:function(a,b){d.Widget.prototype._setOption.apply(this,arguments);"source"===a&&this._initSource();"appendTo"===a&&this.menu.element.appendTo(d(b||
"body",this.element[0].ownerDocument)[0]);"disabled"===a&&(b&&this.xhr)&&this.xhr.abort()},_initSource:function(){var a=this,b,c;d.isArray(this.options.source)?(b=this.options.source,this.source=function(a,c){c(d.ui.autocomplete.filter(b,a.term))}):"string"===typeof this.options.source?(c=this.options.source,this.source=function(b,f){a.xhr&&a.xhr.abort();a.xhr=d.ajax({url:c,data:b,dataType:"json",success:function(a){f(a)},error:function(){f([])}})}):this.source=this.options.source},search:function(a,
b){a=null!=a?a:this.element.val();this.term=this.element.val();if(a.length<this.options.minLength)return this.close(b);clearTimeout(this.closing);if(!1!==this._trigger("search",b))return this._search(a)},_search:function(a){this.pending++;this.element.addClass("ui-autocomplete-loading");this.source({term:a},this._response())},_response:function(){var a=this,b=++c;return function(d){b===c&&a.__response(d);a.pending--;a.pending||a.element.removeClass("ui-autocomplete-loading")}},__response:function(a){!this.options.disabled&&
a&&a.length?(a=this._normalize(a),this._suggest(a),this._trigger("open")):this.close()},close:function(a){clearTimeout(this.closing);this.menu.element.is(":visible")&&(this.menu.element.hide(),this.menu.deactivate(),this._trigger("close",a))},_change:function(a){this.previous!==this.element.val()&&this._trigger("change",a,{item:this.selectedItem})},_normalize:function(a){return a.length&&a[0].label&&a[0].value?a:d.map(a,function(a){return"string"===typeof a?{label:a,value:a}:d.extend({label:a.label||
a.value,value:a.value||a.label},a)})},_suggest:function(a){var b=this.menu.element.empty().zIndex(this.element.zIndex()+1);this._renderMenu(b,a);this.menu.deactivate();this.menu.refresh();b.show();this._resizeMenu();b.position(d.extend({of:this.element},this.options.position));this.options.autoFocus&&this.menu.next(new d.Event("mouseover"))},_resizeMenu:function(){var a=this.menu.element;a.outerWidth(Math.max(a.width("").outerWidth()+1,this.element.outerWidth()))},_renderMenu:function(a,b){var c=
this;d.each(b,function(b,d){c._renderItem(a,d)})},_renderItem:function(a,b){return d("<li></li>").data("item.autocomplete",b).append(d("<a></a>").text(b.label)).appendTo(a)},_move:function(a,b){if(this.menu.element.is(":visible"))if(this.menu.first()&&/^previous/.test(a)||this.menu.last()&&/^next/.test(a))this.element.val(this.term),this.menu.deactivate();else this.menu[a](b);else this.search(null,b)},widget:function(){return this.menu.element},_keyEvent:function(a,b){if(!this.isMultiLine||this.menu.element.is(":visible"))this._move(a,
b),b.preventDefault()}});d.extend(d.ui.autocomplete,{escapeRegex:function(a){return a.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$&")},filter:function(a,b){var c=RegExp(d.ui.autocomplete.escapeRegex(b),"i");return d.grep(a,function(a){return c.test(a.label||a.value||a)})}})})(jQuery);
(function(d){d.widget("ui.menu",{_create:function(){var c=this;this.element.addClass("ui-menu ui-widget ui-widget-content ui-corner-all").attr({role:"listbox","aria-activedescendant":"ui-active-menuitem"}).click(function(a){d(a.target).closest(".ui-menu-item a").length&&(a.preventDefault(),c.select(a))});this.refresh()},refresh:function(){var c=this;this.element.children("li:not(.ui-menu-item):has(a)").addClass("ui-menu-item").attr("role","menuitem").children("a").addClass("ui-corner-all").attr("tabindex",
-1).mouseenter(function(a){c.activate(a,d(this).parent())}).mouseleave(function(){c.deactivate()})},activate:function(c,a){this.deactivate();if(this.hasScroll()){var b=a.offset().top-this.element.offset().top,d=this.element.scrollTop(),g=this.element.height();0>b?this.element.scrollTop(d+b):b>=g&&this.element.scrollTop(d+b-g+a.height())}this.active=a.eq(0).children("a").addClass("ui-state-hover").attr("id","ui-active-menuitem").end();this._trigger("focus",c,{item:a})},deactivate:function(){this.active&&
(this.active.children("a").removeClass("ui-state-hover").removeAttr("id"),this._trigger("blur"),this.active=null)},next:function(c){this.move("next",".ui-menu-item:first",c)},previous:function(c){this.move("prev",".ui-menu-item:last",c)},first:function(){return this.active&&!this.active.prevAll(".ui-menu-item").length},last:function(){return this.active&&!this.active.nextAll(".ui-menu-item").length},move:function(c,a,b){this.active?(c=this.active[c+"All"](".ui-menu-item").eq(0),c.length?this.activate(b,
c):this.activate(b,this.element.children(a))):this.activate(b,this.element.children(a))},nextPage:function(c){if(this.hasScroll())if(!this.active||this.last())this.activate(c,this.element.children(".ui-menu-item:first"));else{var a=this.active.offset().top,b=this.element.height(),e=this.element.children(".ui-menu-item").filter(function(){var c=d(this).offset().top-a-b+d(this).height();return 10>c&&-10<c});e.length||(e=this.element.children(".ui-menu-item:last"));this.activate(c,e)}else this.activate(c,
this.element.children(".ui-menu-item").filter(!this.active||this.last()?":first":":last"))},previousPage:function(c){if(this.hasScroll())if(!this.active||this.first())this.activate(c,this.element.children(".ui-menu-item:last"));else{var a=this.active.offset().top,b=this.element.height(),e=this.element.children(".ui-menu-item").filter(function(){var c=d(this).offset().top-a+b-d(this).height();return 10>c&&-10<c});e.length||(e=this.element.children(".ui-menu-item:first"));this.activate(c,e)}else this.activate(c,
this.element.children(".ui-menu-item").filter(!this.active||this.first()?":last":":first"))},hasScroll:function(){return this.element.height()<this.element[d.fn.prop?"prop":"attr"]("scrollHeight")},select:function(c){this._trigger("selected",c,{item:this.active})}})})(jQuery);
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.auiplugin:jquery-ui-widgets', location = 'node_modules/@atlassian/aui/src/js-vendor/jquery/jquery-ui/jquery.ui.button.js' */
(function(b){var g,h,i,e,k=function(){var a=b(this).find(":ui-button");setTimeout(function(){a.button("refresh")},1)},j=function(a){var c=a.name,d=a.form,f=b([]);c&&(f=d?b(d).find("[name='"+c+"']"):b("[name='"+c+"']",a.ownerDocument).filter(function(){return!this.form}));return f};b.widget("ui.button",{options:{disabled:null,text:!0,label:null,icons:{primary:null,secondary:null}},_create:function(){this.element.closest("form").unbind("reset.button").bind("reset.button",k);"boolean"!==typeof this.options.disabled?
this.options.disabled=!!this.element.propAttr("disabled"):this.element.propAttr("disabled",this.options.disabled);this._determineButtonType();this.hasTitle=!!this.buttonElement.attr("title");var a=this,c=this.options,d="checkbox"===this.type||"radio"===this.type,f="ui-state-hover"+(!d?" ui-state-active":"");null===c.label&&(c.label=this.buttonElement.html());this.buttonElement.addClass("ui-button ui-widget ui-state-default ui-corner-all").attr("role","button").bind("mouseenter.button",function(){if(!c.disabled){b(this).addClass("ui-state-hover");
this===g&&b(this).addClass("ui-state-active")}}).bind("mouseleave.button",function(){c.disabled||b(this).removeClass(f)}).bind("click.button",function(a){if(c.disabled){a.preventDefault();a.stopImmediatePropagation()}});this.element.bind("focus.button",function(){a.buttonElement.addClass("ui-state-focus")}).bind("blur.button",function(){a.buttonElement.removeClass("ui-state-focus")});d&&(this.element.bind("change.button",function(){e||a.refresh()}),this.buttonElement.bind("mousedown.button",function(a){if(!c.disabled){e=
false;h=a.pageX;i=a.pageY}}).bind("mouseup.button",function(a){if(!c.disabled&&(h!==a.pageX||i!==a.pageY))e=true}));"checkbox"===this.type?this.buttonElement.bind("click.button",function(){if(c.disabled||e)return false;b(this).toggleClass("ui-state-active");a.buttonElement.attr("aria-pressed",a.element[0].checked)}):"radio"===this.type?this.buttonElement.bind("click.button",function(){if(c.disabled||e)return false;b(this).addClass("ui-state-active");a.buttonElement.attr("aria-pressed","true");var d=
a.element[0];j(d).not(d).map(function(){return b(this).button("widget")[0]}).removeClass("ui-state-active").attr("aria-pressed","false")}):(this.buttonElement.bind("mousedown.button",function(){if(c.disabled)return false;b(this).addClass("ui-state-active");g=this;b(document).one("mouseup",function(){g=null})}).bind("mouseup.button",function(){if(c.disabled)return false;b(this).removeClass("ui-state-active")}).bind("keydown.button",function(a){if(c.disabled)return false;(a.keyCode==b.ui.keyCode.SPACE||
a.keyCode==b.ui.keyCode.ENTER)&&b(this).addClass("ui-state-active")}).bind("keyup.button",function(){b(this).removeClass("ui-state-active")}),this.buttonElement.is("a")&&this.buttonElement.keyup(function(a){a.keyCode===b.ui.keyCode.SPACE&&b(this).click()}));this._setOption("disabled",c.disabled);this._resetButton()},_determineButtonType:function(){this.type=this.element.is(":checkbox")?"checkbox":this.element.is(":radio")?"radio":this.element.is("input")?"input":"button";if("checkbox"===this.type||
"radio"===this.type){var a=this.element.parents().filter(":last"),b="label[for='"+this.element.attr("id")+"']";this.buttonElement=a.find(b);this.buttonElement.length||(a=a.length?a.siblings():this.element.siblings(),this.buttonElement=a.filter(b),this.buttonElement.length||(this.buttonElement=a.find(b)));this.element.addClass("ui-helper-hidden-accessible");(a=this.element.is(":checked"))&&this.buttonElement.addClass("ui-state-active");this.buttonElement.attr("aria-pressed",a)}else this.buttonElement=
this.element},widget:function(){return this.buttonElement},destroy:function(){this.element.removeClass("ui-helper-hidden-accessible");this.buttonElement.removeClass("ui-button ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-active  ui-button-icons-only ui-button-icon-only ui-button-text-icons ui-button-text-icon-primary ui-button-text-icon-secondary ui-button-text-only").removeAttr("role").removeAttr("aria-pressed").html(this.buttonElement.find(".ui-button-text").html());this.hasTitle||
this.buttonElement.removeAttr("title");b.Widget.prototype.destroy.call(this)},_setOption:function(a,c){b.Widget.prototype._setOption.apply(this,arguments);"disabled"===a?c?this.element.propAttr("disabled",!0):this.element.propAttr("disabled",!1):this._resetButton()},refresh:function(){var a=this.element.is(":disabled");a!==this.options.disabled&&this._setOption("disabled",a);"radio"===this.type?j(this.element[0]).each(function(){b(this).is(":checked")?b(this).button("widget").addClass("ui-state-active").attr("aria-pressed",
"true"):b(this).button("widget").removeClass("ui-state-active").attr("aria-pressed","false")}):"checkbox"===this.type&&(this.element.is(":checked")?this.buttonElement.addClass("ui-state-active").attr("aria-pressed","true"):this.buttonElement.removeClass("ui-state-active").attr("aria-pressed","false"))},_resetButton:function(){if("input"===this.type)this.options.label&&this.element.val(this.options.label);else{var a=this.buttonElement.removeClass("ui-button-icons-only ui-button-icon-only ui-button-text-icons ui-button-text-icon-primary ui-button-text-icon-secondary ui-button-text-only"),
c=b("<span></span>",this.element[0].ownerDocument).addClass("ui-button-text").html(this.options.label).appendTo(a.empty()).text(),d=this.options.icons,f=d.primary&&d.secondary,e=[];d.primary||d.secondary?(this.options.text&&e.push("ui-button-text-icon"+(f?"s":d.primary?"-primary":"-secondary")),d.primary&&a.prepend("<span class='ui-button-icon-primary ui-icon "+d.primary+"'></span>"),d.secondary&&a.append("<span class='ui-button-icon-secondary ui-icon "+d.secondary+"'></span>"),this.options.text||
(e.push(f?"ui-button-icons-only":"ui-button-icon-only"),this.hasTitle||a.attr("title",c))):e.push("ui-button-text-only");a.addClass(e.join(" "))}}});b.widget("ui.buttonset",{options:{items:":button, :submit, :reset, :checkbox, :radio, a, :data(button)"},_create:function(){this.element.addClass("ui-buttonset")},_init:function(){this.refresh()},_setOption:function(a,c){"disabled"===a&&this.buttons.button("option",a,c);b.Widget.prototype._setOption.apply(this,arguments)},refresh:function(){var a="rtl"===
this.element.css("direction");this.buttons=this.element.find(this.options.items).filter(":ui-button").button("refresh").end().not(":ui-button").button().end().map(function(){return b(this).button("widget")[0]}).removeClass("ui-corner-all ui-corner-left ui-corner-right").filter(":first").addClass(a?"ui-corner-right":"ui-corner-left").end().filter(":last").addClass(a?"ui-corner-left":"ui-corner-right").end().end()},destroy:function(){this.element.removeClass("ui-buttonset");this.buttons.map(function(){return b(this).button("widget")[0]}).removeClass("ui-corner-left ui-corner-right").end().button("destroy");
b.Widget.prototype.destroy.call(this)}})})(jQuery);
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.auiplugin:jquery-ui-widgets', location = 'node_modules/@atlassian/aui/src/js-vendor/jquery/jquery-ui/jquery.ui.dialog.js' */
(function(c){var i={buttons:!0,height:!0,maxHeight:!0,maxWidth:!0,minHeight:!0,minWidth:!0,width:!0},j={maxHeight:!0,maxWidth:!0,minHeight:!0,minWidth:!0};c.widget("ui.dialog",{options:{autoOpen:!0,buttons:{},closeOnEscape:!0,closeText:"close",dialogClass:"",draggable:!0,hide:null,height:"auto",maxHeight:!1,maxWidth:!1,minHeight:150,minWidth:150,modal:!1,position:{my:"center",at:"center",collision:"fit",using:function(a){var b=c(this).css(a).offset().top;0>b&&c(this).css("top",a.top-b)}},resizable:!0,
show:null,stack:!0,title:"",width:300,zIndex:1E3},_create:function(){this.originalTitle=this.element.attr("title");"string"!==typeof this.originalTitle&&(this.originalTitle="");this.options.title=this.options.title||this.originalTitle;var a=this,b=a.options,d=b.title||"&#160;",e=c.ui.dialog.getTitleId(a.element),f=(a.uiDialog=c("<div></div>")).appendTo(document.body).hide().addClass("ui-dialog ui-widget ui-widget-content ui-corner-all "+b.dialogClass).css({zIndex:b.zIndex}).attr("tabIndex",-1).css("outline",
0).keydown(function(d){if(b.closeOnEscape&&!d.isDefaultPrevented()&&d.keyCode&&d.keyCode===c.ui.keyCode.ESCAPE){a.close(d);d.preventDefault()}}).attr({role:"dialog","aria-labelledby":e}).mousedown(function(b){a.moveToTop(false,b)});a.element.show().removeAttr("title").addClass("ui-dialog-content ui-widget-content").appendTo(f);var h=(a.uiDialogTitlebar=c("<div></div>")).addClass("ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix").prependTo(f),g=c('<a href="#"></a>').addClass("ui-dialog-titlebar-close ui-corner-all").attr("role",
"button").hover(function(){g.addClass("ui-state-hover")},function(){g.removeClass("ui-state-hover")}).focus(function(){g.addClass("ui-state-focus")}).blur(function(){g.removeClass("ui-state-focus")}).click(function(b){a.close(b);return false}).appendTo(h);(a.uiDialogTitlebarCloseText=c("<span></span>")).addClass("ui-icon ui-icon-closethick").text(b.closeText).appendTo(g);c("<span></span>").addClass("ui-dialog-title").attr("id",e).html(d).prependTo(h);c.isFunction(b.beforeclose)&&!c.isFunction(b.beforeClose)&&
(b.beforeClose=b.beforeclose);h.find("*").add(h).disableSelection();b.draggable&&c.fn.draggable&&a._makeDraggable();b.resizable&&c.fn.resizable&&a._makeResizable();a._createButtons(b.buttons);a._isOpen=!1;c.fn.bgiframe&&f.bgiframe()},_init:function(){this.options.autoOpen&&this.open()},destroy:function(){this.overlay&&this.overlay.destroy();this.uiDialog.hide();this.element.unbind(".dialog").removeData("dialog").removeClass("ui-dialog-content ui-widget-content").hide().appendTo("body");this.uiDialog.remove();
this.originalTitle&&this.element.attr("title",this.originalTitle);return this},widget:function(){return this.uiDialog},close:function(a){var b=this,d,e;if(!1!==b._trigger("beforeClose",a))return b.overlay&&b.overlay.destroy(),b.uiDialog.unbind("keypress.ui-dialog"),b._isOpen=!1,b.options.hide?b.uiDialog.hide(b.options.hide,function(){b._trigger("close",a)}):(b.uiDialog.hide(),b._trigger("close",a)),c.ui.dialog.overlay.resize(),b.options.modal&&(d=0,c(".ui-dialog").each(function(){if(this!==b.uiDialog[0]){e=
c(this).css("z-index");isNaN(e)||(d=Math.max(d,e))}}),c.ui.dialog.maxZ=d),b},isOpen:function(){return this._isOpen},moveToTop:function(a,b){var d=this.options;if(d.modal&&!a||!d.stack&&!d.modal)return this._trigger("focus",b);d.zIndex>c.ui.dialog.maxZ&&(c.ui.dialog.maxZ=d.zIndex);this.overlay&&(c.ui.dialog.maxZ+=1,this.overlay.$el.css("z-index",c.ui.dialog.overlay.maxZ=c.ui.dialog.maxZ));d={scrollTop:this.element.scrollTop(),scrollLeft:this.element.scrollLeft()};c.ui.dialog.maxZ+=1;this.uiDialog.css("z-index",
c.ui.dialog.maxZ);this.element.attr(d);this._trigger("focus",b);return this},open:function(){if(!this._isOpen){var a=this.options,b=this.uiDialog;this.overlay=a.modal?new c.ui.dialog.overlay(this):null;this._size();this._position(a.position);b.show(a.show);this.moveToTop(!0);a.modal&&b.bind("keydown.ui-dialog",function(a){if(a.keyCode===c.ui.keyCode.TAB){var b=c(":tabbable",this),f=b.filter(":first"),b=b.filter(":last");if(a.target===b[0]&&!a.shiftKey)return f.focus(1),!1;if(a.target===f[0]&&a.shiftKey)return b.focus(1),
!1}});c(this.element.find(":tabbable").get().concat(b.find(".ui-dialog-buttonpane :tabbable").get().concat(b.get()))).eq(0).focus();this._isOpen=!0;this._trigger("open");return this}},_createButtons:function(a){var b=this,d=!1,e=c("<div></div>").addClass("ui-dialog-buttonpane ui-widget-content ui-helper-clearfix"),f=c("<div></div>").addClass("ui-dialog-buttonset").appendTo(e);b.uiDialog.find(".ui-dialog-buttonpane").remove();"object"===typeof a&&null!==a&&c.each(a,function(){return!(d=!0)});d&&(c.each(a,
function(a,d){var d=c.isFunction(d)?{click:d,text:a}:d,e=c('<button type="button"></button>').click(function(){d.click.apply(b.element[0],arguments)}).appendTo(f);c.each(d,function(a,b){if("click"!==a)if(a in e)e[a](b);else e.attr(a,b)});c.fn.button&&e.button()}),e.appendTo(b.uiDialog))},_makeDraggable:function(){function a(a){return{position:a.position,offset:a.offset}}var b=this,d=b.options,e=c(document),f;b.uiDialog.draggable({cancel:".ui-dialog-content, .ui-dialog-titlebar-close",handle:".ui-dialog-titlebar",
containment:"document",start:function(e,g){f="auto"===d.height?"auto":c(this).height();c(this).height(c(this).height()).addClass("ui-dialog-dragging");b._trigger("dragStart",e,a(g))},drag:function(c,d){b._trigger("drag",c,a(d))},stop:function(h,g){d.position=[g.position.left-e.scrollLeft(),g.position.top-e.scrollTop()];c(this).removeClass("ui-dialog-dragging").height(f);b._trigger("dragStop",h,a(g));c.ui.dialog.overlay.resize()}})},_makeResizable:function(a){function b(a){return{originalPosition:a.originalPosition,
originalSize:a.originalSize,position:a.position,size:a.size}}var a=void 0===a?this.options.resizable:a,d=this,e=d.options,f=d.uiDialog.css("position"),a="string"===typeof a?a:"n,e,s,w,se,sw,ne,nw";d.uiDialog.resizable({cancel:".ui-dialog-content",containment:"document",alsoResize:d.element,maxWidth:e.maxWidth,maxHeight:e.maxHeight,minWidth:e.minWidth,minHeight:d._minHeight(),handles:a,start:function(a,e){c(this).addClass("ui-dialog-resizing");d._trigger("resizeStart",a,b(e))},resize:function(a,c){d._trigger("resize",
a,b(c))},stop:function(a,f){c(this).removeClass("ui-dialog-resizing");e.height=c(this).height();e.width=c(this).width();d._trigger("resizeStop",a,b(f));c.ui.dialog.overlay.resize()}}).css("position",f).find(".ui-resizable-se").addClass("ui-icon ui-icon-grip-diagonal-se")},_minHeight:function(){var a=this.options;return"auto"===a.height?a.minHeight:Math.min(a.minHeight,a.height)},_position:function(a){var b=[],d=[0,0],e;if(a){if("string"===typeof a||"object"===typeof a&&"0"in a)b=a.split?a.split(" "):
[a[0],a[1]],1===b.length&&(b[1]=b[0]),c.each(["left","top"],function(a,c){+b[a]===b[a]&&(d[a]=b[a],b[a]=c)}),a={my:b.join(" "),at:b.join(" "),offset:d.join(" ")};a=c.extend({},c.ui.dialog.prototype.options.position,a)}else a=c.ui.dialog.prototype.options.position;(e=this.uiDialog.is(":visible"))||this.uiDialog.show();this.uiDialog.css({top:0,left:0}).position(c.extend({of:window},a));e||this.uiDialog.hide()},_setOptions:function(a){var b=this,d={},e=!1;c.each(a,function(a,c){b._setOption(a,c);a in
i&&(e=!0);a in j&&(d[a]=c)});e&&this._size();this.uiDialog.is(":data(resizable)")&&this.uiDialog.resizable("option",d)},_setOption:function(a,b){var d=this.uiDialog;switch(a){case "beforeclose":a="beforeClose";break;case "buttons":this._createButtons(b);break;case "closeText":this.uiDialogTitlebarCloseText.text(""+b);break;case "dialogClass":d.removeClass(this.options.dialogClass).addClass("ui-dialog ui-widget ui-widget-content ui-corner-all "+b);break;case "disabled":b?d.addClass("ui-dialog-disabled"):
d.removeClass("ui-dialog-disabled");break;case "draggable":var e=d.is(":data(draggable)");e&&!b&&d.draggable("destroy");!e&&b&&this._makeDraggable();break;case "position":this._position(b);break;case "resizable":(e=d.is(":data(resizable)"))&&!b&&d.resizable("destroy");e&&"string"===typeof b&&d.resizable("option","handles",b);!e&&!1!==b&&this._makeResizable(b);break;case "title":c(".ui-dialog-title",this.uiDialogTitlebar).html(""+(b||"&#160;"))}c.Widget.prototype._setOption.apply(this,arguments)},
_size:function(){var a=this.options,b,d,e=this.uiDialog.is(":visible");this.element.show().css({width:"auto",minHeight:0,height:0});a.minWidth>a.width&&(a.width=a.minWidth);b=this.uiDialog.css({height:"auto",width:a.width}).height();d=Math.max(0,a.minHeight-b);"auto"===a.height?c.support.minHeight?this.element.css({minHeight:d,height:"auto"}):(this.uiDialog.show(),a=this.element.css("height","auto").height(),e||this.uiDialog.hide(),this.element.height(Math.max(a,d))):this.element.height(Math.max(a.height-
b,0));this.uiDialog.is(":data(resizable)")&&this.uiDialog.resizable("option","minHeight",this._minHeight())}});c.extend(c.ui.dialog,{version:"1.8.24",uuid:0,maxZ:0,getTitleId:function(a){a=a.attr("id");a||(a=this.uuid+=1);return"ui-dialog-title-"+a},overlay:function(a){this.$el=c.ui.dialog.overlay.create(a)}});c.extend(c.ui.dialog.overlay,{instances:[],oldInstances:[],maxZ:0,events:c.map("focus mousedown mouseup keydown keypress click".split(" "),function(a){return a+".dialog-overlay"}).join(" "),
create:function(a){0===this.instances.length&&(setTimeout(function(){c.ui.dialog.overlay.instances.length&&c(document).bind(c.ui.dialog.overlay.events,function(a){if(c(a.target).zIndex()<c.ui.dialog.overlay.maxZ)return!1})},1),c(document).bind("keydown.dialog-overlay",function(b){a.options.closeOnEscape&&(!b.isDefaultPrevented()&&b.keyCode&&b.keyCode===c.ui.keyCode.ESCAPE)&&(a.close(b),b.preventDefault())}),c(window).bind("resize.dialog-overlay",c.ui.dialog.overlay.resize));var b=(this.oldInstances.pop()||
c("<div></div>").addClass("ui-widget-overlay")).appendTo(document.body).css({width:this.width(),height:this.height()});c.fn.bgiframe&&b.bgiframe();this.instances.push(b);return b},destroy:function(a){var b=c.inArray(a,this.instances);-1!=b&&this.oldInstances.push(this.instances.splice(b,1)[0]);0===this.instances.length&&c([document,window]).unbind(".dialog-overlay");a.remove();var d=0;c.each(this.instances,function(){d=Math.max(d,this.css("z-index"))});this.maxZ=d},height:function(){var a,b;return c.browser.msie&&
7>c.browser.version?(a=Math.max(document.documentElement.scrollHeight,document.body.scrollHeight),b=Math.max(document.documentElement.offsetHeight,document.body.offsetHeight),a<b?c(window).height()+"px":a+"px"):c(document).height()+"px"},width:function(){var a,b;return c.browser.msie?(a=Math.max(document.documentElement.scrollWidth,document.body.scrollWidth),b=Math.max(document.documentElement.offsetWidth,document.body.offsetWidth),a<b?c(window).width()+"px":a+"px"):c(document).width()+"px"},resize:function(){var a=
c([]);c.each(c.ui.dialog.overlay.instances,function(){a=a.add(this)});a.css({width:0,height:0}).css({width:c.ui.dialog.overlay.width(),height:c.ui.dialog.overlay.height()})}});c.extend(c.ui.dialog.overlay.prototype,{destroy:function(){c.ui.dialog.overlay.destroy(this.$el)}})})(jQuery);
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.auiplugin:jquery-ui-widgets', location = 'node_modules/@atlassian/aui/src/js-vendor/jquery/jquery-ui/jquery.ui.progressbar.js' */
(function(b){b.widget("ui.progressbar",{options:{value:0,max:100},min:0,_create:function(){this.element.addClass("ui-progressbar ui-widget ui-widget-content ui-corner-all").attr({role:"progressbar","aria-valuemin":this.min,"aria-valuemax":this.options.max,"aria-valuenow":this._value()});this.valueDiv=b("<div class='ui-progressbar-value ui-widget-header ui-corner-left'></div>").appendTo(this.element);this.oldValue=this._value();this._refreshValue()},destroy:function(){this.element.removeClass("ui-progressbar ui-widget ui-widget-content ui-corner-all").removeAttr("role").removeAttr("aria-valuemin").removeAttr("aria-valuemax").removeAttr("aria-valuenow");
this.valueDiv.remove();b.Widget.prototype.destroy.apply(this,arguments)},value:function(a){if(void 0===a)return this._value();this._setOption("value",a);return this},_setOption:function(a,c){"value"===a&&(this.options.value=c,this._refreshValue(),this._value()===this.options.max&&this._trigger("complete"));b.Widget.prototype._setOption.apply(this,arguments)},_value:function(){var a=this.options.value;"number"!==typeof a&&(a=0);return Math.min(this.options.max,Math.max(this.min,a))},_percentage:function(){return 100*
this._value()/this.options.max},_refreshValue:function(){var a=this.value(),b=this._percentage();this.oldValue!==a&&(this.oldValue=a,this._trigger("change"));this.valueDiv.toggle(a>this.min).toggleClass("ui-corner-right",a===this.options.max).width(b.toFixed(0)+"%");this.element.attr("aria-valuenow",a)}});b.extend(b.ui.progressbar,{version:"1.8.24"})})(jQuery);
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.auiplugin:jquery-ui-widgets', location = 'node_modules/@atlassian/aui/src/js-vendor/jquery/jquery-ui/jquery.ui.slider.js' */
(function(d){d.widget("ui.slider",d.ui.mouse,{widgetEventPrefix:"slide",options:{animate:!1,distance:0,max:100,min:0,orientation:"horizontal",range:!1,step:1,value:0,values:null},_create:function(){var a=this,b=this.options,c=this.element.find(".ui-slider-handle").addClass("ui-state-default ui-corner-all"),f=b.values&&b.values.length||1,e=[];this._mouseSliding=this._keySliding=!1;this._animateOff=!0;this._handleIndex=null;this._detectOrientation();this._mouseInit();this.element.addClass("ui-slider ui-slider-"+
this.orientation+" ui-widget ui-widget-content ui-corner-all"+(b.disabled?" ui-slider-disabled ui-disabled":""));this.range=d([]);if(b.range){if(!0===b.range&&(b.values||(b.values=[this._valueMin(),this._valueMin()]),b.values.length&&2!==b.values.length))b.values=[b.values[0],b.values[0]];this.range=d("<div></div>").appendTo(this.element).addClass("ui-slider-range ui-widget-header"+("min"===b.range||"max"===b.range?" ui-slider-range-"+b.range:""))}for(var g=c.length;g<f;g+=1)e.push("<a class='ui-slider-handle ui-state-default ui-corner-all' href='#'></a>");
this.handles=c.add(d(e.join("")).appendTo(a.element));this.handle=this.handles.eq(0);this.handles.add(this.range).filter("a").click(function(a){a.preventDefault()}).hover(function(){b.disabled||d(this).addClass("ui-state-hover")},function(){d(this).removeClass("ui-state-hover")}).focus(function(){b.disabled?d(this).blur():(d(".ui-slider .ui-state-focus").removeClass("ui-state-focus"),d(this).addClass("ui-state-focus"))}).blur(function(){d(this).removeClass("ui-state-focus")});this.handles.each(function(a){d(this).data("index.ui-slider-handle",
a)});this.handles.keydown(function(b){var c=d(this).data("index.ui-slider-handle"),e,f,g;if(!a.options.disabled){switch(b.keyCode){case d.ui.keyCode.HOME:case d.ui.keyCode.END:case d.ui.keyCode.PAGE_UP:case d.ui.keyCode.PAGE_DOWN:case d.ui.keyCode.UP:case d.ui.keyCode.RIGHT:case d.ui.keyCode.DOWN:case d.ui.keyCode.LEFT:if(b.preventDefault(),!a._keySliding&&(a._keySliding=!0,d(this).addClass("ui-state-active"),e=a._start(b,c),!1===e))return}g=a.options.step;e=a.options.values&&a.options.values.length?
f=a.values(c):f=a.value();switch(b.keyCode){case d.ui.keyCode.HOME:f=a._valueMin();break;case d.ui.keyCode.END:f=a._valueMax();break;case d.ui.keyCode.PAGE_UP:f=a._trimAlignValue(e+(a._valueMax()-a._valueMin())/5);break;case d.ui.keyCode.PAGE_DOWN:f=a._trimAlignValue(e-(a._valueMax()-a._valueMin())/5);break;case d.ui.keyCode.UP:case d.ui.keyCode.RIGHT:if(e===a._valueMax())return;f=a._trimAlignValue(e+g);break;case d.ui.keyCode.DOWN:case d.ui.keyCode.LEFT:if(e===a._valueMin())return;f=a._trimAlignValue(e-
g)}a._slide(b,c,f)}}).keyup(function(b){var c=d(this).data("index.ui-slider-handle");a._keySliding&&(a._keySliding=!1,a._stop(b,c),a._change(b,c),d(this).removeClass("ui-state-active"))});this._refreshValue();this._animateOff=!1},destroy:function(){this.handles.remove();this.range.remove();this.element.removeClass("ui-slider ui-slider-horizontal ui-slider-vertical ui-slider-disabled ui-widget ui-widget-content ui-corner-all").removeData("slider").unbind(".slider");this._mouseDestroy();return this},
_mouseCapture:function(a){var b=this.options,c,f,e,g,h;if(b.disabled)return!1;this.elementSize={width:this.element.outerWidth(),height:this.element.outerHeight()};this.elementOffset=this.element.offset();c=this._normValueFromMouse({x:a.pageX,y:a.pageY});f=this._valueMax()-this._valueMin()+1;g=this;this.handles.each(function(b){var a=Math.abs(c-g.values(b));f>a&&(f=a,e=d(this),h=b)});!0===b.range&&this.values(1)===b.min&&(h+=1,e=d(this.handles[h]));if(!1===this._start(a,h))return!1;this._mouseSliding=
!0;g._handleIndex=h;e.addClass("ui-state-active").focus();b=e.offset();this._clickOffset=!d(a.target).parents().andSelf().is(".ui-slider-handle")?{left:0,top:0}:{left:a.pageX-b.left-e.width()/2,top:a.pageY-b.top-e.height()/2-(parseInt(e.css("borderTopWidth"),10)||0)-(parseInt(e.css("borderBottomWidth"),10)||0)+(parseInt(e.css("marginTop"),10)||0)};this.handles.hasClass("ui-state-hover")||this._slide(a,h,c);return this._animateOff=!0},_mouseStart:function(){return!0},_mouseDrag:function(a){var b=this._normValueFromMouse({x:a.pageX,
y:a.pageY});this._slide(a,this._handleIndex,b);return!1},_mouseStop:function(a){this.handles.removeClass("ui-state-active");this._mouseSliding=!1;this._stop(a,this._handleIndex);this._change(a,this._handleIndex);this._clickOffset=this._handleIndex=null;return this._animateOff=!1},_detectOrientation:function(){this.orientation="vertical"===this.options.orientation?"vertical":"horizontal"},_normValueFromMouse:function(a){var b;"horizontal"===this.orientation?(b=this.elementSize.width,a=a.x-this.elementOffset.left-
(this._clickOffset?this._clickOffset.left:0)):(b=this.elementSize.height,a=a.y-this.elementOffset.top-(this._clickOffset?this._clickOffset.top:0));b=a/b;1<b&&(b=1);0>b&&(b=0);"vertical"===this.orientation&&(b=1-b);a=this._valueMax()-this._valueMin();b=this._valueMin()+b*a;return this._trimAlignValue(b)},_start:function(a,b){var c={handle:this.handles[b],value:this.value()};this.options.values&&this.options.values.length&&(c.value=this.values(b),c.values=this.values());return this._trigger("start",
a,c)},_slide:function(a,b,c){var d;if(this.options.values&&this.options.values.length){d=this.values(b?0:1);if(2===this.options.values.length&&!0===this.options.range&&(0===b&&c>d||1===b&&c<d))c=d;c!==this.values(b)&&(d=this.values(),d[b]=c,a=this._trigger("slide",a,{handle:this.handles[b],value:c,values:d}),this.values(b?0:1),!1!==a&&this.values(b,c,!0))}else c!==this.value()&&(a=this._trigger("slide",a,{handle:this.handles[b],value:c}),!1!==a&&this.value(c))},_stop:function(a,b){var c={handle:this.handles[b],
value:this.value()};this.options.values&&this.options.values.length&&(c.value=this.values(b),c.values=this.values());this._trigger("stop",a,c)},_change:function(a,b){if(!this._keySliding&&!this._mouseSliding){var c={handle:this.handles[b],value:this.value()};this.options.values&&this.options.values.length&&(c.value=this.values(b),c.values=this.values());this._trigger("change",a,c)}},value:function(a){if(arguments.length)this.options.value=this._trimAlignValue(a),this._refreshValue(),this._change(null,
0);else return this._value()},values:function(a,b){var c,f,e;if(1<arguments.length)this.options.values[a]=this._trimAlignValue(b),this._refreshValue(),this._change(null,a);else if(arguments.length)if(d.isArray(arguments[0])){c=this.options.values;f=arguments[0];for(e=0;e<c.length;e+=1)c[e]=this._trimAlignValue(f[e]),this._change(null,e);this._refreshValue()}else return this.options.values&&this.options.values.length?this._values(a):this.value();else return this._values()},_setOption:function(a,b){var c,
f=0;d.isArray(this.options.values)&&(f=this.options.values.length);d.Widget.prototype._setOption.apply(this,arguments);switch(a){case "disabled":b?(this.handles.filter(".ui-state-focus").blur(),this.handles.removeClass("ui-state-hover"),this.handles.propAttr("disabled",!0),this.element.addClass("ui-disabled")):(this.handles.propAttr("disabled",!1),this.element.removeClass("ui-disabled"));break;case "orientation":this._detectOrientation();this.element.removeClass("ui-slider-horizontal ui-slider-vertical").addClass("ui-slider-"+
this.orientation);this._refreshValue();break;case "value":this._animateOff=!0;this._refreshValue();this._change(null,0);this._animateOff=!1;break;case "values":this._animateOff=!0;this._refreshValue();for(c=0;c<f;c+=1)this._change(null,c);this._animateOff=!1}},_value:function(){var a=this.options.value;return a=this._trimAlignValue(a)},_values:function(a){var b,c;if(arguments.length)return b=this.options.values[a],b=this._trimAlignValue(b);b=this.options.values.slice();for(c=0;c<b.length;c+=1)b[c]=
this._trimAlignValue(b[c]);return b},_trimAlignValue:function(a){if(a<=this._valueMin())return this._valueMin();if(a>=this._valueMax())return this._valueMax();var b=0<this.options.step?this.options.step:1,c=(a-this._valueMin())%b,a=a-c;2*Math.abs(c)>=b&&(a+=0<c?b:-b);return parseFloat(a.toFixed(5))},_valueMin:function(){return this.options.min},_valueMax:function(){return this.options.max},_refreshValue:function(){var a=this.options.range,b=this.options,c=this,f=!this._animateOff?b.animate:!1,e,g=
{},h,k,i,j;if(this.options.values&&this.options.values.length)this.handles.each(function(a){e=100*((c.values(a)-c._valueMin())/(c._valueMax()-c._valueMin()));g["horizontal"===c.orientation?"left":"bottom"]=e+"%";d(this).stop(1,1)[f?"animate":"css"](g,b.animate);if(!0===c.options.range)if("horizontal"===c.orientation){if(0===a)c.range.stop(1,1)[f?"animate":"css"]({left:e+"%"},b.animate);if(1===a)c.range[f?"animate":"css"]({width:e-h+"%"},{queue:!1,duration:b.animate})}else{if(0===a)c.range.stop(1,
1)[f?"animate":"css"]({bottom:e+"%"},b.animate);if(1===a)c.range[f?"animate":"css"]({height:e-h+"%"},{queue:!1,duration:b.animate})}h=e});else{k=this.value();i=this._valueMin();j=this._valueMax();e=j!==i?100*((k-i)/(j-i)):0;g["horizontal"===c.orientation?"left":"bottom"]=e+"%";this.handle.stop(1,1)[f?"animate":"css"](g,b.animate);if("min"===a&&"horizontal"===this.orientation)this.range.stop(1,1)[f?"animate":"css"]({width:e+"%"},b.animate);if("max"===a&&"horizontal"===this.orientation)this.range[f?
"animate":"css"]({width:100-e+"%"},{queue:!1,duration:b.animate});if("min"===a&&"vertical"===this.orientation)this.range.stop(1,1)[f?"animate":"css"]({height:e+"%"},b.animate);if("max"===a&&"vertical"===this.orientation)this.range[f?"animate":"css"]({height:100-e+"%"},{queue:!1,duration:b.animate})}}});d.extend(d.ui.slider,{version:"1.8.24"})})(jQuery);
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.auiplugin:jquery-ui-widgets', location = 'node_modules/@atlassian/aui/src/js-vendor/jquery/jquery-ui/jquery.ui.tabs.js' */
(function(d){var n=0,o=0;d.widget("ui.tabs",{options:{add:null,ajaxOptions:null,cache:!1,cookie:null,collapsible:!1,disable:null,disabled:[],enable:null,event:"click",fx:null,idPrefix:"ui-tabs-",load:null,panelTemplate:"<div></div>",remove:null,select:null,show:null,spinner:"<em>Loading&#8230;</em>",tabTemplate:"<li><a href='#{href}'><span>#{label}</span></a></li>"},_create:function(){this._tabify(!0)},_setOption:function(a,d){"selected"==a?this.options.collapsible&&d==this.options.selected||this.select(d):
(this.options[a]=d,this._tabify())},_tabId:function(a){return a.title&&a.title.replace(/\s/g,"_").replace(/[^\w\u00c0-\uFFFF-]/g,"")||this.options.idPrefix+ ++n},_sanitizeSelector:function(a){return a.replace(/:/g,"\\:")},_cookie:function(){var a=this.cookie||(this.cookie=this.options.cookie.name||"ui-tabs-"+ ++o);return d.cookie.apply(null,[a].concat(d.makeArray(arguments)))},_ui:function(a,d){return{tab:a,panel:d,index:this.anchors.index(a)}},_cleanup:function(){this.lis.filter(".ui-state-processing").removeClass("ui-state-processing").find("span:data(label.tabs)").each(function(){var a=
d(this);a.html(a.data("label.tabs")).removeData("label.tabs")})},_tabify:function(a){function e(b,a){b.css("display","");!d.support.opacity&&a.opacity&&b[0].style.removeAttribute("filter")}var b=this,c=this.options,g=/^#.+/;this.list=this.element.find("ol,ul").eq(0);this.lis=d(" > li:has(a[href])",this.list);this.anchors=this.lis.map(function(){return d("a",this)[0]});this.panels=d([]);this.anchors.each(function(a,e){var h=d(e).attr("href"),f=h.split("#")[0],k;if(f&&(f===location.toString().split("#")[0]||
(k=d("base")[0])&&f===k.href))h=e.hash,e.href=h;g.test(h)?b.panels=b.panels.add(b.element.find(b._sanitizeSelector(h))):h&&"#"!==h?(d.data(e,"href.tabs",h),d.data(e,"load.tabs",h.replace(/#.*$/,"")),h=b._tabId(e),e.href="#"+h,f=b.element.find("#"+h),f.length||(f=d(c.panelTemplate).attr("id",h).addClass("ui-tabs-panel ui-widget-content ui-corner-bottom").insertAfter(b.panels[a-1]||b.list),f.data("destroy.tabs",!0)),b.panels=b.panels.add(f)):c.disabled.push(a)});a?(this.element.addClass("ui-tabs ui-widget ui-widget-content ui-corner-all"),
this.list.addClass("ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all"),this.lis.addClass("ui-state-default ui-corner-top"),this.panels.addClass("ui-tabs-panel ui-widget-content ui-corner-bottom"),void 0===c.selected?(location.hash&&this.anchors.each(function(b,a){if(a.hash==location.hash)return c.selected=b,!1}),"number"!==typeof c.selected&&c.cookie&&(c.selected=parseInt(b._cookie(),10)),"number"!==typeof c.selected&&this.lis.filter(".ui-tabs-selected").length&&(c.selected=
this.lis.index(this.lis.filter(".ui-tabs-selected"))),c.selected=c.selected||(this.lis.length?0:-1)):null===c.selected&&(c.selected=-1),c.selected=0<=c.selected&&this.anchors[c.selected]||0>c.selected?c.selected:0,c.disabled=d.unique(c.disabled.concat(d.map(this.lis.filter(".ui-state-disabled"),function(a){return b.lis.index(a)}))).sort(),-1!=d.inArray(c.selected,c.disabled)&&c.disabled.splice(d.inArray(c.selected,c.disabled),1),this.panels.addClass("ui-tabs-hide"),this.lis.removeClass("ui-tabs-selected ui-state-active"),
0<=c.selected&&this.anchors.length&&(b.element.find(b._sanitizeSelector(b.anchors[c.selected].hash)).removeClass("ui-tabs-hide"),this.lis.eq(c.selected).addClass("ui-tabs-selected ui-state-active"),b.element.queue("tabs",function(){b._trigger("show",null,b._ui(b.anchors[c.selected],b.element.find(b._sanitizeSelector(b.anchors[c.selected].hash))[0]))}),this.load(c.selected)),d(window).bind("unload",function(){b.lis.add(b.anchors).unbind(".tabs");b.lis=b.anchors=b.panels=null})):c.selected=this.lis.index(this.lis.filter(".ui-tabs-selected"));
this.element[c.collapsible?"addClass":"removeClass"]("ui-tabs-collapsible");c.cookie&&this._cookie(c.selected,c.cookie);for(var a=0,f;f=this.lis[a];a++)d(f)[-1!=d.inArray(a,c.disabled)&&!d(f).hasClass("ui-tabs-selected")?"addClass":"removeClass"]("ui-state-disabled");!1===c.cache&&this.anchors.removeData("cache.tabs");this.lis.add(this.anchors).unbind(".tabs");if("mouseover"!==c.event){var k=function(b,a){a.is(":not(.ui-state-disabled)")&&a.addClass("ui-state-"+b)};this.lis.bind("mouseover.tabs",
function(){k("hover",d(this))});this.lis.bind("mouseout.tabs",function(){d(this).removeClass("ui-state-hover")});this.anchors.bind("focus.tabs",function(){k("focus",d(this).closest("li"))});this.anchors.bind("blur.tabs",function(){d(this).closest("li").removeClass("ui-state-focus")})}var j,i;c.fx&&(d.isArray(c.fx)?(j=c.fx[0],i=c.fx[1]):j=i=c.fx);var l=i?function(a,c){d(a).closest("li").addClass("ui-tabs-selected ui-state-active");c.hide().removeClass("ui-tabs-hide").animate(i,i.duration||"normal",
function(){e(c,i);b._trigger("show",null,b._ui(a,c[0]))})}:function(a,c){d(a).closest("li").addClass("ui-tabs-selected ui-state-active");c.removeClass("ui-tabs-hide");b._trigger("show",null,b._ui(a,c[0]))},m=j?function(a,c){c.animate(j,j.duration||"normal",function(){b.lis.removeClass("ui-tabs-selected ui-state-active");c.addClass("ui-tabs-hide");e(c,j);b.element.dequeue("tabs")})}:function(a,c){b.lis.removeClass("ui-tabs-selected ui-state-active");c.addClass("ui-tabs-hide");b.element.dequeue("tabs")};
this.anchors.bind(c.event+".tabs",function(){var a=this,e=d(a).closest("li"),f=b.panels.filter(":not(.ui-tabs-hide)"),g=b.element.find(b._sanitizeSelector(a.hash));if(e.hasClass("ui-tabs-selected")&&!c.collapsible||e.hasClass("ui-state-disabled")||e.hasClass("ui-state-processing")||b.panels.filter(":animated").length||b._trigger("select",null,b._ui(this,g[0]))===false){this.blur();return false}c.selected=b.anchors.index(this);b.abort();if(c.collapsible){if(e.hasClass("ui-tabs-selected")){c.selected=
-1;c.cookie&&b._cookie(c.selected,c.cookie);b.element.queue("tabs",function(){m(a,f)}).dequeue("tabs");this.blur();return false}if(!f.length){c.cookie&&b._cookie(c.selected,c.cookie);b.element.queue("tabs",function(){l(a,g)});b.load(b.anchors.index(this));this.blur();return false}}c.cookie&&b._cookie(c.selected,c.cookie);if(g.length){f.length&&b.element.queue("tabs",function(){m(a,f)});b.element.queue("tabs",function(){l(a,g)});b.load(b.anchors.index(this))}else throw"jQuery UI Tabs: Mismatching fragment identifier.";
d.browser.msie&&this.blur()});this.anchors.bind("click.tabs",function(){return false})},_getIndex:function(a){"string"==typeof a&&(a=this.anchors.index(this.anchors.filter("[href$='"+a+"']")));return a},destroy:function(){var a=this.options;this.abort();this.element.unbind(".tabs").removeClass("ui-tabs ui-widget ui-widget-content ui-corner-all ui-tabs-collapsible").removeData("tabs");this.list.removeClass("ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all");this.anchors.each(function(){var a=
d.data(this,"href.tabs");a&&(this.href=a);var b=d(this).unbind(".tabs");d.each(["href","load","cache"],function(a,d){b.removeData(d+".tabs")})});this.lis.unbind(".tabs").add(this.panels).each(function(){d.data(this,"destroy.tabs")?d(this).remove():d(this).removeClass("ui-state-default ui-corner-top ui-tabs-selected ui-state-active ui-state-hover ui-state-focus ui-state-disabled ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide")});a.cookie&&this._cookie(null,a.cookie);return this},add:function(a,
e,b){void 0===b&&(b=this.anchors.length);var c=this,g=this.options,e=d(g.tabTemplate.replace(/#\{href\}/g,a).replace(/#\{label\}/g,e)),a=!a.indexOf("#")?a.replace("#",""):this._tabId(d("a",e)[0]);e.addClass("ui-state-default ui-corner-top").data("destroy.tabs",!0);var f=c.element.find("#"+a);f.length||(f=d(g.panelTemplate).attr("id",a).data("destroy.tabs",!0));f.addClass("ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide");b>=this.lis.length?(e.appendTo(this.list),f.appendTo(this.list[0].parentNode)):
(e.insertBefore(this.lis[b]),f.insertBefore(this.panels[b]));g.disabled=d.map(g.disabled,function(a){return a>=b?++a:a});this._tabify();1==this.anchors.length&&(g.selected=0,e.addClass("ui-tabs-selected ui-state-active"),f.removeClass("ui-tabs-hide"),this.element.queue("tabs",function(){c._trigger("show",null,c._ui(c.anchors[0],c.panels[0]))}),this.load(0));this._trigger("add",null,this._ui(this.anchors[b],this.panels[b]));return this},remove:function(a){var a=this._getIndex(a),e=this.options,b=this.lis.eq(a).remove(),
c=this.panels.eq(a).remove();b.hasClass("ui-tabs-selected")&&1<this.anchors.length&&this.select(a+(a+1<this.anchors.length?1:-1));e.disabled=d.map(d.grep(e.disabled,function(b){return b!=a}),function(b){return b>=a?--b:b});this._tabify();this._trigger("remove",null,this._ui(b.find("a")[0],c[0]));return this},enable:function(a){var a=this._getIndex(a),e=this.options;if(-1!=d.inArray(a,e.disabled))return this.lis.eq(a).removeClass("ui-state-disabled"),e.disabled=d.grep(e.disabled,function(b){return b!=
a}),this._trigger("enable",null,this._ui(this.anchors[a],this.panels[a])),this},disable:function(a){var a=this._getIndex(a),d=this.options;a!=d.selected&&(this.lis.eq(a).addClass("ui-state-disabled"),d.disabled.push(a),d.disabled.sort(),this._trigger("disable",null,this._ui(this.anchors[a],this.panels[a])));return this},select:function(a){a=this._getIndex(a);if(-1==a)if(this.options.collapsible&&-1!=this.options.selected)a=this.options.selected;else return this;this.anchors.eq(a).trigger(this.options.event+
".tabs");return this},load:function(a){var a=this._getIndex(a),e=this,b=this.options,c=this.anchors.eq(a)[0],g=d.data(c,"load.tabs");this.abort();if(!g||0!==this.element.queue("tabs").length&&d.data(c,"cache.tabs"))this.element.dequeue("tabs");else{this.lis.eq(a).addClass("ui-state-processing");if(b.spinner){var f=d("span",c);f.data("label.tabs",f.html()).html(b.spinner)}this.xhr=d.ajax(d.extend({},b.ajaxOptions,{url:g,success:function(f,g){e.element.find(e._sanitizeSelector(c.hash)).html(f);e._cleanup();
b.cache&&d.data(c,"cache.tabs",!0);e._trigger("load",null,e._ui(e.anchors[a],e.panels[a]));try{b.ajaxOptions.success(f,g)}catch(i){}},error:function(d,f){e._cleanup();e._trigger("load",null,e._ui(e.anchors[a],e.panels[a]));try{b.ajaxOptions.error(d,f,a,c)}catch(g){}}}));e.element.dequeue("tabs");return this}},abort:function(){this.element.queue([]);this.panels.stop(!1,!0);this.element.queue("tabs",this.element.queue("tabs").splice(-2,2));this.xhr&&(this.xhr.abort(),delete this.xhr);this._cleanup();
return this},url:function(a,d){this.anchors.eq(a).removeData("cache.tabs").data("load.tabs",d);return this},length:function(){return this.anchors.length}});d.extend(d.ui.tabs,{version:"1.8.24"});d.extend(d.ui.tabs.prototype,{rotation:null,rotate:function(a,d){var b=this,c=this.options,g=b._rotate||(b._rotate=function(d){clearTimeout(b.rotation);b.rotation=setTimeout(function(){var a=c.selected;b.select(++a<b.anchors.length?a:0)},a);d&&d.stopPropagation()}),f=b._unrotate||(b._unrotate=!d?function(a){a.clientX&&
b.rotate(null)}:function(){g()});a?(this.element.bind("tabsshow",g),this.anchors.bind(c.event+".tabs",f),g()):(clearTimeout(b.rotation),this.element.unbind("tabsshow",g),this.anchors.unbind(c.event+".tabs",f),delete this._rotate,delete this._unrotate);return this}})})(jQuery);
}catch(e){WRMCB(e)};