WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'com.atlassian.confluence.editor:editor-resources-conf-frontend', location = 'tinymce3/plugins/autocomplete/autocomplete-settings.js' */
define("confluence-editor/tinymce3/plugins/autocomplete/autocomplete-settings",["ajs"],function(b){return{Settings:{},log:function(d){return function(e,f,a){var c=null!=a&&"object"!==typeof a;b.debug(d+" - "+e+" : "+(f||null)+(null!=a?c?" = "+a:" >":""));a&&!c&&b.debug(a)}}}});require("confluence/module-exporter").exportModuleAsGlobal("confluence-editor/tinymce3/plugins/autocomplete/autocomplete-settings","Confluence.Editor.Autocompleter");
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.editor:editor-resources-conf-frontend', location = 'tinymce3/plugins/autocomplete/autocomplete-util.js' */
define("confluence-editor/tinymce3/plugins/autocomplete/autocomplete-util",["jquery","confluence-rest/confluence-rest"],function(k,f){var h=function(a,c,g,b,d){var e;a.statusMessage?e=[[{html:a.statusMessage,className:"error"}]]:(a=c?f.REST.makeRestMatrixFromSearchData(a):f.REST.makeRestMatrixFromData(a,b),e=f.REST.convertFromRest(a));g(e,c,function(a,b){d&&typeof d==="function"&&d(e,a,b)})};return{dropdownLink:function(a,c,g){return"<a href='#' class='"+(c||"")+"'><span class='icon "+(g||"")+"'></span><span>"+
a+"</span></a>"},getRestData:function(a,c,g,b,d,e,f){var i=c(b),j=a.settings.cacheManager,c=j.get(b);i?(a=k.ajax({type:"GET",url:i,data:g(a,b),dataType:"json",global:!1,timeout:5E3}),a.done(function(a){j.put(b,a)}),c?h(c,b,d,e,f):(a.done(function(a){h(a,b,d,e,f)}),a.fail(function(a,c){"timeout"==c&&h({statusMessage:"Timeout",query:b},b,d,e)}))):d([],b)}}});require("confluence/module-exporter").exportModuleAsGlobal("confluence-editor/tinymce3/plugins/autocomplete/autocomplete-util","Confluence.Editor.Autocompleter.Util");
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.editor:editor-resources-conf-frontend', location = 'tinymce3/plugins/autocomplete/autocomplete-control.js' */
define("confluence-editor/tinymce3/plugins/autocomplete/autocomplete-control",["ajs","jquery","confluence-editor/tinymce3/plugins/autocomplete/autocomplete-settings","document","confluence/property-panel"],function(c,g,z,A,t){var v=function(d,r){var e,a,h=z.log("Autocompleter.Control"),s=require("tinymce"),b={},o=d.selection,u=o.getRng(!0),p=u.startOffset,l=u.startContainer;a=l.nodeValue;var m=r.leadingChar,x=d.getDoc(),n=r.backWords||0,i=z.Settings[m||"["];e=!i||"undefined"===typeof i.preventStartNodes?
"div.code, a[href], img, pre":i.preventStartNodes;if(g("#autocomplete",x).length)return c.debug("init","Autocomplete already exists, returning null."),null;b.backWords=n;b.maxResults=r.maxResults||10;null==a&&(u.collapsed&&p&&l.childNodes[p-1])&&(l=l.childNodes[p-1],p=(a=l.nodeValue)&&a.length||0);var q="";if(null!=a)for(var q=(a+"").substring(0,p),k=l.previousSibling;k&&3===k.nodeType;)q=k.nodeValue+q,k=k.previousSibling;var k=[/([("'<\(\u201c\u2018]\[|[\ufeff\u200b\u2014\s\xa0].)$/,/(\([^!])$/,
/(\/\/)$/],f;if(f=!n)if(f=q){a:{q+=m;f=0;for(var F=k.length;f<F;f++)if(k[f].test(q)){k=!0;break a}k=!1}f=!k}if(f)return h("init","Cursor is in wrong word location to start autocomplete, returning null."),null;if(g(l).closest(e).length)return h("init","Cursor is in wrong node to start autocomplete, returning null."),null;t&&t.current&&(t.shouldCreate=!1,t.destroy());!m&&null==a&&(c.debug("init","No text available for suggestion, range is",u),a="");b.getContainer=function(){return g("#autocomplete",
x)};if(u.collapsed&&n&&a){e=l;a=p;k=function(b,j,c){!j.global&&(j=RegExp(j.source,"g"+"i".slice(0,j.ignoreCase)+"m".slice(0,j.multiLine)));c==null?c=b.length:c<0&&(c=0);for(var b=b.substring(0,c+1),c=-1,d=0,a;(a=j.exec(b))!=null;){c=a.index;j.lastIndex=++d}return c};for(q=0;q<n;q++){f=e.nodeValue.substring(0,a);for(a=k(f,/\s+/,a);-1==a;)if((f=e.previousSibling)&&3===f.nodeType)e=f,(f=f.nodeValue)&&(a=k(f,/\s+/,f.length));else{q=n;break}}a+=1;s.isIE&&1==n?(n=o.getRng(),n.moveStart("character",a-p),
n.select()):(n=o.getRng(!0),n.setStart(e,a),n.setEnd(l,p),o.setRng(n))}p=o&&o.getNode()&&o.getNode().classList.contains("placeholder-inline-tasks")?"":o.getContent({format:"text"}).replace("\n","");h("init","suggestionHtml",p);l=c("span").attr("id","autocomplete");m&&l.append(c("span").attr("id","autocomplete-trigger").text(m));m=c("span").attr("id","autocomplete-search-text");m.text(c.Rte.HIDDEN_CHAR);l.append(m);o.setNode(l[0]);var w=b.getContainer();b.previousSearchText="";b.settings=i;!1!==i.cache&&
!i.cacheManager?i.cacheManager=new c.Confluence.localStorageCacheManager(i.ch):!1===i.cache&&!i.cacheManager&&(i.cacheManager={get:g.noop,put:g.noop});i=g("#autocomplete-search-text",b.getContainer());m=g(x.createElement("span")).text(p||c.Rte.HIDDEN_CHAR);i.empty().append(m);o.select(m[0],!0);o.collapse();var B=function(c,j){if(b.onBeforeKey&&!b.onBeforeKey(j,b.text())){s.dom.Event.cancel(j);h("before","blocked by onBeforeKey: "+j.keyCode);return false}},C=function(c,j){var a=o.getRng(true),d=b.getContainer(),
e=a.startContainer,a=e.parentNode;e.nodeType===3&&(a=a.parentNode);var f=(e=a?a.parentNode:null)?e.parentNode:null,d=a!==d[0]&&e!==d[0]&&f!==d[0];if(j.keyCode===27||d){h("after","dying because of: "+(d?"outside search span":"escape pressed"));b.die()}else if(b.onAfterKey&&!b.onAfterKey(j,b.text())){s.dom.Event.cancel(j);h("after","blocked by onAfterKey: "+j.keyCode);return false}},D=function(c,a){if(b.onKeyPress&&!b.onKeyPress(a,b.text())){s.dom.Event.cancel(a);h("press","blocked by onKeyPress: "+
a.keyCode);return false}},E=function(a,c){if(b.getContainer()[0]!=c.target.parentNode){h("click","Clicked outside of autocomplete, closing.");b.die()}};d.onKeyDown.addToTop(B);d.onKeyUp.addToTop(C);d.onKeyPress.addToTop(D);d.onClick.addToTop(E);b.word="";r.keepAlias?h("init","No suggestion based on previous or selected text"):b.word=p;c.Rte.showElement(w[0]);i=s.DOM.getPos(w[0]);m=w.height();b.left=i.x;b.top=i.y+m;b.text=function(a){var d=g("#autocomplete-search-text",b.getContainer());if(a!=null){d.html(a);
return this}a=c.escapeEntities(d.text());return a.replace(c.Rte.HIDDEN_CHAR,"")};b.plainText=function(a){var d=g("#autocomplete-search-text",b.getContainer());if(a!=null){d.text(a);return this}a=d.text();return a.replace(c.Rte.HIDDEN_CHAR,"")};var y=function(a,c){var d=b.getContainer();return v.replaceWithTextAndGetRange(d,a,c)};b.replaceWithSelectedSearchText=function(){var a=b.text();h("replaceWithSelectedSearchText",a);y(a,false);return a};b.die=function(a){if(b.dying)c.debug("die","Already dying, returning.");
else{b.dying=true;if(t)t.shouldCreate=true;if(b.getContainer().length){h("die","Tearing down autocomplete, cleaning up autocompleter");a=(a||r.backWords?"":b.settings.ch)+b.text();u=y(a,true)}setTimeout(function(){h("die","Removing autocomplete-control keyboard listeners.");d.onKeyDown.remove(B);d.onKeyUp.remove(C);d.onClick.remove(E);d.onKeyPress.remove(D)},1);c.Rte.unbindScroll("autocomplete");g(A).unbind("click.autocomplete-outside");this.onDeath&&this.onDeath()}};c.Rte.bindScroll("autocomplete",
function(a){c.debug("scrolling:",a);if(c.Rte.isAnyPartShown(w))b.onScroll();else b.die()});g(A).bind("click.autocomplete-outside",function(a){g(a.target).closest("#autocomplete-dropdown, .aui-datepicker-dialog, .ui-datepicker-header").length||b.die()});c.Rte.getEditor().onBeforeExecCommand.add(function(a,c){c=="mceConfSavePage"&&b.die()});b.update=function(a){c.Rte.BookmarkManager.storeBookmark();y("",true);this.settings.update(this,a)};b.removeSpan=function(){b.getContainer().remove()};return b};
v.removeOrphanedControl=function(){var d=g(c.Rte.getEditor().getDoc()),r=d.find("#autocomplete"),e;if(!r.length)return null;e=d.find("#autocomplete-trigger").text();d=d.find("#autocomplete-search-text").text();v.replaceWithTextAndGetRange(r,d,!1);return{leadingChar:e,content:d}};v.replaceWithTextAndGetRange=function(d,g,e){if(d.length){var g=g||"",e=e||!g,a=c.Rte.getEditor(),h=d[0].parentNode,s=c.Rte.Content.getChildIndex(h,d[0]),b=e?1:0,e=a.selection.getRng(!0);e.setStart(h,s+b);e.setEnd(h,s+1);
d.before(g||c.Rte.HIDDEN_CHAR).remove();a.selection.setRng(e);return e}c.log("replaceWithTextAndGetRange Error: attempting to replace a non-existent element")};return v});require("confluence/module-exporter").exportModuleAsGlobal("confluence-editor/tinymce3/plugins/autocomplete/autocomplete-control","Confluence.Editor.Autocompleter.Control");
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.editor:editor-resources-conf-frontend', location = 'tinymce3/plugins/autocomplete/autocomplete-manager.js' */
define("confluence-editor/tinymce3/plugins/autocomplete/autocomplete-manager","ajs jquery window confluence/input-driven-dropdown confluence-editor/tinymce3/plugins/autocomplete/autocomplete-settings confluence-editor/tinymce3/plugins/autocomplete/autocomplete-control".split(" "),function(e,j,p,q,h,k){h.log("Autocompleter.Manager");var c,a,n=function(m){c=k(e.Rte.getEditor(),m);if(!c)return false;e.trigger("synchrony.stop",{id:"confluence.autocomplete-plugin"});e.trigger("rte-autocomplete-on-start",
{triggerChar:c.settings.ch});var r=j(p).width(),i,g=function(b){var f=j("#autocomplete-dropdown"),d=c.getContainer(),a,m,g,h,l;f.length||(f=e("div").addClass("aui-dd-parent quick-nav-drop-down").attr("id","autocomplete-dropdown").appendTo("body"));a=e.Position.spaceAboveBelow(e.Rte.getEditorFrame(),d);b.find("ol:has(a.menu-header)").addClass("top-menu-item");b.find("ol:empty").hide();f.append(b);g=e.Rte.Content.offset(d);h=Math.max(f.width()+g.left-r+10,0);m=g.left-h-0;b=b.outerHeight(true);l=b+10;
if(i){var k;k=i==1?a.above>=l:a.below>=l;k||(i=null)}if(!i)i=a.below>=l?2:a.above>=l?1:a.below>a.above?2:1;a=f.find(".autocomplete-dropdown-arrow");a.length||(a=j('<div class="autocomplete-dropdown-arrow"></div>'));if(i===1){a.addClass("autocomplete-dropdown-bottom-arrow").css({top:b-1});d=g.top-b-10}else{a.removeClass("autocomplete-dropdown-bottom-arrow").css("top","");d=g.top+d.height()+10}a.css({left:h}).appendTo(f);f.css({position:"absolute",top:d,left:m})};a=new q("inputdriven-dropdown",{onShow:function(b){e.trigger("rte-autocomplete-on-show",
{triggerChar:c.settings.ch});var a=e.Rte.getEditorFrame();a&&a.shim&&a.shim.hide();b.find("a.menu-header").unbind().click(function(b){b.preventDefault();c.die()});this.reset();c.settings.selectFirstItem&&b.find("a:not('.menu-header')").length&&e.dropDown.current.moveDown()},dropdownPlacement:g,onDeath:function(){j("#autocomplete-dropdown").remove()},ajsDropDownOptions:{selectionHandler:function(b,a){b.preventDefault();var d=j.data(a[0],"properties");d&&typeof d.callback==="function"?d.callback(c):
d.className!=="menu-header"&&c.update(d);e.trigger("rte-autocomplete-on-select",{triggerChar:c.settings.ch,result:d});c.die()},moveHandler:function(b,a){var c=e.dropDown.current;b&&b.find("a").is(".menu-header")&&(a=="up"?c.moveUp():c.moveDown())},className:"autocomplete "+c.settings.dropDownClassName},getDataAndRunCallback:function(b){c&&c.settings.getDataAndRunCallback&&c.settings.getDataAndRunCallback(c,b,function(f,d,e,g){f.unshift([{className:"menu-header dropdown-prevent-highlight",href:"#",
name:c.settings.getHeaderText(c,b)}]);f.push(c.settings.getAdditionalLinks(c,b,e));a&&a.show(f,d,g||[d])})},dropDownDelay:c.settings.dropDownDelay});c.onBeforeKey=function(b,a){var c=require("tinymce");if(b.keyCode===40||b.keyCode===38||b.keyCode===13){c.dom.Event.cancel(b);return false}if(b.keyCode===27||b.keyCode===9||b.keyCode===8&&!a){this.die(b.keyCode===8);return false}return true};c.onKeyPress=function(b){var a=require("tinymce"),d=String.fromCharCode(j.browser.msie?b.keyCode:b.which);if(b.keyCode===
13){a.dom.Event.cancel(b);return false}e.indexOf(this.settings.endChars,d)!==-1&&c.die();return true};var h=/\S{2,}/;c.onAfterKey=function(b,f){if(b.keyCode===40||b.keyCode===38||b.keyCode===13){var d=e.dropDown.current;if(!d)return false;if(d.getFocusIndex()==-1&&b.keyCode===13){c.die();c=null;return true}if(!b.which)b.which=b.keyCode;return d.moveFocus(b)}if(!(d=b.keyCode===8&&!f))d=/[\u4E00-\u9FFF]/gi.test(f);(d||h.test(f))&&a.change(f,d);return true};c.onDeath=function(){if(a){a.remove();a.closing=
true}e.trigger("synchrony.start",{id:"confluence.autocomplete-plugin"});e.trigger("rte-autocomplete-on-death",{triggerChar:c.settings.ch})};c.onScroll=function(){a.dd&&g(a.dd.$)};a.change(c.text(),"force");return true},o={getInputDrivenDropdown:function(){return a},triggerListener:function(c,e){var i=require("tinymce");if(e.metaKey)return true;var g=j.browser.msie?e.keyCode:e.which;a&&a.closing&&(a=null);g=String.fromCharCode(g);!a&&g in h.Settings&&n({leadingChar:g})&&i.dom.Event.cancel(e);return true},
shortcutFired:function(e,h){var i=h?0:1;a&&a.closing&&(a=null);if(a){i=h?0:c.backWords+1;c.die();c=null}return n({leadingChar:e,backWords:i})},reattach:function(){var a=k.removeOrphanedControl();a&&o.shortcutFired(a.leadingChar)}};return o});require("confluence/module-exporter").exportModuleAsGlobal("confluence-editor/tinymce3/plugins/autocomplete/autocomplete-manager","Confluence.Editor.Autocompleter.Manager");
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.editor:editor-resources-conf-frontend', location = 'tinymce3/plugins/autocomplete/editor_plugin_src.js' */
define("confluence-editor/tinymce3/plugins/autocomplete/editor_plugin_src",["tinymce","confluence/legacy-editor-global-AVOID-IF-POSSIBLE","ajs"],function(a,b,c){return{init:function(a){b.Autocompleter.Settings={};a.onPostRender.add(function(){c.debug("Autocomplete enabled, adding keyPress listener");a.onKeyPress.addToTop(b.Autocompleter.Manager.triggerListener);c.trigger("ready-editor-autocomplete")});a.onUndo.add(b.Autocompleter.Manager.reattach);a.onRedo.add(b.Autocompleter.Manager.reattach)},getInfo:function(){return{longname:"Auto Complete",
author:"Atlassian",authorurl:"http://www.atlassian.com",version:a.majorVersion+"."+a.minorVersion}}}});require("confluence/module-exporter").safeRequire("confluence-editor/tinymce3/plugins/autocomplete/editor_plugin_src",function(a){var b=require("tinymce");b.create("tinymce.plugins.AutoComplete",a);b.PluginManager.add("autocomplete",b.plugins.AutoComplete)});
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.editor:editor-resources-conf-frontend', location = 'tinymce3/plugins/autocomplete-link/autocomplete-settings-links.js' */
define("confluence-editor/tinymce3/plugins/autocomplete-link/autocomplete-settings-links","jquery ajs confluence-link-browser/link-object confluence-link-browser/link-adapter confluence/legacy-editor-global-AVOID-IF-POSSIBLE confluence/unescape-entities".split(" "),function(m,d,g,j,e,h){return function(){var i=e.Autocompleter,k=function(a){return a?d.contextPath()+"/rest/prototype/1/search.json":d.Meta.get("remote-user")?d.contextPath()+"/rest/prototype/1/session/history.json":null},l=function(a,
b){var c={"max-results":a.maxResults};if(b){c.query=h(b);c.search="name";c.preferredSpaceKey=d.Meta.get("space-key")}return c};e.Autocompleter.Settings["["]={ch:"[",cache:false,endChars:["]"],dropDownClassName:"autocomplete-links",selectFirstItem:true,getHeaderText:function(){return "Link suggestions"},getAdditionalLinks:function(a,b,c){if(b){a="Search for &lsquo;{0}&rsquo;";a=d.format(a,b)}else a="Search";
var f=e.LinkBrowser,a=[{className:"search-for",name:a,href:"#",callback:function(a){a.replaceWithSelectedSearchText();a=f.open({panelKey:f.SEARCH_PANEL});a.doSearch(a.getLocationPresenter().getRawLinkText())}},{className:"dropdown-insert-link",html:i.Util.dropdownLink("Insert web link","dropdown-prevent-highlight","editor-icon"),callback:function(a){a.replaceWithSelectedSearchText();f.open({panelKey:f.WEBLINK_PANEL})}}];c&&c(b,a);return a},getDataAndRunCallback:function(a,
b,c){e.Autocompleter.Util.getRestData(a,k,l,b,c,"content",function(a,b,c){if(b){var e;if(!(e=a.length<2)){a=a[1][0].restObj;a=a.type==="page"?a.space.key==d.Meta.get("space-key")&&a.title.toLowerCase()===b.toLowerCase():false;e=!a}e&&c.push({className:"insert-create-page-link",html:i.Util.dropdownLink("Insert link to create page","dropdown-prevent-highlight","editor-icon"),callback:function(a){var c=h(b),c=g.createLinkToNewPage(c,d.Meta.get("space-key"));a.update(c)}})}})},
update:function(a,b){b.restObj&&(b=g.fromREST(b.restObj));j.setLink(b)}}}});
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.editor:editor-resources-conf-frontend', location = 'tinymce3/plugins/autocomplete-link/editor_plugin_src.js' */
define("confluence-editor/tinymce3/plugins/autocomplete-link/editor_plugin_src",["tinymce","confluence-editor/tinymce3/plugins/autocomplete-link/autocomplete-settings-links","confluence/legacy-editor-global-AVOID-IF-POSSIBLE","confluence/dark-features"],function(c,a,d,e){return{init:function(b){b.addCommand("mceConfAutocompleteLink",function(){d.Autocompleter.Manager.shortcutFired("[")});e.isEnabled("editor.spa.uxenhancements")?b.addShortcut("meta+shift+K",b.getLang("AutoComplete"),"mceConfAutocompleteLink"):
b.addShortcut("ctrl+shift+K",b.getLang("AutoComplete"),"mceConfAutocompleteLink");a()},getInfo:function(){return{longname:"Auto Complete Link",author:"Atlassian",authorurl:"http://www.atlassian.com",version:c.majorVersion+"."+c.minorVersion}}}});require("confluence/module-exporter").safeRequire("confluence-editor/tinymce3/plugins/autocomplete-link/editor_plugin_src",function(c){var a=require("tinymce");a.create("tinymce.plugins.AutoCompleteLink",c);a.PluginManager.add("autocompletelink",a.plugins.AutoCompleteLink)});
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.editor:editor-resources-conf-frontend', location = 'tinymce3/plugins/autocomplete-media/autocomplete-settings-media.js' */
define("confluence-editor/tinymce3/plugins/autocomplete-media/autocomplete-settings-media","jquery ajs confluence-editor/utils/attachments-insert-utils tinymce confluence/macro-js-overrides confluence-rest/confluence-rest confluence/legacy-editor-global-AVOID-IF-POSSIBLE".split(" "),function(j,d,k,h,i,l,f){return function(){var m=function(c){var b=d.params.attachmentSourceContentId||d.Meta.get("content-id");return c?d.contextPath()+"/rest/prototype/1/search.json":+b?d.contextPath()+"/rest/prototype/1/content/"+
b+"/attachments.json":null},n=function(c,b){var a=d.MacroBrowser.getMacroMetadata("view-file")?[]:["image","word","excel","pdf","powerpoint","multimedia"];return b?{type:"attachment",attachmentType:a,search:"name","max-results":c.maxResults,query:b}:{attachmentType:a,"max-results":c.maxResults}};f.Autocompleter.Settings["!"]={ch:"!",cache:false,endChars:["!"],dropDownClassName:"autocomplete-media",selectFirstItem:true,getHeaderText:function(){return d.MacroBrowser.getMacroMetadata("view-file")?"File suggestions":
"Media suggestions"},getAdditionalLinks:function(){var c="Open file library";return[{className:"dropdown-insert-image",html:f.Autocompleter.Util.dropdownLink(c,"dropdown-prevent-highlight","editor-icon"),callback:function(b){b.replaceWithSelectedSearchText();f.defaultInsertImageDialog()}},{className:"dropdown-insert-macro",html:f.Autocompleter.Util.dropdownLink("Insert other media",
"dropdown-prevent-highlight","editor-icon"),callback:function(b){b.replaceWithSelectedSearchText();h.confluence.macrobrowser.macroBrowserToolbarButtonClicked({selectedCategory:"media"})}}]},getDataAndRunCallback:function(c,b,a){f.Autocompleter.Util.getRestData(c,m,n,b,a,"attachment")},update:function(c,b){d.trigger("rte-autocomplete-on-insert",{triggerChar:"!",selectedFile:b});var a=b.restObj,e=l.REST.wikiLink(a),f=a&&a.title||b.name;if(a.thumbnailLink){e.destination&&e.destination.replace(/^\^/,
"");a=j.extend({filename:f,contentId:b.ownerId||a.ownerId},e.params);h.confluence.ImageUtils.insertFromProperties(a)}else{var i=!!d.MacroBrowser.getMacroMetadata("view-file"),g=a.contentType;i&&(!(g&&g==="application/x-shockwave-flash")||g&&(g==="audio/mp3"||g==="video/mp4")||a.niceType!=="Multimedia")?k.insertFilePlaceholder({name:f,page:a.parentTitle,space:a.space?a.space.key:"",date:a.datePath,ownerId:a.ownerId}):this._insertFile(f,b,e)}},_insertFile:function(c,b,a){var e;switch(b.restObj.niceType){case "PDF Document":e=
"viewpdf";break;case "Word Document":e="viewdoc";break;case "Excel Spreadsheet":e="viewxls";break;case "PowerPoint Presentation":e="viewppt";break;case "Multimedia":e="multimedia"}c={page:a.destination.substring(0,a.destination.indexOf("^")),name:c};i.get("viewdoc").beforeParamsRetrieved(c);c.page||delete c.page;e={contentId:d.Meta.get("content-id")||"0",macro:{name:e,params:c,body:""}};h.confluence.MacroUtils.insertMacro(e)}}}});require("confluence/module-exporter").safeRequire("confluence-editor/tinymce3/plugins/autocomplete-media/autocomplete-settings-media");
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.editor:editor-resources-conf-frontend', location = 'tinymce3/plugins/autocomplete-media/editor_plugin_src.js' */
define("confluence-editor/tinymce3/plugins/autocomplete-media/editor_plugin_src",["tinymce","confluence/legacy-editor-global-AVOID-IF-POSSIBLE","confluence-editor/tinymce3/plugins/autocomplete-media/autocomplete-settings-media"],function(a,b,c){return{init:function(a){a.addCommand("mceConfAutocompleteImage",function(){b.Autocompleter.Manager.shortcutFired("!")});a.addShortcut("ctrl+shift+m",a.getLang("AutoComplete"),"mceConfAutocompleteImage");c()},getInfo:function(){return{longname:"Auto Complete Media",
author:"Atlassian",authorurl:"http://www.atlassian.com",version:a.majorVersion+"."+a.minorVersion}}}});require("confluence/module-exporter").safeRequire("confluence-editor/tinymce3/plugins/autocomplete-media/editor_plugin_src",function(a){var b=require("tinymce");b.create("tinymce.plugins.AutoCompleteMedia",a);b.PluginManager.add("autocompletemedia",b.plugins.AutoCompleteMedia)});
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.editor:editor-resources-conf-frontend', location = 'tinymce3/plugins/autocomplete-media/autocomplete-analytics-media.js' */
require(["ajs"],function(a){a.bind("init.rte",function(){a.bind("rte-autocomplete-on-show",function(d,c){"!"===c.triggerChar&&a.trigger("analytics",{name:"confluence.editor.autocomplete.trigger",data:{type:"media"}})});a.bind("rte-autocomplete-on-insert",function(d,c){if("!"===c.triggerChar){var b=c.selectedFile;b&&b.name&&(b={extension:b.name.split(".").pop(),type:"media"},a.trigger("analytics",{name:"confluence.editor.autocomplete.insert",data:b}))}})});a.bind("rte-destroyed",function(){a.unbind("rte-autocomplete-on-insert");
a.unbind("rte-autocomplete-on-show")})});
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.editor:editor-resources-conf-frontend', location = 'tinymce3/plugins/confluencepaste/linkify.js' */
define("confluence-editor/tinymce3/plugins/confluencepaste/linkify",function(){return{RE_EMAIL_PATTERN:"(?:\\s|\\A|^)[\\w.-]+\\+*[\\w.-]+@(?:(?:[\\w-]+\\.)+[A-Za-z]{2,6}|(?:\\d{1,3}\\.){3}\\d{1,3})",RE_URL_SCHEME:"(?:[\\w-]{2,}):/{1,3}",RE_TLD:"(?:aero|arpa|biz|com|coop|edu|gov|info|int|mil|museum|name|net|org|travel|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cu|cv|cx|cy|cz|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|fi|fj|fk|fm|fo|fr|ga|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|qa|re|ro|ru|rw|sa|sb|sc|sd|se|sg|si|sj|sk|sl|sm|sn|so|sr|st|sv|sy|sz|tc|td|tf|tg|th|tj|tk|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|um|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw)",
RE_URL_MIDCHAR:"(?:[^\\s()]+|\\((\\S+)\\))",RE_URL_ENDCHAR:"(?:\\((\\S+)\\)|[^\\s`!()\\[\\]{};:'\".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019])",init:function(){this.RE_URL_ENDING||(this.RE_URL_ENDING="(?:"+this.RE_URL_MIDCHAR+"*"+this.RE_URL_ENDCHAR+")?",this.RE_FULL_URL=this.RE_URL_SCHEME+"\\w+(?:.\\w+)"+this.RE_URL_ENDING,this.RE_OTHER_URL="\\w[\\w_-]*(?:\\.\\w[\\w_-]*)*\\."+this.RE_TLD+"(?:[\\/\\?#]"+this.RE_URL_ENDING+"|\\b)")},linkify:function(f,b,i){this.init();f=this.match_and_replace(this.RE_EMAIL_PATTERN,
f,!0,!1,b,i);f=this.match_and_replace(this.RE_FULL_URL,f,!1,!1,b,i);return f=this.match_and_replace(this.RE_OTHER_URL,f,!1,!0,b,i)},match_and_replace:function(f,b,i,o,k,h){for(var c=0,a=0,d=0,c=0,l=/<\/[aA]>/,f=RegExp(f,"g"),p=h.hasOwnProperty("add_wbrs")?h.add_wbrs:null,j=h.hasOwnProperty("truncate_length")?h.truncate_length:100,m=h.hasOwnProperty("link_target")?h.link_target:"_blank",h=h.hasOwnProperty("link_titles")?h.link_titles:null,d={},n=0;d=f.exec(b);){n++;if(20<n)break;c=d.index;d=d[0].length;
if(0<=b.substring(a,c).search(/<[aA]/)){l.lastIndex=a;c=b.substring(a,b.length).search(l);if(0>c)break;c+=a;f.lastIndex=c+4;a=c+4}else{var a=b.substr(c,d),g=a.search(/&(amp|gt|lt)$/);if(0<g&&b.length>c+d&&";"==b[c+d]){d-=a.length-g;for(a=b.substr(c,d);!a.match(this.RE_URL_ENDCHAR+"$")&&0<d;)d--,a=b.substr(c,d)}g=a;o&&(g="http://"+g);var e="<a";m&&(e+=' target="'+m+'"');e+=' href="';i&&(e+="mailto:");g=g.replace(/"/g,"%22");e+=g+'"';h&&(e+=' title="'+(i?"Email "+g:g)+'"');j&&a.length>j&&(a=a.substr(0,
j)+"...");p&&(a=a.replace(RegExp("([/=])","g"),"<wbr>$1"));e+=">"+a+"</a>";k&&k.push(g);b=b.slice(0,c)+e+b.slice(c+d,b.length);f.lastIndex=c+e.length;a=c+e.length}}return b}}});require("confluence/module-exporter").exportModuleAsGlobal("confluence-editor/tinymce3/plugins/confluencepaste/linkify","linkify");
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.editor:editor-resources-conf-frontend', location = 'tinymce3/plugins/confluencepaste/post-paste-node-filter.js' */
define("confluence-editor/tinymce3/plugins/confluencepaste/post-paste-node-filter",["jquery","confluence-editor/tinymce3/plugins/confluencepaste/linkify","ajs","document","tinymce"],function(c,q,r,y,z){function u(a,b){for(var f=c(a).find("["+b+"]"),d="",e="",g="",h=0,k=f.length;h<k;h++)e=(d=c(f[h]))&&["/",d.attr(b)].join(""),g=d&&["/",d.attr("data-mce-"+b)].join(""),r.contextPath()&&0===e.indexOf(r.contextPath())&&(f[h]=d.attr(b,e)),r.contextPath()&&0===g.indexOf(r.contextPath())&&(f[h]=d.attr("data-mce-"+
b,g));return f}function m(a,b,f){var a=c(a).find("["+b+"]"),d="",e,g;if(a)for(var h=0,k=a.length;h<k;h++){e=c(a[h]);g=f.standard;for(var n in f)if(f.hasOwnProperty(n)&&e.is(n)){g=f[n];break}if(-1<b.indexOf("style")){var d=e,i=g;g=[];for(var o="",o=void 0,p=d.attr("style"),l=d.attr("data-mce-style"),j=0,m=i.length;j<m;j++)p&&-1<p.toLowerCase().indexOf(i[j])?g.push(i[j]+": "+d.css(i[j])+";"):l&&-1<l.toLowerCase().indexOf(i[j])&&(o=RegExp(i[j]+":.+?(?:;|$)"),o=l.match(o),g.push(-1<o[0].indexOf(";")?
o:o+";"));d=g.join(" ")}else{d=e;i=b;p=[];if(g){l=0;for(j=g.length;l<j;l++)d.is("["+i+"~="+g[l]+"]")&&p.push(g[l])}d=p.join(" ")}e.removeAttr(b);d.length&&e.attr(b,d)}}function A(a,b){function f(f){var e;d.index&&(e=a.splitText(d.index),a&&b.push(a),a=e);(e=a.splitText(d[0].length))&&b.push(e);c(a).wrap("<a href='"+f+a.data+"'></a>")}var d,e,g;e=s.exec(a.data);g=t.exec(a.data);e?(d=e,f("mailto:")):g&&(e=(d=g)&&-1===d[0].indexOf("://")?"http://":"",f(e))}var t;q.init();var v=RegExp(q.RE_FULL_URL),
w=RegExp(q.RE_OTHER_URL);t={exec:function(a){var b=v.exec(a);return b?b:w.exec(a)},test:function(a){return v.test(a)||w.test(a)}};var s,x=RegExp(q.RE_EMAIL_PATTERN);s={exec:function(a){if((a=x.exec(a))&&/\s/.test(a[0][0]))a[0]=a[0].replace(/\s/,""),a.index++;return a},test:function(a){return x.test(a)}};c(y).bind("postPaste",function(a,b,f){a=f.node;b={standard:["text-decoration","text-align","margin-left"],".wysiwyg-macro":["background-image"],p:["margin-left","text-align"],span:["color","text-decoration"],
pre:["margin-left"]};b.td=b.th=["text-align"];b.li=["list-style-type","background-image"];b.col=["width"];b["table.confluenceTable.relative-table"]=["width"];m(a,"style",b);m(a,"data-mce-style",b);c.browser.mozilla&&(u(a,"src"),u(a,"href"));m(a,"face",{standard:[]});m(a,"id",{standard:[]});m(a,"data-mce-href",{standard:[]});a=f.node;b=[];b.push({elements:["div"],attribute:"class",blackValue:"aui-buttons"});for(var d=0;d<b.length;d++)for(var e=b[d],g=0;g<e.elements.length;g++)for(var h=c(a).find(e.elements[g]+
"["+e.attribute+"]"),k=0;k<h.length;k++){var n=h.eq(k).attr(e.attribute),n=n.replace(e.blackValue,"");h.eq(k).attr(e.attribute,n)}var i=f.node;c.each(".contentLayout .contentLayout2 .columnLayout .header .footer .cell .innerCell .panelContent .panel .panelHeader .Apple-converted-space font .jira-status .jira-issue .diff-html-removed .diff-html-added .diff-html-changed".split(" "),function(a,b){c(b,i).contents().unwrap()});c("img",i).map(function(){c(this).attr("data-attachment-copy","");!c(this).attr("src")&&
c(this).remove()});c("dl",i).map(function(){c(this).replaceWith(c("<p/>").text(c(this).text()))});c("a",i).map(function(){c(this).removeClass("confluence-userlink userLogoLink")});if(!c.browser.msie)for(a=c.makeArray(f.node.childNodes);a.length;)b=a.pop(),c(b).is("a")||(3===b.nodeType?A(b,a):1===b.nodeType&&(b.childNodes&&"pre"!==b.nodeName.toLowerCase())&&(a=a.concat(c.makeArray(b.childNodes))));if(a=c.browser.mozilla)a=c(f.node),a=a.children("br").length&&!a.find(":not(br)").length&&!c(z.activeEditor.selection.getStart()).closest("[data-macro-body-type='PLAIN_TEXT']").length;
a&&(f=c(f.node),a="<p>"+f.html().replace(/<br>/gi,"</p><p>")+"</p>",f.html(a))});return{URL:t,EMAIL:s}});require("confluence/module-exporter").exportModuleAsGlobal("confluence-editor/tinymce3/plugins/confluencepaste/post-paste-node-filter","Confluence.Editor.regex");
}catch(e){WRMCB(e)};