WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'com.atlassian.confluence.extra.team-calendars:calendars-in-space', location = 'com/atlassian/confluence/extra/calendar3/components/calendars-in-space/calendar-navigation-buttons-view.js' */
define("tc/subcalendar-navigation-buttons-view",["jquery","underscore","tc/calendar-util","tc/util","tc/calendar-add-inline-dialog","tc-backbone"],function(d,a,b,f,c,g){var e=g.View.extend({events:{"click .edit-calendar-button, #editCalendarLink":"_onEditButtonClick","click .add-calendar-button":"_onAddButtonClick"},initialize:function(h){this.calendarDiv=h.calendarDiv;this.CalendarPlugin=h.CalendarPlugin;AJS.bind("calendar.loaded",a.bind(this._onCalendarLoaded,this));AJS.bind("calendar.removed",a.bind(this._onCalendarRemoved,this));AJS.bind("calendar.watch.statuses.loaded",a.bind(this._onWatchStatusLoaded,this));this.inlineAddCalendarDialog=new c({callbackHandler:this.CalendarPlugin.getRenderedMacroCallbackHandler(this.calendarDiv)})},render:function(){this._initShareButton();if(b.isSpaceCalendarView(this.calendarDiv)){var i=!d(".no-calendar-page").is(":visible");this.$(".add-calendar-button").toggleClass("hidden",!i);this.$(".add-calendar-button-more").toggleClass("hidden",!i)}else{if(b.isSingleCalendarView(this.calendarDiv)){if(this.subCalendar){var h=this.CalendarPlugin.getParameter(this.calendarDiv,"readOnly")!=="true"&&this.subCalendar.editable&&this.subCalendar.eventsEditable;this.$(".edit-calendar-button").toggleClass("hidden",!h)}}}this.inlineAddCalendarDialog.render()},_initShareButton:function(){var i=!d(".no-calendar-page").is(":visible");var j=b.getParameter(this.calendarDiv,"enableShareCalendar");var k=true;if(this.subCalendar){k=this.subCalendar.eventsViewable}this.$(".share-calendar-button").toggleClass("hidden",!i||!j||!k);if(AJS.Confluence.SharePage&&!this.shareDialogLoaded){AJS.Confluence.SharePage.initDialog(d(".share-calendar-button"),"shareContentPopup",{offsetX:-110});this.shareDialogLoaded=true;var h="spaceCalendars";if(b.isSingleCalendarView(this.calendarDiv)){h="singleCalendar"}d(".share-calendar-button").click(function(l){Confluence.TeamCalendars.fireEventForAnalytics("share.calendar.click."+h)})}},_onEditButtonClick:function(h){this.CalendarPlugin.showSubCalendarEdit(this.calendarDiv,this.subCalendar);d("#edit-calendar-dialog").find(".button-panel-button.submit").removeClass("hidden");h.preventDefault();return false},_onCalendarLoaded:function(i,h){if(b.isSingleCalendarView(this.calendarDiv)){this.subCalendar=h}var j=this.CalendarPlugin.getParameter(this.calendarDiv,"contentId");AJS.params.pageId=j?j:AJS.params.pageId;this.render()},_onCalendarRemoved:function(){this.render()},_onWatchStatusLoaded:function(i,h){},_onAddButtonClick:function(i){Confluence.TeamCalendars.fireEventForAnalytics("add.calendar.click.new."+Confluence.TeamCalendars.getCalendarContext());var h=Confluence.TeamCalendars.Dialogs.getSubCalendarCreateDialog("parent",this.CalendarPlugin.getRenderedMacroCallbackHandler(this.calendarDiv));f.showDialogInUpdatedHeight(h);d("input[name='name']",h.getCurrentPanel().body).focus();d("#inline-dialog-inline-dialog-more").hide();i.preventDefault();return false}});return e});
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.extra.team-calendars:calendars-in-space', location = 'com/atlassian/confluence/extra/calendar3/components/calendars-in-space/calendar-restriction-button-view.js' */
define("tc/subcalendar-restriction-button-view",["jquery","underscore","tc/calendar-util"],function(d,a,b){var c=Backbone.View.extend({events:{"click .restrict-calendar-button":"_onRestrictionClick"},initialize:function(e){this.calendarDiv=e.calendarDiv;this.CalendarPlugin=e.CalendarPlugin;AJS.bind("calendar.loaded",a.bind(this._onCalendarLoaded,this))},render:function(){var e=b.hasRestriction(this.subCalendar);this.$(".restrict-calendar-button.restricted").toggleClass("hidden",!e);this.$(".restrict-calendar-button.no-restricted").toggleClass("hidden",e)},_onRestrictionClick:function(){if(this.CalendarPlugin.getParameter(this.calendarDiv,"readOnly")!=="true"&&this.subCalendar.administrable&&!b.isJiraSubCalendar(this.subCalendar)){this.CalendarPlugin.getSubCalendarRestrictionsDialog(this.calendarDiv,this.subCalendar)}event.preventDefault()},_onCalendarLoaded:function(f,e){if(b.isSingleCalendarView(this.calendarDiv)){this.subCalendar=e;this.render()}}});return c});
}catch(e){WRMCB(e)};