WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'com.atlassian.confluence.plugins.quickedit:quick-edit-general', location = 'jscripts/quick-edit.js' */
define("confluence-quick-edit/quick-edit","ajs confluence/templates confluence/meta jquery window document confluence-quick-edit/util confluence-quick-edit/captcha-manager confluence/legacy-editor-global-AVOID-IF-POSSIBLE wrm confluence/dark-features".split(" "),function(c,n,o,b,r,s,t,h,e,u){function v(){var a=new b.Deferred;c.Confluence.EditorLoader.load(function(){setTimeout(function(){a.resolve()},0)},function(){a.reject()},{editPermission:!!b("#editPageLink").length});return a}var p={enableShortcut:function(){b("#editPageLink").addClass("full-load")},
disableShortcut:function(){b("#editPageLink").removeClass("full-load")}},i=[],m={loadingContentTimeout:4E3,register:function(a){i.push(a)},disableHandlers:function(){b.each(i,function(a,b){return b.disable()})},enableHandlers:function(){b.each(i,function(a,b){return b.enable()})},SaveBarBinder:{bind:function(a,b){a&&e.addSaveHandler(a);b&&e.addCancelHandler(b)}},activateEditor:function(a){function e(){function f(a){var c=new b.Deferred;u.require(a).done(function(a){c.resolve(a)}).fail(function(a){c.reject(a)});
return c}var i,k=new b.Deferred;if(c.Rte&&c.Rte.getEditor()){c.debug("there is already an editor open");return k.reject("there is already an editor open")}if(!a.$container||!a.$form){c.logError("activateEditor could not be initialsed: bad arguments",a);return k.reject("bad parameters")}if(a.$container.nodeType)a.$container=b(a.$container);if(a.$form.nodeType)a.$form=b(a.$form);i=c.Confluence.BlockAndBuffer.block(b(s));a.preActivate&&a.preActivate();p.disableShortcut();var q=a.timeoutResources||c.Confluence.EditorLoader.loadingTimeout,
h=m.loadingContentTimeout,j=t.timeoutDeferred;b.when(j("resources",v(),q),j("fetch content",a.fetchContent||b.Deferred().resolve(),h),j("additional resources",a.additionalResources?f(a.additionalResources):b.Deferred().resolve(),q)).done(function(e,f){var d={$container:a.$container,content:f,$form:a.$form,replayBufferedKeys:i};a.preInitialise&&a.preInitialise(d);b(".quick-comment-prompt",d.$container).hide();b(".quick-comment-body",d.$container).addClass("comment-body");var g=b(c.Confluence.EditorLoader.getPreloadContainer());
if(d.content&&d.content.title){var l=d.content.title;g.find("#content-title").val(l)}d.$form.append(g.children());g.show();b("#editor-precursor").hide();b("#rte-savebar").find(".toolbar-split-left").hide();if(o.get("content-type")==="comment"){b("#pluggable-status").hide();var g=n.Editor.Page.cancelButton({contentType:o.get("content-type")}),l=b("#rte-button-cancel"),h=l.parent(".rte-toolbar-group-done");if(h.length){h.remove();b("#rte-button-discard").remove()}else{l.parent(".aui-buttons").remove();
l.remove()}b("#rte-savebar").find(".toolbar-split-right").append(g);g=n.Editor.Page.previewButton({});b("#rte-button-ellipsis").remove();b("#rte-savebar").find(".toolbar-group-preview").append(g)}var j=function(){d.editor=c.Rte.getEditor();if(d&&d.$container&&d.$container.nodeType)d.$container=b(d.$container);if(d&&d.$container&&d.$form.nodeType)d.$form=b(d.$form);d.$container.find(".quick-comment-loading-container").hide();d.$form.show();d.$form.addClass("fadeIn");var e=d.editor,f=d.content?d.content.editorContent:
"",g=d.replayBufferedKeys;if(f){e.setContent(f);e.startContent=e.getContent({format:"raw",no_events:1});e.undoManager.clear()}g()&&e.undoManager.add();c.trigger("quickedit.success");c.trigger("quickedit.visible");c.trigger("add-bindings.keyboardshortcuts");c.trigger("active.dynamic.rte");b("div.aui-message.closeable").each(function(){var a=b(this),d;if(!a.find(".icon-close").length){d=b('<span class="aui-icon icon-close" role="button" tabindex="0"></span>').click(function(){a.closeMessage()}).keypress(function(b){if(b.which===
c.keyCode.ENTER||b.which===c.keyCode.SPACE){a.closeMessage();b.preventDefault()}});a.append(d)}});a.postInitialise&&a.postInitialise(d);m.SaveBarBinder.bind(a.saveHandler,a.cancelHandler);c.trigger("rte-quick-edit-ready");c.unbind("rte-ready",j);k.resolve()};c.bind("rte-ready",j);c.bind("rte-destroyed",a.postDeactivate||function(){});c.Rte.BootstrapManager.initialise({plugins:a.plugins,toolbar:a.toolbar,excludePlugins:a.excludePlugins,isQuickEdit:true,onInitialise:a.onInitialise})}).fail(function(b,
e){k.reject(b,e);c.logError("Error loading page quick edit. Falling back to normal edit URL...");c.trigger("analytics",{name:"rte.quick-edit.activate-editor.failed"});if(a.fallbackUrl){c.log("This parameter is deprecated. To be removed in the next major version (5.8 or 6.0). Please use the promise returned to bind custom action if the editor fails to load instead.");r.location=a.fallbackUrl}});return k.promise()}if(a.closeAnyExistingEditor&&c.Rte&&c.Rte.getEditor()){var f=new b.Deferred;this.deactivateEditor().done(function(){e().done(function(){f.resolve()}).fail(function(a){f.reject(a)})}).fail(function(){c.debug("Could not deactivate current editor.");
f.reject("Could not deactivate current editor.")});return f}return e()},deactivateEditor:function(){require("tinymce").majorVersion>=4?require("tinymce").execCommand("mceRemoveEditor",true,"wysiwygTextarea"):require("tinymce").execCommand("mceRemoveControl",true,"wysiwygTextarea");e.UI.toggleSavebarBusy(false);var a=c.Confluence.EditorLoader.getPreloadContainer().empty();b(".editor-container").remove();b("#editor-precursor").remove();b("#anonymous-warning").remove();b(".quick-comment-prompt").show();
b(".bottom-comment-panels").show();b("#editor-notification-container").empty();b(".action-reply-comment").removeAttr("reply-disabled");p.enableShortcut();e.removeAllSaveHandlers();e.removeAllCancelHandlers();return c.Confluence.EditorLoader.getEditorPreloadMarkup().done(function(b){a.append(b);a.hide();(new h(a)).refreshCaptcha();c.trigger("rte-destroyed");c.unbind("rte-destroyed")})}};return m});require("confluence/module-exporter").exportModuleAsGlobal("confluence-quick-edit/quick-edit","AJS.Confluence.QuickEdit");
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.plugins.quickedit:quick-edit-general', location = 'jscripts/handlers/view.js' */
define("confluence-quick-edit/handlers/view",["jquery","ajs","window"],function(c,d,e){return function(){var a;sessionStorage.viewPort&&(a=JSON.parse(sessionStorage.viewPort));if(a&&a.pageId==d.params.pageId){var b;b=c("#main-content");var f=c("#header");b=-1!==a.blockIndex?b.children().first().children().eq(a.blockIndex).find(".innerCell").eq(a.columnIndex).children().eq(a.index):b.children().eq(a.index);e.scrollTo(0,b.offset().top+a.offset-f.outerHeight())}delete sessionStorage.viewPort}});
require("confluence/module-exporter").safeRequire("confluence-quick-edit/handlers/view",function(c){require("ajs").toInit(c)});
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.plugins.quickedit:quick-edit-general', location = 'jscripts/handlers/shortcut.js' */
define("confluence-quick-edit/handlers/shortcut",["ajs"],function(a){var d=!1;a.bind("initialize.keyboardshortcuts add-bindings.keyboardshortcuts",function(){d=!0});a.bind("remove-bindings.keyboardshortcuts",function(){d=!1});return{createShortcut:function(f,g){function b(){c=c||a.whenIType(f).moveToAndClick(g)}function e(){c&&c.unbind();c=null}var c;return{bind:function(){d&&b();a.bind("initialize.keyboardshortcuts",b);a.bind("add-bindings.keyboardshortcuts",b);a.bind("remove-bindings.keyboardshortcuts",
e)},unbind:function(){e();a.unbind("initialize.keyboardshortcuts",b);a.unbind("add-bindings.keyboardshortcuts",b);a.unbind("remove-bindings.keyboardshortcuts",e)}}}}});require("confluence/module-exporter").exportModuleAsGlobal("confluence-quick-edit/handlers/shortcut","AJS.Confluence.QuickEdit.KeyboardShortcuts");
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.plugins.quickedit:quick-edit-general', location = 'jscripts/handlers/page.js' */
define("confluence-quick-edit/handlers/page","jquery ajs underscore confluence/meta confluence-quick-edit/handlers/shortcut confluence/aui-overrides confluence/analytics-support confluence-editor/profiles window confluence/performance-session confluence-quick-edit/quick-edit confluence/legacy-editor-global-AVOID-IF-POSSIBLE confluence/get-content-id confluence/api/browser confluence-editor/editor/page-editor-message".split(" "),function(b,d,C,i,v,w,n,x,k,l,o,D,p,y,z){function q(a,c,g){var f={pageId:g,
blockIndex:-1,columnIndex:-1,index:-1,offset:0,hasBlock:function(){return this.blockIndex!==-1}},d=false,e=function(a,b){var g=a.offset();if(i(a)){f.index=b;f.offset=c-g.top;d=true}},i=function(a){var b=a.offset();return b.top-8<=c&&b.top+a.height()>=c};if(a.children().length===1&&a.children().first().hasClass("contentLayout2")){a.children().first().children().each(function(a){if(!f.hasBlock()&&i(b(this)))f.blockIndex=a});if(f.hasBlock()){a=a.children().first().children().eq(f.blockIndex).find(".innerCell");
a.each(function(a){if(f.columnIndex===-1){var c=b(this).children().length;if(c>0)if(c<2){if(b(this).children().first().height()>25)f.columnIndex=a}else f.columnIndex=a}});a.eq(f.columnIndex).children().each(function(a){d||e(b(this),a)})}}else a.children().each(function(a){d||e(b(this),a)});return d?f:null}function r(a){var c=require("tinymce");h.disable();w.metaToParams();if(a.$container.nodeType)a.$container=b(a.$container);if(a.$form.nodeType)a.$form=b(a.$form);if(d.DarkFeatures.isEnabled("confluence.view.edit.transition")){var g=
b("#main-content"),f=b("#header"),e=b("#main-header"),f=k.pageYOffset+f.outerHeight()+e.outerHeight();j=q(g,f,d.params.pageId);d.trigger("quick-edit.viewport.saved");var l=function(){b(c.activeEditor.getWin().document).find("body#tinymce").addClass("page-edit");b("#content").css({paddingRight:0});d.unbind("quickedit.visible",l)};d.bind("quickedit.visible",l)}g=a.$form;e=d.contextPath()+"/pages/";if(i.get("page-version")===0){f=i.get("content-type")==="page"?"docreatepage":"docreateblogpost";e=e+(f+
".action")}else{f=i.get("content-type")==="page"?"doeditpage":"doeditblogpost";e=e+(f+".action?pageId="+p())}b(".ia-splitter-left").remove();try{b("#confluence-ui").length?b("#main").detach().appendTo("#full-height-container"):b("#main").unwrap()}catch(m){}b("#rte").removeClass("editor-default").addClass("editor-fullheight");a.$container.children().remove();b(".editor-container").children().eq(0).unwrap();g.attr({"class":"editor aui",action:e,name:"editpageform",id:"editpageform",style:""});a.$container.append(g);
a.$container.removeClass("view").addClass("edit");b("body").addClass("contenteditor edit");i.set("use-inline-tasks","true")}function s(a){require("tinymce");b("#editor-precursor").show();b("#rte-savebar").find(".toolbar-split-left").show();if(k.history.pushState){var c=e.attr("href");if(c!=k.location.pathname+k.location.search){history.pushState({quickEdit:true},"",c);d.trigger("rte-quick-edit-push-state",c)}}else{k.location.hash="editor";d.trigger("rte-quick-edit-push-hash")}c=a.content;if(c.permissions)for(var g in c.permissions)b("#"+
g).attr("value",c.permissions[g]);b("#originalVersion").val(a.content.pageVersion);i.set("page-version",a.content.pageVersion);i.set("page-title",a.content.title);b('meta[name="page-version"]').attr("content",a.content.pageVersion);b('meta[name="ajs-page-version"]').attr("content",a.content.pageVersion);b("#syncRev").val(a.content.syncRev);i.set("conf-revision",a.content.confRev);b('meta[name="ajs-conf-revision"]').attr("content",a.content.confRev);g=a.content.atlToken;i.set("atl-token",g);b('input[name="atl_token"]').val(g);
d.trigger("analyticsEvent",{name:"quick-edit-success"});b("#navigation").remove();var f=new Date,h=function(b,c){if(f&&!(c.type==="keydown"&&[91,92,93,224,33,34,37,38,39,40,16,17,18,20,112,113,114,115,116,117,118,119,120,121,122,123].indexOf(c.keyCode)>-1)){var d=new Date-f;f=null;n.publish("confluence.editor.transition.firstkeydown",{delay:d});a.editor.onKeyDown.remove(h);a.editor.onChange.remove(h)}};a.editor.onKeyDown.add(h);a.editor.onChange.add(h);l.debugTimeEnd("confluence.editor")}function A(a){setTimeout(function(){if(j){var c;
c=b(a.getBody());c=j.hasBlock()?c.children().first().children().eq(j.blockIndex).find(".innerCell").eq(j.columnIndex).children().eq(j.index):c.children().eq(j.index);a.getWin().scrollTo(0,c.offset().top+j.offset);b("#main").css("visibility","visible")}})}function B(){var a=new b.Deferred;l.debugTime("confluence.editor.quick.fetchContent");var c=b.ajax({url:d.contextPath()+"/rest/tinymce/1/content/"+p()+".json",cache:false});c.success(function(b){l.debugTimeEnd("confluence.editor.quick.fetchContent");
d.trigger("rte-initial-raw-content-ready",b);a.resolve(b)});c.error(function(b){a.reject("error fetching content",b)});return a}function t(a,b){if(b)switch(b.status){case 412:if(e){e.find(".aui-icon").css("visibility","visible");e.parent().spinStop()}z.handleMessage("collab.edit.user.limit.reached",{type:"warning",title:"You can\'t edit this page right now",message:"\u003cp\u003eThis page is so popular, you\'ve reached the maximum number of simultaneous editors.\u003c/p\u003e\u003cp\u003eTry again when it\'s not so busy.\u003c/p\u003e",close:"manual"});n.publish("collab.edit.user.limit.reached",{browser:u.friendlyName()+
"-"+u.version(),pageId:i.get("page-id"),editMode:"quick"});return}k.location=e.attr("href")}var m,j,e,u=new y(k.navigator.userAgent),h={editShortcut:v.createShortcut("e","#editPageLink"),activateEventHandler:function(a){if(!a.metaKey&&!a.shiftKey&&!a.ctrlKey&&!a.altKey&&!(a.which===2||a.which===3)){a.preventDefault();if(m&&m.state()==="pending")d.debug("Editor is being activated. Ignoring handler...");else{m=h.activateEditor();if(e){e.find(".aui-icon").css("visibility","hidden");e.parent().spin({left:"10px"})}}}},
enable:function(){if(b("#confluence-ui").length)return false;e=b("#editPageLink");if(b("body").is(".theme-default")){e.on("click",h.activateEventHandler);e.removeClass("full-load");h.editShortcut.bind();d.debug("QuickPageEdit enabled")}else d.debug("QuickPageEdit not enabled")},activateEditor:function(){l.debugTime("confluence.editor");d.trigger("rte-quick-edit-init");var a=b("#content").find(".quick-comment-form"),c=function(){var a=require("tinymce").activeEditor.getWin(),c=b(a.document).find("#tinymce");
if(a=q(c,a.pageYOffset,d.params.pageId))sessionStorage.viewPort=JSON.stringify(a)};return o.activateEditor({fetchContent:B(),$container:b("#content"),$form:a.length?a:b('<form method="post"></form>'),preInitialise:r,postInitialise:s,saveHandler:function(){d.DarkFeatures.isEnabled("confluence.view.edit.transition")&&c()},cancelHandler:function(){d.DarkFeatures.isEnabled("confluence.view.edit.transition")&&c()},plugins:x.createProfileForPageEditor({versionComment:true,notifyWatchers:true}).plugins,
onInitialise:function(a){d.DarkFeatures.isEnabled("confluence.view.edit.transition")&&a.onLoad.add(A)}}).fail(t)},disable:function(){d.debug("QuickPageEdit disabled.");h.editShortcut.unbind();e&&e.unbind("click",h.activateEventHandler)}};o.register(h);return{disable:h.disable,activate:h.activateEditor,preInitialise:r,postInitialize:s,_objForTesting:{onFailActivateEditor:t}}});require("confluence/module-exporter").exportModuleAsGlobal("confluence-quick-edit/handlers/page","AJS.Confluence.QuickEdit.QuickEditPage");
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.plugins.quickedit:quick-edit-general', location = 'jscripts/init.js' */
define("confluence-quick-edit/init",["ajs","jquery","window","confluence-quick-edit/quick-edit","confluence-editor-loader/editor-loader"],function(b,a,c,d,e){return function(){a("body").hasClass("page-gadget")?b.debug("QuickComment: editor preload is disabled"):a(c).load(function(){b.debug("QuickComment: instigated background loading of the comment editor.");e.load(null,null,{editPermission:!!a("#editPageLink").length})});d.enableHandlers();b.trigger("rte-quick-edit-enable-handlers")}});
require("confluence/module-exporter").safeRequire("confluence-quick-edit/init",function(b){var a=require("ajs");a.DarkFeatures.isEnabled("disable-quick-edit")?a.log("disable-quick-edit is turned on; run AJS.Confluence.EditorLoader.load() manually."):a.toInit(b)});
}catch(e){WRMCB(e)};