WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'confluence.web.resources:control', location = 'includes/js/control.js' */
define("confluence/control","confluence/class confluence/trigger confluence/api/logger confluence/api/keyboard jquery document".split(" "),function(n,p,h,k,d,e){return n.extend({INVALID:"INVALID",_throwReadOnlyError:function(a){Error(this.CLASS_SIGNATURE+": Sorry ["+a+"] is a read-only property")},_assignEvents:function(a,b){this._unassignEvents(a,b);if("string"===typeof b)for(var c in this._events[a])d(e).delegate(b,c,this._getDispatcher(a,c));else for(c in b=d(b),this._events[a])b.bind(c,this._getDispatcher(a,
c)),h.debug("Control bound eventType '"+c+"' for group '"+a+"' on target '"+(b[0].type||b[0])+"'")},_unassignEvents:function(a,b){if("string"===typeof b)for(var c in this._events[a])d(e).undelegate(b,c,this._getDispatcher(a,c));else{b=d(b);try{for(c in this._events[a])b.unbind(c,this._getDispatcher(a,c))}catch(q){var l=b.data("events");if(l)for(c in l)if(c in this._events[a]){for(var f=this._getDispatcher(a,c),m=l[c],g=0;g<m.length;g++)if(m[g]===f){m.splice(g,1);break}h.debug("Control unbound eventType '"+
c+"' for group '"+a+"' on target '"+(b[0].type||b[0])+"'")}}}},_getDispatcher:function(a,b){var c=a+"/"+b;this._dispatchers||(this._dispatchers={});if(!this._dispatchers[c]){var e=this._events[a][b],f=this;this._dispatchers[c]=function(c){h.debug("Control dispatching eventType '"+b+"' for group '"+a+"' on instance '"+f.type+"'");return e.call(f,c,d(this))}}return this._dispatchers[c]},_isValidInput:function(){return!0},_handleKeyEvent:function(a){if(this._isValidInput(a)){var b=k.SpecialKey,c=k.shortcutEntered(a);
if(c){if(this.keys[c]){this.keys[c].call(this,a);return}if((c===b.BACKSPACE||c===b.DELETE)&&this.keys.onEdit){this.keys.onEdit.call(this,a);return}}(b=k.characterEntered(a))&&this.keys.onEdit&&this.keys.onEdit.call(this,a,b)}},getCustomEventName:function(a){return(this.CLASS_SIGNATURE||"")+"_"+a},_getCustomEventArgs:function(){return[this]},trigger:function(a){return p(a,this)},_supportsBoxShadow:function(){var a=e.body.style;return void 0!==a.WebkitBoxShadow||void 0!==a.MozBoxShadow||void 0!==a.boxShadow},
_setOptions:function(a){var b,c;a=a||{};if(a instanceof d||"string"===typeof a||"object"===typeof a&&a.nodeName)a={element:a};b=d(a.element);c=b.getOptionsFromAttributes();this.options=d.extend(!0,this._getDefaultOptions(a),c,a);if(0===b.length)return this.INVALID},getCaret:function(a){var b=a.selectionStart;if(0<=b)return a.selectionEnd>b?-1:b;if(e.selection&&(b=e.selection.createRange(),0===b.text.length)){var c=b.duplicate();c.moveToElementText(a);c.setEndPoint("EndToStart",b);return c.text.length}return-1},
_render:function(){var a,b=arguments[0],c=[];for(a=1;a<arguments.length;a++)c.push(arguments[a]);return this._renders[b].apply(this,c)}})});require("confluence/module-exporter").exportModuleAsGlobal("confluence/control","AJS.Control");
}catch(e){WRMCB(e)};