(window.webpackJsonp=window.webpackJsonp||[]).push([["content-title~b59ad437"],{"4ahR":function(e,t,n){"use strict";n.d(t,"a",(function(){return i})),n.d(t,"b",(function(){return c}));var a=n("ERkP");const r=()=>{},i=Object(a.createContext)({isLeftSidebarCollapsed:!1,expandLeftSidebar:r,collapseLeftSidebar:r,leftSidebarState:{isFlyoutOpen:!1,isResizing:!1,isLeftSidebarCollapsed:!1,leftSidebarWidth:0,lastLeftSidebarWidth:0},setLeftSidebarState:r}),c=()=>Object(a.useContext)(i)},Dsoe:function(e,t,n){"use strict";n.d(t,"a",(function(){return i}));var a=n("ERkP"),r=n("hpu0");class i extends a.Component{constructor(e){super(e),this.markExperienceStart()}markExperienceStart(){const{id:e,name:t,timeout:n,attributes:a,collect:i,onSuccess:c}=this.props;Object(r.b)().start({attributes:a,name:t,timeout:n,id:e,collect:i,onSuccess:c})}render(){return null}}},HYLC:function(e,t,n){"use strict";n.d(t,"a",(function(){return c}));var a=n("daKX"),r=n("0nUU");const i=Object(a.a)("browser-metrics"),c=e=>{if(!e)return i.error`metricKey is falsy.`,null;const t=r.d[e];return t||(i.error`${e} has not been configured`,null)}},MV18:function(e,t,n){"use strict";n.d(t,"a",(function(){return i}));var a=n("ERkP"),r=n("6z9Z");function i({name:e,attributes:t}){const n=Object(a.useContext)(r.a);return Object(a.useEffect)(()=>n.succeed({name:e,attributes:t}),[e,t,n]),null}},PoOp:function(e,t,n){"use strict";n.d(t,"a",(function(){return s}));var a=n("ERkP"),r=n("+6Tk"),i=n("HYLC"),c=n("keNr"),o=n("hb7u");const s=Object(a.memo)(({metricName:e,usePageLoadStartTime:t=!1,startTime:n})=>{const s=Object(i.a)(e),l=Object(r.a)(c.a);return Object(a.useEffect)(()=>{!l&&s&&s.start({startTime:t?o.a.pageLoadStartTimestamp:n})},[s,l,n,t]),null})},UEVo:function(e,t,n){"use strict";n.d(t,"a",(function(){return o}));var a=n("ERkP"),r=n("+6Tk"),i=n("HYLC"),c=n("keNr");const o=Object(a.memo)(({metricName:e,stopTime:t,customData:n})=>{const o=Object(i.a)(e),s=Object(r.a)(c.a);return Object(a.useEffect)(()=>{!s&&o&&o.stop({customData:n,stopTime:t})},[o,s]),null})},bWlm:function(e,t,n){"use strict";n.d(t,"a",(function(){return c}));var a=n("ERkP"),r=n("+6Tk"),i=n("1N1n");const c=e=>{const t=Object(r.a)(i.a),{contentId:n,registerReloader:c}=Object(a.useContext)(i.b);Object(a.useEffect)(()=>{t&&c(e)},[n,e.reload,e.name,t])}},fNih:function(e,t,n){"use strict";n.r(t);var a=n("zjfJ"),r=n("Czhu"),i=n("ERkP"),c=n.n(i),o=(n("aWzz"),n("gQ5V")),s=n("Dsoe"),l=n("3VMZ"),d=n("FdGg"),u=n("X2PC"),m=n("jF39"),b=n("1N1n"),p=n("adTp"),h=n("7+Q0"),f=n("PoOp"),x=n("0nUU"),E=n("bhtZ"),T=n("H5qd"),g=n.n(T),k=n("j+hl");const O=g.a`query ContentTitleExternalQuery($contentId:ID!$externalToken:String!){sharedContent(contentId:$contentId shareToken:$externalToken){content{id title ...contentAppearancePublishedFragment properties(key:"editor"){nodes{id key value}}}}}${k.b}`;var j=n("KsTJ"),w=n("4ahR"),y=n("a0gl"),C=n("UEVo"),P=n("MV18"),S=n("Ua4J");const v=j.default.div`
  /* please update next/packages/content-title/src/ContentTitlePlaceholder.js if you change anything here */
  display: inline-block;
  box-sizing: border-box;
  min-height: 120px;
  width: 100%;
  max-width: 100%;

  ${({centerTitle:e,leftSidebarWidth:t,allowDynamicTextSizing:n})=>e&&`\n    display: block;\n    margin: 0 auto;\n    word-break: break-word;\n    word-wrap: break-word;\n    ${((e,t)=>t?`\n      /* media screen sizes are taken from @atlaskit/editor-common - WidthProvider breakpoints + 80px padding */\n      @media screen and (max-width: ${1345+e}px) {\n        max-width: 680px;\n      }\n      @media screen and (min-width: ${1346+e}px) and (max-width: ${2225+e}px) {\n        max-width: 760px;\n      }\n      @media screen and (min-width: ${2226+e}px) {\n        max-width: 850px;\n      }\n    `:"\n    /* override media queries to the akEditorDefaultLayoutWidth if allowDynamicTextSizing FF is turned off */\n    max-width: 760px\n  ")(t,n)}\n    `};
`;v.displayName="StyledContentTitle";const N=j.default.h1`
  font-weight: normal;
  font-size: 28px;
  margin: 0;
  color: #333;
  word-break: break-word;
  word-wrap: break-word;
  /* update next/packages/content-title/src/ContentTitlePlaceholder.js when this changes */
  min-height: 35px;
  line-height: 35px;
  padding-top: 5px;
  cursor: pointer;
`;N.displayName="StyledH1";const F=({lookAndFeel:e,banner:t,title:n,children:a,centerTitle:o})=>{var s,d,u;const{featureFlags:m}=Object(y.a)(),{leftSidebarState:b}=Object(w.b)(),p=(null!=(u=b)?u.leftSidebarWidth:u)||20,h=!m["confluence.frontend.fabric.editor.disable.dynamic-text-resizing"],{getQueryParams:f,setQueryParams:E}=Object(i.useContext)(S.a);return c.a.createElement(v,{centerTitle:o,leftSidebarWidth:p,allowDynamicTextSizing:h,style:Object(r.a)({},null!=(d=e)&&null!=(d=d.content)?d.header:d),"data-test-id":"page-content-header","data-testid":"page-content-header"},t||null,c.a.createElement(N,{id:"title-text","data-test-id":"title-text",style:null!=(s=e)?s.headings:s,onClick:()=>(()=>{const e=f();e&&(Object.keys(e).forEach(t=>e[t]=null),E(e))})()},n),a,c.a.createElement(C.a,{metricName:x.a.CONTENT_TITLE}),c.a.createElement(P.a,{name:l.a.VIEW_PAGE_TITLE}))};var L=n("Qn63");n.d(t,"ContentTitle",(function(){return I}));class I extends i.Component{constructor(...e){super(...e),Object(a.a)(this,"_isFabricPage",e=>{var t;return'"v2"'===(null!=(t=e)&&null!=(t=t.properties)&&null!=(t=t.nodes)&&null!=(t=t[0])?t.value:t)}),Object(a.a)(this,"_shouldCenterFabricPage",e=>Object(p.e)(e).appearance===h.b.DEFAULT),Object(a.a)(this,"_isCenteredTitle",e=>!!this._isFabricPage(e)&&this._shouldCenterFabricPage(e))}render(){const{spaceKey:e,banner:t,contentId:n,externalToken:a,children:p}=this.props;return c.a.createElement(i.Fragment,null,c.a.createElement(s.a,{id:n,name:l.a.VIEW_PAGE_TITLE}),c.a.createElement(d.a,{attribution:u.a.CONTENT_EXPERIENCE},c.a.createElement(f.a,{metricName:x.a.CONTENT_TITLE,usePageLoadStartTime:!0}),c.a.createElement(o.b,{query:a?O:E.a,variables:{contentId:n,spaceKey:e,externalToken:a,isThemed:!0},context:{single:!0,allowOnExternalPage:!0},fetchPolicy:"cache-and-network"},({error:e,data:n,refetch:o})=>{var s,l;const d=a?null!=(l=n)&&null!=(l=l.sharedContent)?l.content:l:null!=(s=n)&&null!=(s=s.content)&&null!=(s=s.nodes)?s[0]:s;if(!d)return c.a.createElement(L.a,null);if(e)throw e;const u=(({space:e})=>{if(!e)return null;const{lookAndFeel:t}=e;return Object(r.a)(Object(r.a)({},t),{},{headings:t.headings.reduce((e,t)=>(e[t.key]=t.value,e),{})})})(d),h=d.title||"",f=this._isCenteredTitle(d);return c.a.createElement(i.Fragment,null,c.a.createElement(F,{title:h,lookAndFeel:u,banner:t,centerTitle:f},p),c.a.createElement(m.a,{name:"title",types:[b.e.content],reload:o}))})))}}Object(a.a)(I,"defaultProps",{children:null})},jF39:function(e,t,n){"use strict";n.d(t,"a",(function(){return r}));var a=n("bWlm");const r=e=>(Object(a.a)(e),null)},keNr:function(e,t,n){"use strict";n.d(t,"a",(function(){return a}));const a="confluence.frontend.bm.disable-non-page-load-metrics"}}]);
//# sourceMappingURL=content-title~b59ad437.LChdJABJqe.js.map