WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'com.atlassian.confluence.plugins.drag-and-drop:drag-and-drop-for-editor-conf-frontend', location = 'js/editor.js' */
define("confluence-drag-and-drop/editor","ajs jquery conf/confluence-drag-and-drop/analytics/files-upload-analytics conf/confluence-drag-and-drop/drag-and-drop-overlay document confluence-drag-and-drop/files-uploader-factory plupload underscore".split(" "),function(b,f,u,v,n,w,l,h){function x(){if(!q){var c=new b.Dialog(450,180);c.addHeader("Not Supported");c.addSubmit("Ok",function(){c.remove()});c.addPanel("Panel 1",
"panel1");c.getCurrentPanel().html("\u003cp\u003eAttachments are not supported in Templates.\u003c/p\u003e \u003cp\u003eFiles may be attached to a Page, and added as an image via the Insert menu.\u003c/p\u003e");c.show();q=!0}}var c,m=w.get(),r=function(b,a,f){if(!a)return!1;if(a.generalError)return h.each(a.generalError.fileIds,function(d){c.renderError(d,a.generalError.message);(d=b.getFile(d))&&b.removeFile(d)}),!0;if(a.fileErrors)return h.each(a.fileErrors,function(d){c.renderError(d.id,d.message);(d=b.getFile(d.id))&&b.removeFile(d)}),a.fileErrors.length===f.length},t=function(f){f.total.queued||(f.stop(),c.showCloseButton(),
c.hasErrors()||setTimeout(function(){c.hide();c.clearRenderOutput();b.Rte.BookmarkManager.restoreBookmark()},1E3))},y=function(p){var a=n.getElementById("fileuploadShim"),k=!1;a||(a=n.createElement("div"),a.setAttribute("id","fileuploadShim"),n.body.appendChild(a));var d=new l.Uploader({runtimes:"html5",dragdrop:!0,drop_element:p,browse_button:a.getAttribute("id"),multipart:!1,max_file_size:+b.Meta.get("global-settings-attachment-max-size")});c||(c=new b.DragAndDropProgressDialog);d.init();var h=
{};d.bind("Started",function(c,b){u.triggerEvent("confluence.editor.files.drag-and-drop",b)});d.bind("FilesAdded",function(g,e){"template"===b.Meta.get("content-type")?(g.stop(),x()):b.UploadUtils.filterFiles(g,e,function(e,g){for(var a=0;a<g.length;a++){var f=g[a];f.status!==l.FAILED?c.render({workId:f.id,status:f.status,file:f}):e.removeFile(f)}m.filesAdded(e,g,h).then(function(a){a=r(e,a,g);c.show();a?c.showCloseButton():(c.cancelListeners.push(function(g,a){(g=e.getFile(a.workId))&&e.removeFile(g);
c.renderInfo(a.workId,"File was manually removed from the queue.")}),d.start())})})});d.bind("BeforeUpload",function(c,b){m.beforeUpload(c,b,h)});d.bind("UploadProgress",function(b,a){c.renderUpdateToBytesUploaded(a.id,a.loaded,a.size);c.hideCloseButton()});f.browser.mozilla&&function(){l.addEvent(p,"dragenter",function(b){k=b.rangeParent&&void 0!=b.rangeOffset?{startElement:b.rangeParent,startOffset:b.rangeOffset}:!1})}();d.bind("FileUploaded",function(a,e,h){m.fileUploaded(a,e,h,!0).done(function(a){k&&
f(k.startElement.parentNode).closest('[contenteditable\x3d"true"]',p).length&&tinymce.activeEditor.selection.setCursorLocation(k.startElement,k.startOffset);"\x3cimg"===a.htmlForEditor.substr(0,4)?tinymce.confluence.ImageUtils.insertImagePlaceholder(a.htmlForEditor):b.Rte.getEditor().execCommand("mceInsertContent",!1,a.htmlForEditor,{skip_focus:!0});c.renderComplete(e.id)}).fail(function(b){r(a,b,[e])}).always(function(){t(d)})});d.bind("Error",function(a,e){e.response?(a=m.serverError(e.response)||
e.message,c.renderError(e.file.id,a),b.trigger("analyticsEvent",{name:"confluence.editor.upload.error.server-unknown"})):(a=e.message,e.code===l.FILE_SIZE_ERROR?(a=b.format("is too big to upload. Files must be less than {0}.",b.DragAndDropUtils.niceSize(b.Meta.get("global-settings-attachment-max-size"))),b.trigger("analyticsEvent",{name:"confluence.editor.upload.error.file-size"})):e.code===b.UploadUtils.ErrorCode.FILE_IS_A_FOLDER_ERROR&&(a="might be a folder or an unsupported file type.",b.trigger("analyticsEvent",
{name:"confluence.editor.upload.error.file-type"})),c.render({workId:e.file.id,status:e.file.status,file:e.file,errorMessage:a}),c.isVisible()||(c.show(),c.showCloseButton()));t(d)});return{instance:d,uploadProgressDialog:c}},q=!1;return function(){var c=b.Rte.getEditor().getBody().parentNode,a=y(c);v.bindFileDragOverlay({$dragZone:f(c).add("#toolbar ~ #editor-precursor"),$overlayZone:f("#rte"),isTransparent:!0});return a}});
require("confluence/module-exporter").safeRequire("confluence-drag-and-drop/editor",function(b){require("confluence/api/event").bind("rte-ready",function(){var f=b();AJS.Confluence.Uploader=f.instance;AJS.Confluence.EditorUploadProgressDialog=f.uploadProgressDialog})});
}catch(e){WRMCB(e)};