WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'com.atlassian.auiplugin:internal-@atlassian-aui-src-js-aui-inline-dialog2', location = 'node_modules/@atlassian/aui/src/js/aui/inline-dialog2.js' */
("undefined"===typeof window?global:window).__1568a26ea3fe084223145f2b1f4304f3=function(){function c(a){return a&&a.__esModule?a:{"default":a}}function l(a,b){var d=document.querySelector('[aria-controls="'+a.id+'"]');d&&b(d)}function n(a){a=a.target;(0,e.default)(a).set("mouse-inside",!0);a.message({type:"mouseenter"})}function o(a){a=a.target;(0,e.default)(a).set("mouse-inside",!1);a.message({type:"mouseleave"})}function m(a){(0,e.default)(a).set("mouse-inside",void 0);a.removeEventListener("mouseenter",
n);a.removeEventListener("mouseleave",o);"hover"===a.respondsTo&&((0,e.default)(a).set("mouse-inside",!1),a.addEventListener("mouseenter",n),a.addEventListener("mouseleave",o))}function j(a){var b=!a.hasAttribute("aria-hidden"),d=a.hasAttribute("open");if(b||a.open!==d)d?((0,e.default)(a).set("is-processing-show",!0),(0,f.default)(a).show(),(0,f.default)(a).isVisible()?l(a,function(b){a._auiAlignment||(a._auiAlignment=new p.default(a,b));a._auiAlignment.enable();b.setAttribute("aria-expanded","true")}):
a.open=!1,(0,e.default)(a).set("is-processing-show",!1)):((0,f.default)(a).hide(),(0,f.default)(a).isVisible()?a.open=!0:l(a,function(b){a._auiAlignment||(a._auiAlignment=new p.default(a,b));a._auiAlignment.disable();b.setAttribute("aria-expanded","false")}))}var k={};"use strict";Object.defineProperty(k,"__esModule",{value:!0});var q=c(__02fa0d2334b5d2f9701871403ba9d89a),p=c(__670509c3f39577904eaf81675f28b1a5),r=c(__8f23956215d754ca94df621efa6b0438),g=c(__82e760f4580e37eda172e78ba0378f6d),s=c(__da99b881b3bdaf63767de8d2780ca44c),
t=c(__fb27ffae84b96c14bf339e62cefcf116),f=c(__b16464bbf0aa314bacb753553ada098e),h=c(__da172e72afc5a7088e3034df761062a6),e=c(__ed9b9aac7079f8ce29349f1a2c1b9701),u={click:function(a){if(a.open){if(!(0,f.default)(a).isPersistent())a.open=!1}else a.open=!0},mouseenter:function(a){a.open||(a.open=!0);a._clearMouseleaveTimeout&&a._clearMouseleaveTimeout()},mouseleave:function(a){if(!(0,f.default)(a).isPersistent()&&a.open){a._clearMouseleaveTimeout&&a._clearMouseleaveTimeout();var b=setTimeout(function(){if(!(0,
e.default)(a).get("mouse-inside"))a.open=!1},1E3);a._clearMouseleaveTimeout=function(){clearTimeout(b);a._clearMouseleaveTimeout=null}}},focus:function(a){a.open||(a.open=!0)},blur:function(a){if(!(0,f.default)(a).isPersistent()&&a.open)a.open=!1}},i={attribute:"responds-to",values:["toggle","hover"],missingDefault:"toggle",invalidDefault:"toggle"},h=(0,h.default)("aui-inline-dialog",{prototype:{get open(){return(0,f.default)(this).isVisible()},set open(a){g.default.setBooleanAttribute(this,"open",
a);j(this)},get persistent(){return this.hasAttribute("persistent")},set persistent(a){g.default.setBooleanAttribute(this,"persistent",a)},get respondsTo(){return g.default.computeEnumValue(i,this.getAttribute(i.attribute))},set respondsTo(a){var b=this.respondsTo;g.default.setEnumAttribute(this,i,a);b!==this.respondsTo&&m(this)},message:function(a){var b={toggle:["click"],hover:["mouseenter","mouseleave","focus","blur"]}[this.respondsTo];if(b&&-1<b.indexOf(a.type))u[a.type](this,a);return this}},
created:function(a){(0,e.default)(a).set("is-processing-show",!1);l(a,function(b){b.setAttribute("aria-expanded",a.open);b.setAttribute("aria-haspopup","true")})},attributes:{"aria-hidden":function(a,b){if("true"===b.newValue){var d=document.querySelector('[aria-controls="'+a.id+'"]');d&&d.setAttribute("aria-expanded","false")}g.default.setBooleanAttribute(a,"open","false"===b.newValue)},open:function(a){document.body.contains(a)&&j(a)},"responds-to":function(a,b){var d=g.default.computeEnumValue(i,
b.oldValue),c=g.default.computeEnumValue(i,b.newValue);d!==c&&m(a)}},attached:function(a){(0,s.default)(a).attributeExists("id");a.hasAttribute("open")?(0,e.default)(a).get("is-processing-show")||j(a):j(a);m(a)},detached:function(a){a._auiAlignment&&a._auiAlignment.destroy()},template:function(a){var b=(0,q.default)('<div class="aui-inline-dialog-contents"></div>').append(a.childNodes);(0,q.default)(a).addClass("aui-layer").html(b)}});(0,r.default)("aui/inline-dialog2",h);(0,t.default)("InlineDialog2",
h);k.default=h;return k=k["default"]}.call(this);
}catch(e){WRMCB(e)};