WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'com.atlassian.plugins.atlassian-connect-plugin:ap-navigator-v5', location = 'v5/js/iframe/host/_uritemplate.js' */
(function(x){function n(a){var b;if(null===a||void 0===a)return!1;if(e.isArray(a))return 0<a.length;if("string"===typeof a||"number"===typeof a||"boolean"===typeof a)return!0;for(b in a)if(a.hasOwnProperty(b)&&n(a[b]))return!0;return!1}var m=function(){function a(b){this.options=b}a.prototype.toString=function(){return JSON&&JSON.stringify?JSON.stringify(this.options):this.options};return a}(),e=function(){function a(b){if("function"===typeof Object.freeze&&"object"===typeof b&&null!==b){Object.freeze(b);
var c,k;for(k in b)b.hasOwnProperty(k)&&(c=b[k],"object"===typeof c&&a(c))}return b}return{isArray:function(b){return"[object Array]"===Object.prototype.toString.apply(b)},isString:function(b){return"[object String]"===Object.prototype.toString.apply(b)},isNumber:function(b){return"[object Number]"===Object.prototype.toString.apply(b)},isBoolean:function(b){return"[object Boolean]"===Object.prototype.toString.apply(b)},join:function(b,c){var a="",d=!0,f;for(f=0;f<b.length;f+=1)d?d=!1:a+=c,a+=b[f];
return a},map:function(b,c){for(var a=[],d=0;d<b.length;d+=1)a.push(c(b[d]));return a},filter:function(b,c){for(var a=[],d=0;d<b.length;d+=1)c(b[d])&&a.push(b[d]);return a},deepFreeze:a}}(),t=function(){function a(b){return"0"<=b&&"9">=b}return{isAlpha:function(b){return"a"<=b&&"z">=b||"A"<=b&&"Z">=b},isDigit:a,isHexDigit:function(b){return a(b)||"a"<=b&&"f">=b||"A"<=b&&"F">=b}}}(),u=function(){function a(b,a){return"%"===b.charAt(a)&&t.isHexDigit(b.charAt(a+1))&&t.isHexDigit(b.charAt(a+2))}var b=
{encode:function(b){return unescape(encodeURIComponent(b))},numBytes:function(b){return 127>=b?1:194<=b&&223>=b?2:224<=b&&239>=b?3:240<=b&&244>=b?4:0},isValidFollowingCharCode:function(b){return 128<=b&&191>=b}};return{encodeCharacter:function(a){var c="";a=b.encode(a);var d,f;for(f=0;f<a.length;f+=1)d=a.charCodeAt(f),c+="%"+(16>d?"0":"")+d.toString(16).toUpperCase();return c},isPctEncoded:function(c){if(!a(c,0))return!1;var k=parseInt(c.substr(1,2),16),k=b.numBytes(k);if(0===k)return!1;for(var d=
1;d<k;d+=1)if(!a(c,3*d)||!b.isValidFollowingCharCode(parseInt(c.substr(3*d+1,2),16)))return!1;return!0},pctCharAt:function(c,k){var d=c.charAt(k);if(!a(c,k))return d;var f=parseInt(c.substr(k+1,2),16),f=b.numBytes(f);if(0===f)return d;for(var e=1;e<f;e+=1)if(!a(c,k+3*e)||!b.isValidFollowingCharCode(parseInt(c.substr(k+3*e+1,2),16)))return d;return c.substr(k,3*f)}}}(),v=function(){return{isVarchar:function(a){return t.isAlpha(a)||t.isDigit(a)||"_"===a||u.isPctEncoded(a)},isUnreserved:function(a){return t.isAlpha(a)||
t.isDigit(a)||"-"===a||"."===a||"_"===a||"~"===a},isReserved:function(a){return":"===a||"/"===a||"?"===a||"#"===a||"["===a||"]"===a||"@"===a||"!"===a||"$"===a||"\x26"===a||"("===a||")"===a||"*"===a||"+"===a||","===a||";"===a||"\x3d"===a||"'"===a}}}(),w=function(){function a(b,a){var c="",d,f;if("number"===typeof b||"boolean"===typeof b)b=b.toString();for(d=0;d<b.length;d+=f.length)f=b.charAt(d),c+=v.isUnreserved(f)||a&&v.isReserved(f)?f:u.encodeCharacter(f);return c}return{encode:a,encodePassReserved:function(b){return a(b,
!0)},encodeLiteral:function(b){var a="",k,d;for(k=0;k<b.length;k+=d.length)d=u.pctCharAt(b,k),a=1<d.length?a+d:a+(v.isReserved(d)||v.isUnreserved(d)?d:u.encodeCharacter(d));return a},encodeLiteralCharacter:function(b,a){var c=u.pctCharAt(b,a);return 1<c.length?c:v.isReserved(c)||v.isUnreserved(c)?c:u.encodeCharacter(c)}}}(),A=function(){function a(a){b[a]={symbol:a,separator:"?"===a?"\x26":""===a||"+"===a||"#"===a?",":a,named:";"===a||"\x26"===a||"?"===a,ifEmpty:"\x26"===a||"?"===a?"\x3d":"",first:"+"===
a?"":a,encode:"+"===a||"#"===a?w.encodePassReserved:w.encode,toString:function(){return this.symbol}}}var b={};a("");a("+");a("#");a(".");a("/");a(";");a("?");a("\x26");return{valueOf:function(a){return b[a]?b[a]:0<="\x3d,!@|".indexOf(a)?null:b[""]}}}(),y=function(){function a(a){this.literal=w.encodeLiteral(a)}a.prototype.expand=function(){return this.literal};a.prototype.toString=a.prototype.expand;return a}(),C=function(){function a(a){function b(){var b=a.substring(q,g);if(0===b.length)throw new m({expressionText:a,
message:"a varname must be specified",position:g});e={varname:b,exploded:!1,maxLength:null};q=null}function k(){if(p===g)throw new m({expressionText:a,message:"after a ':' you have to specify the length",position:g});e.maxLength=parseInt(a.substring(p,g),10);p=null}var d,f=[],e=null,q=null,p=null,g,h="";d=function(b){var c=A.valueOf(b);if(null===c)throw new m({expressionText:a,message:"illegal use of reserved operator",position:g,operator:b});return c}(a.charAt(0));for(q=g=d.symbol.length;g<a.length;g+=
h.length){h=u.pctCharAt(a,g);if(null!==q){if("."===h){if(q===g)throw new m({expressionText:a,message:"a varname MUST NOT start with a dot",position:g});continue}if(v.isVarchar(h))continue;b()}if(null!==p){if(g===p&&"0"===h)throw new m({expressionText:a,message:"A :prefix must not start with digit 0",position:g});if(t.isDigit(h)){if(4<=g-p)throw new m({expressionText:a,message:"A :prefix must have max 4 digits",position:g});continue}k()}if(":"===h){if(null!==e.maxLength)throw new m({expressionText:a,
message:"only one :maxLength is allowed per varspec",position:g});if(e.exploded)throw new m({expressionText:a,message:"an exploeded varspec MUST NOT be varspeced",position:g});p=g+1}else if("*"===h){if(null===e)throw new m({expressionText:a,message:"exploded without varspec",position:g});if(e.exploded)throw new m({expressionText:a,message:"exploded twice",position:g});if(e.maxLength)throw new m({expressionText:a,message:"an explode (*) MUST NOT follow to a prefix",position:g});e.exploded=!0}else if(","===
h)f.push(e),e=null,q=g+1;else throw new m({expressionText:a,message:"illegal character",character:h,position:g});}null!==q&&b();null!==p&&k();f.push(e);return new B(a,d,f)}return function(b){var c,e,d=[],f=null,n=0;for(c=0;c<b.length;c+=1)if(e=b.charAt(c),null!==n){if("}"===e)throw new m({templateText:b,message:"unopened brace closed",position:c});"{"===e&&(n<c&&d.push(new y(b.substring(n,c))),n=null,f=c)}else if(null!==f){if("{"===e)throw new m({templateText:b,message:"brace already opened",position:c});
if("}"===e){if(f+1===c)throw new m({templateText:b,message:"empty braces",position:f});try{d.push(a(b.substring(f+1,c)))}catch(q){if(q.prototype===m.prototype)throw new m({templateText:b,message:q.options.message,position:f+q.options.position,details:q.options});throw q;}f=null;n=c+1}}else throw Error("reached unreachable code");if(null!==f)throw new m({templateText:b,message:"unclosed brace",position:f});n<b.length&&d.push(new y(b.substr(n)));return new z(b,d)}}(),B=function(){function a(a){if(!n(a))return!0;
if(e.isString(a))return""===a;if(e.isNumber(a)||e.isBoolean(a))return!1;if(e.isArray(a))return 0===a.length;for(var b in a)if(a.hasOwnProperty(b))return!1;return!0}function b(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push({name:c,value:a[c]});return b}function c(a,b,c){this.templateText=a;this.operator=b;this.varspecs=c}function k(a,b,c){var d="";c=c.toString();if(b.named){d+=w.encodeLiteral(a.varname);if(""===c)return d+=b.ifEmpty;d+="\x3d"}null!==a.maxLength&&(c=c.substr(0,a.maxLength));return d+=
b.encode(c)}function d(a){return n(a.value)}function f(c,g,f){var h=[],l="";if(g.named){l+=w.encodeLiteral(c.varname);if(a(f))return l+=g.ifEmpty;l+="\x3d"}e.isArray(f)?(h=e.filter(f,n),h=e.map(h,g.encode)):(h=b(f),h=e.filter(h,d),h=e.map(h,function(a){return g.encode(a.name)+","+g.encode(a.value)}));return l+=e.join(h,",")}function m(c,g,f){var h=[];e.isArray(f)?(h=e.filter(f,n),h=e.map(h,function(b){var d=w.encodeLiteral(c.varname);return d=a(b)?d+g.ifEmpty:d+("\x3d"+g.encode(b))})):(h=b(f),h=e.filter(h,
d),h=e.map(h,function(b){var c=w.encodeLiteral(b.name);return c=a(b.value)?c+g.ifEmpty:c+("\x3d"+g.encode(b.value))}));return e.join(h,g.separator)}function q(a,c){var d=[],f="";e.isArray(c)?(d=e.filter(c,n),d=e.map(d,a.encode)):(d=b(c),d=e.filter(d,function(a){return n(a.value)}),d=e.map(d,function(b){return a.encode(b.name)+"\x3d"+a.encode(b.value)}));return f+=e.join(d,a.separator)}c.prototype.toString=function(){return this.templateText};c.prototype.expand=function(b){var c=[],d,p,l,r=this.operator;
for(d=0;d<this.varspecs.length;d+=1)if(p=this.varspecs[d],l=b[p.varname],null!==l&&void 0!==l)if(e.isArray(l),"string"===typeof l||"number"===typeof l||"boolean"===typeof l)c.push(k(p,r,l));else{if(p.maxLength&&n(l))throw b=Error,l=JSON&&JSON.stringify?JSON.stringify(l):l,new b("Prefix modifiers are not applicable to variables that have composite values. You tried to expand "+this+" with "+l);p.exploded?n(l)&&(r.named?c.push(m(p,r,l)):c.push(q(r,l))):!r.named&&a(l)||c.push(f(p,r,l))}return 0===c.length?
"":r.first+e.join(c,r.separator)};return c}(),z=function(){function a(a,c){this.templateText=a;this.expressions=c;e.deepFreeze(this)}a.prototype.toString=function(){return this.templateText};a.prototype.expand=function(a){var b,e="";for(b=0;b<this.expressions.length;b+=1)e+=this.expressions[b].expand(a);return e};a.parse=C;a.UriTemplateError=m;return a}();x(z)})(function(x){"function"===typeof define?define("_uritemplate",[],function(){return x}):"undefined"!==typeof window?window.UriTemplate=x:global.UriTemplate=
x});
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.plugins.atlassian-connect-plugin:ap-navigator-v5', location = 'v5/js/navigator/context.js' */
define("ac/navigator/context",function(){var a;return{setContextFunction:function(b){a=b},getContextFunction:function(){return a}}});
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.plugins.atlassian-connect-plugin:ap-navigator-v5', location = 'v5/js/navigator/module.js' */
define("ac/navigator/module",["ac/navigator/utils","ac/navigator/routes","ac/navigator/context","ac/spa-context"],function(b,e,f,g){return{getLocation:function(a){var c=f.getContextFunction();"function"!==typeof c?console.error("no context function defined"):(context=c(),"object"!==typeof context||Array.isArray(context)||null===context?console.error("navigator context callback did not return an object"):a(context))},go:function(a,c,d){a=a.toLowerCase();c=c||{};c.addonKey||(c.addonKey=d._context.extension.addon_key);
if(b.isApiEnabled())if(d=e.getRoutes(),e.hasRoutes()&&a in d)if("function"===typeof d[a])d[a](c,b.goToUrl);else b.goToUrl(b.buildUrl(d[a],c));else console.error("The URL target "+a+" is not available. Valid targets are: "+Object.keys(d).toString());else console.error("connect navigation api not yet implemented for this product")},_shouldThrottle:function(a,c){var d=Number(window.localStorage.getItem("lastReloadTimestamp")),b=Number(window.localStorage.getItem("reloadAttempts")),e=Date.now();e-d>a&&
(b=0);if(b>=c)return console.error("Reloads must be "+a+"ms apart after "+b+" reload attempts."),!0;b+=1;window.localStorage.setItem("lastReloadTimestamp",e);window.localStorage.setItem("reloadAttempts",b);return!1},reload:function(){this._shouldThrottle(12E4,5)||(g.isInIframe()?b.getTopmostSameOriginWindow(window).location.reload():window.location.reload())}}});
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.plugins.atlassian-connect-plugin:ap-navigator-v5', location = 'v5/js/navigator/routes.js' */
define("ac/navigator/routes",function(){function g(a){return Object.keys(a).map(function(c){return["ac."+c,a[c]].map(encodeURIComponent).join("\x3d")}).join("\x26")}var e={addonmodule:function(a,c){var b=a&&a.addonKey,d=a&&a.moduleKey;if(!b)throw Error("Missing addonKey parameter in the context.");if(!d)throw Error("Missing moduleKey parameter in the context.");var f=[b,d].map(encodeURIComponent).join("/"),f=AJS.contextPath()+"/plugins/servlet/ac/"+f;void 0!=a.context&&(console.warn("DEPRECATED API - The context field has been deprecated in favor of customData."),
connectHost.trackDeprecatedMethodUsed("AP.navigate-context",{addon_key:b,moduleKey:d}));b=AJS.$.extend({},a.context||{},a.customData||{});b=g(b);c.apply(this,[""!=b?f+"?"+b:f])},site:function(a,c){function b(a){if(-1!==a.indexOf("plugins/servlet/ac-redirect"))throw Error("Cannot use legacy redirect filter in Navigator API");}if(a.relativeUrl){if("string"!==typeof a.relativeUrl||"/"!==a.relativeUrl[0])throw Error("Invalid relativeUrl passed in context");b(a.relativeUrl);var d=0===a.relativeUrl.indexOf(AJS.contextPath())?
"":AJS.contextPath();c.apply(this,[window.location.protocol+"//"+window.location.hostname+d+a.relativeUrl])}else if(a.absoluteUrl){d=window.location.protocol+"//"+window.location.hostname+"/";if("string"!==typeof a.absoluteUrl||0!==a.absoluteUrl.indexOf(d))throw Error("Invalid absoluteUrl passed in context");b(a.absoluteUrl);c.apply(this,[a.absoluteUrl])}else throw Error("No context supplied to Navigator API");}};return{hasRoutes:function(){return e&&0!==Object.getOwnPropertyNames(e).length},addRoutes:function(a){e=
AJS.$.extend(e,a)},getRoutes:function(){return e}}});
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.plugins.atlassian-connect-plugin:ap-navigator-v5', location = 'v5/js/navigator/utils.js' */
define("ac/navigator/utils",["_uritemplate","ac/spa-context"],function(e,c){var d=!1;return{enableApi:function(){d=!0},disableApi:function(){d=!1},isApiEnabled:function(){return d},buildUrl:function(a,b){"/"!==a[0]&&(a="/"+a);return AJS.contextPath()+e.parse(a).expand(b)},goToUrl:function(a){var b=function(){window.location.href=a};c.isInIframe()?c.getContainerApi().navigate(a,b):c.canSpaTransition()?c.getNavigationApi().navigate(a):b()},hasContext:function(a,b){return a[b]?!0:(AJS.error("Missing "+
b+" in navigator context"),!1)},appendQueryParam:function(a,b,c){return a+(-1<a.indexOf("?")?"\x26":"?")+b+"\x3d"+encodeURIComponent(c)},getTopmostSameOriginWindow:function(a){function b(a){try{if(null==a.location.href)return!1}catch(f){return!1}return!0}for(;a!==a.parent&&b(a.parent);)a=a.parent;return a}}});
}catch(e){WRMCB(e)};