WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'com.atlassian.confluence.plugins.confluence-link-browser:link-object', location = 'js/link-object.js' */
define("confluence-link-browser/link-object",["jquery","ajs","confluence-rest/confluence-rest"],function(d,h,p){function l(a){return d.nodeName(a,"img")?a:a.hasChildNodes()&&1===a.childNodes.length&&d.nodeName(a,"a")&&d.nodeName(a.firstChild,"img")?a.firstChild:null}function m(a){return a?d(a).attr("data-linked-resource-default-alias")||d(a).attr("src"):""}function n(a){var b={};"A"===a.nodeName&&d(a.attributes).each(function(){b[this.name]=this.value});return b}function k(a,b){for(;a&&a!=b;){if(3!=
a.nodeType)return!1;a=a.nextSibling}return 3===b.nodeType}var e={isLink:function(a){return a&&!!a.fillNode}},f=function(a){if(e.isLink(a))return a;var b={insert:function(){return require("confluence-link-browser/link-adapter").setLink(b)},fillNode:function(a){var b=this.attrs;b.href=b.href||"#";a.attr(b);this.classes&&this.classes.length&&a.addClass(this.classes.join(" "));a.html(this.body.html);return a},getData:function(){var a={},b;for(b in this)this.hasOwnProperty(b)&&!d.isFunction(this[b])&&
(a[b]=this[b]);return a},getLinkedImage:function(){return this.body&&this.body.jquery?1===this.body.length&&this.body.is("img")&&this.body:null},getResourceId:function(){return this.attrs["data-linked-resource-id"]||""},getResourceVersion:function(){return this.attrs["data-linked-resource-version"]||""},isToConfluenceEntity:function(){return this.attrs["data-linked-resource-id"]},isToAttachmentOnSamePage:function(a){return"attachment"==this.attrs["data-linked-resource-type"]&&this.attrs["data-linked-resource-container-id"]==
a},isCustomAtlassianContentLink:function(){return this.classes&&this.classes.length?-1!=d.inArray("confluence-link",this.classes):!1},hasAnchor:function(){return this.attrs["data-anchor"]},getResourceType:function(){return this.attrs["data-linked-resource-type"]},getDefaultAlias:function(){return this.attrs["data-linked-resource-default-alias"]},getHref:function(){return this.attrs.href},getAnchor:function(){return this.attrs["data-anchor"]},getHtml:function(){return this.body.html},getShortcut:function(){return this.attrs["data-linked-resource-shortcut"]},
isHrefValid:function(){return this.attrs.href&&"http://"!=this.attrs.href},isImage:function(){return this.body.isImage},isNewLink:function(){return d.isEmptyObject(this.attrs)},isShortcutLink:function(){return"shortcut"===this.getResourceType()},showsBreadcrumbs:function(){return!0}};if(a&&a.attrs){var f={},g=null;d.each(a.attrs,function(a,b){"class"==a?g=b:f[a]=b});a.attrs=f;if(g){var c=g.split(" ");a.classes=a.classes&&a.classes.length?a.classes.concat(c):c}}d.extend(b,a);return b};e.fromData=function(a){return f(a)};
e.fromNode=function(a,b){f({attrs:{},body:{html:b,text:b}});return f({attrs:n(a),body:{html:b,text:b}})};e.fromSelectedAnchor=function(a,b){var e=d(a),g=l(a),c=!g&&k(a.firstChild,a.lastChild);return f({attrs:n(a),body:{isEditable:c,isImage:!!g,html:e.html(),imgName:m(g),text:b}})};e.fromSelection=function(a,b,d,e){b=l(b);var c;if(c=!b)if(a.collapsed)c=!0;else if(c=a.startContainer,c==a.endContainer)c=3===c.nodeType?!0:k(c.childNodes[a.startOffset],c.childNodes[a.endOffset-1]);else{var g=require("tinymce").activeEditor.dom;
c=g.isBlock(a.startContainer)?a.startContainer.childNodes[a.startOffset]:a.startContainer;a=g.isBlock(a.endContainer)?a.endContainer.childNodes[a.endOffset-1]:a.endContainer;a=c&&a&&c.parentNode==a.parentNode?{start:c,end:a}:null;c=!!a&&k(a.start,a.end)}return f({attrs:{},body:{isEditable:c,isImage:!!b,html:d,imgName:m(b),text:e}})};e.fromREST=function(a){var b=f({attrs:{"data-base-url":h.Confluence.getBaseUrl(),"data-linked-resource-id":a.id,"data-linked-resource-type":a.type,"data-linked-resource-content-type":a.contentType,
href:p.REST.findLink(a.link),"data-linked-resource-default-alias":a.title},body:{html:h.escapeHtml(a.title),text:h.escapeHtml(a.title)},classes:["confluence-link"]});"user"===a.type&&(b.attrs["data-linked-resource-type"]="userinfo");return b};e.createLinkToNewPage=function(a,b){return f({attrs:{"data-space-key":b,"data-content-title":a,href:h.contextPath()+"/pages/createpage.action?spaceKey\x3d"+b+"\x26title\x3d"+a},body:{html:h.escapeEntities(a),text:a},classes:["createlink","confluence-link"]})};
e.makeExternalLink=function(a){return f({attrs:{href:a},body:{html:a,text:a}})};e.isExternalLink=function(a){return a&&(a.match(/^(\/\/|mailto:|file:|http:|https:)/)||0===a.indexOf("\\"))};return e});require("confluence/module-exporter").exportModuleAsGlobal("confluence-link-browser/link-object","Confluence.Link");
}catch(e){WRMCB(e)};