WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'com.atlassian.confluence.plugins.quickedit:quick-comment-initial', location = 'jscripts/handlers/comment.js' */
define("confluence-quick-edit/handlers/comment","ajs jquery aui/flag confluence-quick-edit/util confluence-editor/editor/page-editor-message confluence-quick-edit/handlers/page confluence-quick-edit/quick-edit confluence-quick-edit/captcha-manager confluence-quick-edit/comment-display-manager confluence/legacy-editor-global-AVOID-IF-POSSIBLE confluence/get-content-id".split(" "),function(a,d,o,l,e,p,g,q,r,k,m){function n(a,c){var d=a.match(RegExp("[?&]"+c+"=(\\d+)"));return d&&d.length>1?parseInt(d[1]):
0}d(function(){a.AppLinksInitialisationBinder=function(b){a.bind("init.rte",b)}});var f={timeout:8E3,showLoadingEditorErrorMessage:function(){a.trigger("rte-quick-comment-loading-failed");o({type:"error",title:"Error",persistent:false,body:"Error loading the comment editor. Please refresh the page to try again."})},preInitialise:function(){p.disable();a.Meta.set("content-type","comment");a.Meta.set("draft-type","");a.params.contentType="comment";a.params.draftType=
"";a.Meta.set("use-inline-tasks","false");d("#editor-precursor").children().eq(0).hide();d("#pagelayout-menu").parent().hide();d("#page-layout-2-group").hide();d("#rte-button-tasklist").remove();d("#pluggable-status-container").remove();d("#rte-insert-tasklist").parent().remove();d("#rte-button-preview").removeClass().addClass("aui-button aui-button-light toolbar-item toolbar-group-preview rte-button-preview-comment")},postInitialise:function(b){a.Rte.editorFocus(b.editor)},delegatingSaveCommentHandler:function(a){return a.asyncRenderSafe?
f.ajaxSaveCommentHandler(a):f.reloadPageSaveCommentHandler(a)},reloadPageSaveCommentHandler:function(a){var c=l.getBaseUrl();c.addQueryParam("focusedCommentId",a.id);c.addQueryParam("refresh",+new Date);window.location.href=c.toString()+"#comment-"+a.id},ajaxSaveCommentHandler:function(b){var c={isDefault:true,path:a.Meta.get("static-resource-url-prefix")+"/images/icons/profilepics/default.png"};a.Meta.get("current-user-avatar-uri-reference")!==a.contextPath()+"/images/icons/profilepics/default.png"&&
(c={isDefault:false,path:a.Meta.get("current-user-avatar-uri-reference")});var d=a.Meta.get("remote-user"),h={userName:d===""?null:d,displayName:a.Meta.get("current-user-fullname"),profilePicture:c};f.cancelComment().done(function(){r.addOrUpdateComment(h,b,true,false);a.trigger("page.commentAddedOrUpdated",{commentId:b.id})})},cancelHandler:function(){if(g){a.Rte.Content.editorResetContentChanged();g.deactivateEditor()}},createCommenterParam:function(b,c,d){return{userName:c||a.Meta.get("remote-user")||
null,displayName:d||a.Meta.get("user-display-name"),profilePicture:{isDefault:b.hasClass("defaultLogo"),path:b.attr("src")}}},createSaveHandler:function(b,c){var f=l.generateUUID();return function(h){h.preventDefault();if(a.Rte.Content.isEmpty()){a.Confluence.EditorNotification.notify("warning","Comment text is empty. Cannot create empty comments.");k.UI.toggleSavebarBusy(false)}else{var i=h=0,j=a.Confluence.EditorLoader.getEditorForm();if(j.is("form")){i=j.attr("action");h=n(i,"parentId");i=n(i,"commentId")}var e=new q(j),
j=function(a){c(a);e.refreshCaptcha()},g=d("#watchPage").is(":checked");i>0?k.CommentManager.updateComment(m(),i,a.Rte.Content.getHtml(),g,e.getCaptchaData(),b,j):k.CommentManager.saveComment(m(),h,a.Rte.Content.getHtml(),g,f,e.getCaptchaData(),b,j)}}},saveCommentErrorHandler:function(b){k.UI.toggleSavebarBusy(false);var c;if(b&&b.search(/captcha/i)!==-1){c="The typed word did not match the text in the picture.";e.closeMessages(["captcha-response-failed"]);e.handleMessage("captcha-response-failed",{type:"error",
message:c})}else{c="Failed to save the comment. Please try again later.";e.closeMessages(["server-offline"]);e.handleMessage("server-offline",{type:"error",message:c})}a.logError("Error saving comment",b)},cancelComment:function(){a.Rte.Content.editorResetContentChanged();return g.deactivateEditor()},proceedWithActivation:function(){var b=new d.Deferred,c=a.Rte&&a.Rte.getEditor();if(c)if(c.isDirty()&&!k.isEmpty())if(confirm("Your comment will be lost."))b=f.cancelComment();else return b.reject();
else b=f.cancelComment();else b.resolve();return b}};return f});require("confluence/module-exporter").exportModuleAsGlobal("confluence-quick-edit/handlers/comment","AJS.Confluence.QuickEdit.QuickComment");
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.plugins.quickedit:quick-comment-initial', location = 'jscripts/handlers/comment/top-level.js' */
define("confluence-quick-edit/handlers/comment/top-level","ajs jquery confluence-quick-edit/handlers/shortcut confluence-quick-edit/handlers/comment window confluence-quick-edit/quick-edit".split(" "),function(c,a,e,b,f,g){function h(a){b.preInitialise(a)}function i(c){a("#comments-section").one("click",".quick-comment-prompt",d.activateEventHandler);a("#rte-savebar").scrollWindowToElement();b.postInitialise(c)}function j(){if(!c.Confluence.EditorLoader.resourcesLoaded()){c.trigger("analytics",{name:"rte.quick-edit.top-comment.spinner"});
a(".quick-comment-prompt").hide();a(".quick-comment-loading-container").fadeIn().spin("medium")}}function k(b){b.preventDefault();f.location=a("#add-comment-rte").attr("href")}var l=c.DarkFeatures.isEnabled("editor.slow.comment.disable"),d={commentShortcut:e.createShortcut("m",".quick-comment-prompt"),activateEventHandler:function(e){e.preventDefault();b.proceedWithActivation().done(function(){var d=b.createSaveHandler(b.delegatingSaveCommentHandler,b.saveCommentErrorHandler);return g.activateEditor({preActivate:j,
$container:a("form[name=inlinecommentform]").closest(".quick-comment-container"),$form:a("form[name=inlinecommentform]"),preInitialise:h,saveHandler:d,cancelHandler:b.cancelHandler,postInitialise:i,plugins:c.Confluence.Editor._Profiles.createProfileForCommentEditor().plugins,additionalResources:["wrc!comment-editor"],timeoutResources:b.timeout}).fail(function(){l?b.showLoadingEditorErrorMessage():f.location=a("#add-comment-rte").attr("href")})}).fail(function(){a("#comments-section").one("click",
".quick-comment-prompt",d.activateEventHandler)})},enable:function(){a("#comments-section").one("click",".quick-comment-prompt",d.activateEventHandler);a("#add-comment-rte").removeClass("full-load");this.commentShortcut.bind()},disable:function(){a("#comments-section").off("click",".quick-comment-prompt");this.commentShortcut.unbind()}};g.register(d);return{bindCommentAreaFallbackHandler:function(){a("#comments-section").delegate(".quick-comment-prompt","click",k)},cancelComment:function(){c.log("'AJS.Confluence.QuickEdit.QuickComment.TopLevel.cancelComment' is deprecated in 5.7, consider using 'AJS.Confluence.QuickEdit.QuickComment.cancelComment' instead.");
return b.cancelComment()}}});require("confluence/module-exporter").exportModuleAsGlobal("confluence-quick-edit/handlers/comment/top-level","AJS.Confluence.QuickEdit.QuickComment.TopLevel");
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.plugins.quickedit:quick-comment-initial', location = 'jscripts/handlers/comment/reply.js' */
define("confluence-quick-edit/handlers/comment/reply","ajs confluence/templates jquery confluence-quick-edit/handlers/comment confluence-quick-edit/quick-edit confluence/get-content-id".split(" "),function(d,j,a,b,h,k){function l(a){b.preInitialise(a);a.$container.scrollWindowToElement()}function m(a){b.postInitialise(a)}function i(a){var b=a.attr("id").match(/comment-(\d+)/),f=0;if(b)f=parseInt(b[1]);else{d.trigger("analytics",{name:"rte.quick-edit.get-reply-parent.failed"});d.logError("replyHandler: activateEventHandler - could not extract a parent comment Id from the comment id "+
a.attr("id"))}return f}function n(){a(".comment.reply").closest(".comment-threads").remove()}var o=d.DarkFeatures.isEnabled("editor.slow.comment.disable"),e={activateEventHandler:function(e){e.preventDefault();e.stopPropagation();var g=this;if(a(g).attr("reply-disabled"))return false;b.proceedWithActivation().done(function(){var f=a(g).closest("div.comment"),c=a(".quick-comment-container img.userLogo"),c=b.createCommenterParam(c),c={contentId:k(),parentCommentId:i(f),commenter:c,context:{contextPath:d.Meta.get("context-path"),
staticResourceUrlPrefix:d.Meta.get("static-resource-url-prefix")}},c=a(j.Comments.displayReplyEditorLoadingContainer(c)),e=a(".quick-comment-loading-container",c);e.hide();f.after(c);if(d.Confluence.EditorLoader.resourcesLoaded())d.trigger("analytics",{name:"rte.quick-edit.reply-comment.no-spinner"});else{d.trigger("analytics",{name:"rte.quick-edit.reply-comment.spinner"});f.after(c);e.fadeIn();e.spin("medium");e[0].scrollIntoView()}c=a(g).closest(".comment-thread").find(".quick-comment-container");
d.Meta.set("form-name",a("form",c).attr("name"));h.activateEditor({$container:c,$form:a("form.quick-comment-form[name=threadedcommentform]"),preInitialise:l,postInitialise:m,saveHandler:b.createSaveHandler(b.delegatingSaveCommentHandler,b.saveCommentErrorHandler),cancelHandler:b.cancelHandler,plugins:d.Confluence.Editor._Profiles.createProfileForCommentEditor().plugins,postDeactivate:n,additionalResources:["wrc!comment-editor"],timeoutResources:b.timeout}).fail(function(){o?b.showLoadingEditorErrorMessage():
window.location=a("#reply-comment-"+i(f)).attr("href")});a(g).attr("reply-disabled",true)})},enable:function(){a("#comments-section").delegate(".action-reply-comment","click",e.activateEventHandler)},disable:function(){a("#comments-section").undelegate(".action-reply-comment","click")}};h.register(e);return{cancelComment:function(){d.log("'AJS.Confluence.QuickEdit.QuickComment.Reply.cancelComment' is deprecated in 5.7, consider using 'AJS.Confluence.QuickEdit.QuickComment.cancelComment' instead.");
return b.cancelComment()}}});require("confluence/module-exporter").exportModuleAsGlobal("confluence-quick-edit/handlers/comment/reply","AJS.Confluence.QuickEdit.QuickComment.Reply");
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.plugins.quickedit:quick-comment-initial', location = 'jscripts/handlers/comment/edit.js' */
define("confluence-quick-edit/handlers/comment/edit","ajs confluence-quick-edit/handlers/comment jquery confluence/templates confluence-quick-edit/quick-edit confluence/get-content-id".split(" "),function(e,b,d,j,i,k){function l(a){b.preInitialise(a);a.$container.scrollWindowToElement()}function m(a){b.postInitialise(a)}function h(a){return(a=a.attr("id").match(/comment-(\d+)/))?parseInt(a[1]):0}function n(a){var b=new d.Deferred;d.ajax({url:e.contextPath()+"/rest/api/content/"+a+"?expand=body.editor",
cache:false}).done(function(a){!a||!a.body||!a.body.editor?b.reject("invalid response from loading comment rest endpoint"):b.resolve({editorContent:a.body.editor.value})}).fail(function(){b.reject("error fetching content")});return b}function o(){var a=d(".comment.edit");a.prev(".comment").show();a.remove()}var p=e.DarkFeatures.isEnabled("editor.slow.comment.disable"),g={activateEventHandler:function(a){var g=this;a.preventDefault();a.stopPropagation();b.proceedWithActivation().done(function(){var a=
d(g).closest("div.comment"),c;c=a.find(".author .confluence-userlink");var f=a.find(".comment-user-logo img.userLogo");c=b.createCommenterParam(f,c.attr("data-username"),c.text());c={contentId:k(),commentId:h(a),commenter:c,context:{contextPath:e.Meta.get("context-path"),staticResourceUrlPrefix:e.Meta.get("static-resource-url-prefix")},mode:"edit"};c=d(j.Comments.displayEditEditorContainer(c));f=d(".quick-comment-loading-container",c);a.hide();a.after(c);f.fadeIn().spin("medium");f[0].scrollIntoView();
c=a.next(".quick-comment-container");e.Meta.set("form-name",d("form",c).attr("name"));i.activateEditor({$container:c,$form:d("form.quick-comment-form[name=editcommentform]"),fetchContent:n(h(a)),preInitialise:l,postInitialise:m,saveHandler:b.createSaveHandler(b.delegatingSaveCommentHandler,b.saveCommentErrorHandler),cancelHandler:b.cancelHandler,plugins:e.Confluence.Editor._Profiles.createProfileForCommentEditor().plugins,postDeactivate:o,additionalResources:["wrc!comment-editor"],timeoutResources:b.timeout}).fail(function(){p?
b.showLoadingEditorErrorMessage():window.location=d("#edit-comment-"+h(a)).attr("href")})})},enable:function(){d("#comments-section").delegate(".comment-action-edit","click",g.activateEventHandler)},disable:function(){d("#comments-section").undelegate(".comment-action-edit","click")}};i.register(g);return{cancelComment:function(){e.log("'AJS.Confluence.QuickEdit.QuickComment.Edit.cancelComment' is deprecated in 5.7, consider using 'AJS.Confluence.QuickEdit.QuickComment.cancelComment' instead.");return b.cancelComment()}}});
require("confluence/module-exporter").exportModuleAsGlobal("confluence-quick-edit/handlers/comment/edit","AJS.Confluence.QuickEdit.QuickComment.Edit");
}catch(e){WRMCB(e)};
;
try {
/* module-key = 'com.atlassian.confluence.plugins.quickedit:quick-comment-initial', location = 'jscripts/editor-comment-manager.js' */
define("confluence-quick-edit/editor-comment-manager",["ajs","jquery","confluence-quick-edit/comment-display-manager","confluence/legacy-editor-global-AVOID-IF-POSSIBLE"],function(d,l,m,n){return function(){function k(a,e,i,h,b,f,g){d.trigger("analytics",{name:"confluence.page.comment.create",data:{pageID:d.Meta.get("page-id")}});a={type:"POST",url:a,contentType:"application/x-www-form-urlencoded; charset=UTF-8",data:{html:e,watch:i,uuid:h},dataType:"json",cache:!1,headers:{"X-Atlassian-Token":"no-check"},
success:function(a){f(a)},error:function(a,c,b){c=c+": "+b;a.responseText&&(c=c+" - "+a.responseText);g(c)},timeout:12E4};b&&b.id&&(a.headers["X-Atlassian-Captcha-Id"]=b.id,a.headers["X-Atlassian-Captcha-Response"]=b.response);l.ajax(a)}return{addComment:function(a,e,d,h,b,f,g,j,c){n.CommentManager.saveComment(a,e,d,function(a){m.addComment(g,a,f);j(a)},c)},saveComment:function(a,e,i,h,b,f,g,j){var c=null,c=e?d.contextPath()+"/rest/tinymce/1/content/"+a+"/comments/"+e+"/comment?actions=true":d.contextPath()+
"/rest/tinymce/1/content/"+a+"/comment?actions=true";k(c,i,h,b,f,g,j)},updateComment:function(a,e,i,h,b,f,g){a=d.contextPath()+"/rest/tinymce/1/content/"+a+"/comments/"+e+"?actions=true";k(a,i,h,null,b,f,g)}}}});require("confluence/module-exporter").safeRequire("confluence-quick-edit/editor-comment-manager",function(d){require("ajs").bind("init.rte",function(){Confluence.Editor.CommentManager=d()})});
}catch(e){WRMCB(e)};