WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'com.atlassian.confluence.plugins.confluence-labels:labels-resources', location = 'com/atlassian/confluence/plugins/labels/labels.js' */
define("confluence-labels/labels/labels","ajs confluence/templates window document jquery confluence/legacy-editor-global-AVOID-IF-POSSIBLE".split(" "),function(c,y,z,A,t,E){var m=function(b){function u(a,d){if(!a||!d){var e=b("#dialog-label-list");a=e.attr("entityid");d=e.attr("entitytype")}return a&&d?b(".labels-section-content").filter(function(){return this.getAttribute("entityid")==a&&this.getAttribute("entitytype")==d}).find(g.labelView):b(g.labelView)}c.bind("init.rte-control",function(){var a=
0;c.Meta.get("num-labels")?a=c.Meta.get("num-labels"):b("#createPageLabelsString").val()&&(a=b.trim(b("#createPageLabelsString").val()).split(/\s+/).length);0!=a&&(c.Meta.set("num-labels",a),b("#rte-button-labels").trigger("updateLabel"))});var B=function(a){a=b.trim(a);if(!a)return[];var d=[],e=(new Date).getTime();b(a.split(/\s+/)).each(function(a,b){a=b.split(":");var f;b=a[0];2===a.length&&(f=a[0],b=a[1]);d.push({name:b,prefix:f,id:e});e++});return d},t=function(a){var d=[];b.each(a,function(a,
b){b.prefix&&"global"!==b.prefix?d.push(b.prefix+":"+b.name):d.push(b.name)});return d.join(" ")},g={labelView:".label-list",labelItem:".aui-label",noLabelsMessage:".no-labels-message",idAttribute:"data-label-id",labelsFormFieldId:c.Meta.get("labels-form-field-id")||"createPageLabelsString"},C=c.contextPath(),n={base:C+"/rest/ui/1.0/",getRestEndPoint:function(a){return this.base+("attachment"==a?"attachment/":"template"==a?"template/":"space"==a?"space/":"content/")},index:C+"/labels/autocompletelabel.action?maxResults\x3d3",
validate:function(){return this.getRestEndPoint()+"labels/validate"},add:function(a,b){return this.getRestEndPoint(a)+b+"/labels"},remove:function(a,b,e){return this.getRestEndPoint(a)+b+"/label/"+e},list:function(a,b){return this.getRestEndPoint(a)+b+"/labels"}},v=function(a){var d=b("#"+g.labelsFormFieldId);d.length&&d.val(a)},w=function(){var a=b("#"+g.labelsFormFieldId);return a.length?a.val():""},x=function(){return b(".space-administration").length},l=function(a){return"0"===a||!!A.getElementById("createpagetemplate")},
D=function(a){r();a&&a.promise&&(a.always([F,G]),a.done(function(a,e){c.Meta.set("num-labels",u().first().find(g.labelItem).size());b("#rte-button-labels").trigger("updateLabel");a=e.not(".editable");0===e.find(".aui-label").length?a.find(".labels-edit-container").before(y.Labels.nolabels()):a.find(".no-labels-message").remove()}));return a},G=function(){b("#labels-string, #add-labels-editor-button").removeAttr("disabled aria-disabled")},F=function(){b("#labels-string").val("")},r=function(a){a=a||
null;b("#label-operation-error-message").empty().toggle(!!a);c.messages.warning("#label-operation-error-message",{body:a})},H=function(a,b,e,f){a=u(a,b).not(".editable");a.length&&(a.find("li.aui-label").remove(),a.find("li.labels-edit-container").before(y.Labels.dialogLabels({labels:e,spaceKey:f})));return a},J=function(a,d,e){if(!a)return!1;b("#labels-string, #add-labels-editor-button").attr({disabled:"disabled","aria-disabled":!0});if(l(d)){a=(w()+" "+a).split(/\s+/);var f=[];b.each(a,function(a,
d){-1===b.inArray(d,f)&&f.push(d)});a=f.join(" ")}a={url:l(d)?n.validate():n.add(e,d),type:"POST",dataType:"json",contentType:"application/json",data:JSON.stringify(B(a))};var h=b.Deferred();a=b.ajax(a);a.done(function(a){var f=b("#dialog-label-list").find(".label-list");a=a.labels;var p=t(a);if(l()){var k=(new Date).getTime();b.each(a,function(a,b){b.id=k++})}v(p);m.updateDialogLabelList(a);p=H(d,e,a,c.Meta.get("space-key"));h.resolve(a,p.add(f))});a.fail(function(a,b){var d;if("timeout"===b)d="Connecting to the server timed out, you\'ll need to try again";
else try{d=JSON.parse(a.responseText).message}catch(I){d=b,c.log("Unexpected error when adding labels: "+I.message)}c.log("Failed to add labels: "+d);c.log("Failed to add labels xhr: "+a.responseText);r(d);h.reject(b)});return h.promise()},K=function(a,d,e){if(!a)return!1;a=a.jquery?a:b(a);x()&&(d=c.Meta.get("space-key"),e="space");var f=a.attr(g.idAttribute),h,k=b.Deferred();l(d)?(h=b.Deferred(),h.resolve()):(h={url:n.remove(e,d,f),type:"DELETE",dataType:"json",contentType:"application/json",data:{}},
h=b.ajax(h));h.done(function(){var c=x()?b("#space-categories-list"):u(d,e),h=c.find(g.labelItem).filter("["+g.idAttribute+"\x3d'"+f+"']");h.fadeOut("normal",function(){h.remove();k.resolve(a,c)});var m=b.trim(a.find("a").text()),q=w().split(/\s+/),q=b.grep(q,function(a){return a&&a!==m});v(q.join(" "))});h.fail(function(a,b){c.log(b);r("timeout"==b?"Connecting to the server timed out, you\'ll need to try again":b);k.reject(b)});return k.promise()},L=function(){var a=c.Meta.get("content-type"),d=E.Drafts.isNewContent()?c.Meta.get("draft-id"):
c.Meta.get("page-id");l(d)||b.ajax({url:n.list(a,d),cache:!1,success:function(a){c.Meta.set("num-labels",a.labels.length);b("#rte-button-labels").trigger("updateLabel");m.updateDialogLabelList(a.labels)},error:function(a,b){c.logError(b)}})};b(A).on("click",".label-list.editable .aui-icon-close",function(a){a.preventDefault();a=b("#dialog-label-list");m.removeLabel(b(this).closest("li"),a.attr("entityid"),a.attr("entitytype"))});c.toInit(function(){x()&&(m.bindAutocomplete(),b(".label-list").addClass("editable"))});
c.bind("editor-heartbeat",function(a,d){"undefined"!==typeof d.labelsHash&&(a=b("#rte-button-labels"),a.data("labelsHash")!==d.labelsHash&&(L(),a.data("labelsHash",d.labelsHash)))});return{addLabel:function(a,b,e){return D(J(a,b,e))},removeLabel:function(a,b,e){return D(K(a,b,e))},bindAutocomplete:function(){var a=b("#labels-string"),d=a.parents("#add-labels-form").length;a.length&&(b(z).bind("quicksearch.ajax-success",function(a,b){if("/labels/autocompletelabel.action?maxResults\x3d3"==b.url)return m.queryTokens=
b.json&&b.json.queryTokens||[],!1}),b(z).bind("quicksearch.ajax-error",function(a,b){if("/labels/autocompletelabel.action?maxResults\x3d3"==b.url)return m.queryTokens=[],!1}),a.quicksearch("/labels/autocompletelabel.action?maxResults\x3d3",function(){if(!b("#labels-autocomplete-list .label-suggestion").length||""===a.val())this.hide();else if(!d)for(var e=b("#labels-autocomplete-list a.label-suggestion"),f=0,c=e.length;f<c;f++)e.get(f).href="#"},{makeParams:function(a){return{query:a,contentId:c.params.pageId||
""}},dropdownPlacement:function(a){b("#labels-autocomplete-list").append(a)},ajsDropDownOptions:{selectionHandler:function(e,f){if(f.find("a.label-suggestion").length){f=b("span",f);f=b.data(f[0],"properties");var c=a.val();if(d)c=c.split(/\s+/),c[c.length-1]=f.name,a.val(c.join(" "));else{for(var k=m.queryTokens,g=-1,p,l="",q=0,n=k.length;q<n;q++)l=k[q],p=c.lastIndexOf(l),p>g&&(g=p);-1!=g?(k=c.substr(0,g),(c=c.substr(g+l.length).match(/^\s+/))&&(k+=c[0]),a.val(k+f.name)):a.val(f.name)}}this.hide();
e.preventDefault();a.focus()}}}))},labelsAreNotPersisted:l,routes:n,setLabelError:r,parseLabelStringToArray:B,getLabelLink:function(a,b){var d="/label/";null!==a&&void 0!=a&&""!==a&&(d+=a+"/");a=encodeURI;var c=b.prefix;b=b.name;return a(d+("global"===c||"team"===c||void 0===c||""===c||null===c?b:c+":"+b))},setLabelsInputField:v,getLabelsInputField:w}}(t);return m});require("confluence/module-exporter").exportModuleAsGlobal("confluence-labels/labels/labels","AJS.Labels");
}catch(e){WRMCB(e)};