WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'confluence.web.resources:property-panel-js', location = 'includes/js/property-panel.js' */
define("confluence/property-panel",["jquery","ajs","confluence/position","window","document"],function(e,k,u,r,p){var v=function(b,d){var a=e('\x3cdiv class\x3d"property-panel-arrow"\x3e\x3c/div\x3e');d&&a.addClass("property-panel-bottom-arrow").css({top:b.outerHeight()});b.prepend(a);return a},w=function(b,d,a,e){a=a.outerHeight()+~~e;b=u.spaceAboveBelow(b[0],d);return b.below>=a?!1:b.above>=a},t=function(b,d){d=d||{};r.setTimeout(function(){var a=k.Rte.Content.offset(b.anchor),h=b.panel.width(),
f=h+a.left-e(r).width()+10,c=e(b.anchor).outerHeight(),f=a.left-(0<f?f:0)-0,c=b.shouldFlip?a.top-7-b.panel.outerHeight()-4:a.top+7+c;if(b.options.anchorIframe)var m=e(b.options.anchorIframe),m=m.offset().top+m.height()-b.panel.outerHeight()-10,c=Math.min(c,m);b.panel.find(".property-panel-arrow").css({left:Math.min(Math.abs(a.left-f)+16,h-12)});f=Math.max(0,f);a={top:c,left:f,"z-index":2975};h=b.panel.add();d.animate?h.animate(a,d.animateDuration):h.css(a)},d.delay||0)},q={shouldCreate:!0,current:null,
getAnchor:function(){return e(this.current.anchor)},createFromButtonModel:function(b,d,a,h){for(var f=k("div").attr({"class":"panel-buttons"}),c=0,m=a.length;c<m;c++)if(a[c]){var g=a[c],l=g.html||'\x3cspan class\x3d"icon"\x3e\x3c/span\x3e',n=[];g.text&&(l+='\x3cspan class\x3d"panel-button-text"\x3e'+g.text+"\x3c/span\x3e");g.className&&n.push(g.className);g.disabled&&n.push("disabled");g.selected&&n.push("selected");!a[c+1]&&n.push("last");!a[c-1]&&n.push("first");g.html?l=e(g.html):(l=k("a").attr({href:a[c].href||
"#"}).addClass("aui-button").html(l),g.disabled?(l.attr("title",g.disabledText),l.disable(),l.click(function(a){return k.stopEvent(a)})):a[c].click&&function(a,b,c){b.click(function(d){a.click(b,c);return k.stopEvent(d)})}(a[c],l,d));g.tooltip&&l.attr("data-tooltip",g.tooltip);l.addClass(n.join(" "));f.append(l)}return this.create(b,d,f,h)},create:function(b,d,a,h){h=h||{};k.Rte.BookmarkManager.storeBookmark();var f=e("#property-panel"),c,m=void 0==h.enableFlip||h.enableFlip;f.length&&this.destroy();
f=k("div").addClass("aui-property-panel-parent").addClass(b+"-panel aui-box-shadow").attr("id","property-panel").appendTo("body");c=k("div").addClass("aui-property-panel").append(a);f.append(c).css({top:0,left:-1E4});c=m&&w(e(h.anchorIframe||e(d).parent()),e(d),f,10);var g=this;a.find(".last:last").css({"margin-right":0});a=v(f,c);this.current={anchor:d,panel:f,hasAnchorChanged:function(a){return a&&g.hasAnchorChanged(a)},snapToElement:function(a){t(this,a)},shouldFlip:c,tip:a,options:h,updating:!0,
type:b};t(this.current);c=this.current;e(p).bind("keydown.property-panel.escape",function(a){27===a.keyCode&&q.destroy()});e(p).bind("click.property-panel",function(a){e(a.target).closest("#property-panel").length||q.destroy()});k.trigger("created.property-panel",this.current);this.current.updating=!1;return this.current},destroy:function(){this.current?this.current.updating?k.log("PropertyPanel.destroy: called while updating, returning"):(k.trigger("destroyed.property-panel",this.current),e(p).unbind(".property-panel").unbind(".contextToolbar"),
this.current.panel.remove(),this.current=null):k.log("PropertyPanel.destroy: called with no current PropertyPanel, returning")},hasAnchorChanged:function(b){var d=this.current;return d&&e(d.anchor)[0]==e(b)[0]?d.options.originalHeight&&d.options.originalHeight!=e(b).height():!0}};return q});require("confluence/module-exporter").exportModuleAsGlobal("confluence/property-panel","AJS.Confluence.PropertyPanel");
}catch(e){WRMCB(e)};