chmod a+x /etc/init.d/procps
chmod a+x /etc/init.d/cups
chmod a+x /etc/init.d/apport
chmod a+x /etc/init.d/atd
chmod a+x /etc/init.d/bluetooth
chmod a+x /etc/init.d/avahi-daemon
chmod a+x /etc/init.d/hwclock.sh
chmod a+x /etc/init.d/hddtemp
chmod a+x /etc/init.d/rsync
chmod a+x /etc/init.d/lvm2
chmod a+x /etc/init.d/lvm2-lvmpolld
chmod a+x /etc/init.d/plymouth
chmod a+x /etc/init.d/kerneloops
chmod a+x /etc/init.d/apparmor
chmod a+x /etc/init.d/x11-common
chmod a+x /etc/init.d/irqbalance
chmod a+x /etc/init.d/iscsid
chmod a+x /etc/init.d/cryptdisks
chmod a+x /etc/init.d/gdm3
chmod a+x /etc/init.d/cron
chmod a+x /etc/init.d/cryptdisks-early
chmod a+x /etc/init.d/open-vm-tools
chmod a+x /etc/init.d/speech-dispatcher
chmod a+x /etc/init.d/postgresql
chmod a+x /etc/init.d/alsa-utils
chmod a+x /etc/init.d/openvpn
chmod a+x /etc/init.d/apache2
chmod a+x /etc/init.d/uuidd
chmod a+x /etc/init.d/keyboard-setup.sh
chmod a+x /etc/init.d/unattended-upgrades
chmod a+x /etc/init.d/whoopsie
chmod a+x /etc/init.d/network-manager
chmod a+x /etc/init.d/pulseaudio-enable-autospawn
chmod a+x /etc/init.d/dbus
chmod a+x /etc/init.d/anacron
chmod a+x /etc/init.d/spice-vdagent
chmod a+x /etc/init.d/ufw
chmod a+x /etc/init.d/open-iscsi
chmod a+x /etc/init.d/lm-sensors
chmod a+x /etc/init.d/multipath-tools
chmod a+x /etc/init.d/saned
chmod a+x /etc/init.d/kmod
chmod a+x /etc/init.d/pppd-dns
chmod a+x /etc/init.d/console-setup.sh
chmod a+x /etc/init.d/plymouth-log
chmod a+x /etc/init.d/rsyslog
chmod a+x /etc/init.d/cups-browsed
chmod a+x /etc/init.d/screen-cleanup
chmod a+x /etc/init.d/udev
chmod a+x /etc/init.d/acpid
chmod a+x /etc/init.d/apache-htcacheclean
chmod a+x /etc/init.d/ssh
chmod a+x /etc/cron.d/e2scrub_all
chmod a+x /etc/cron.d/popularity-contest
chmod a+x /etc/cron.d/anacron
chmod a+x /etc/cron.monthly/0anacron
chmod a+x /etc/cron.weekly/man-db
chmod a+x /etc/cron.weekly/0anacron
chmod a+x /etc/cron.weekly/update-notifier-common
chmod a+x /etc/cron.daily/dpkg
chmod a+x /etc/cron.daily/apport
chmod a+x /etc/cron.daily/man-db
chmod a+x /etc/cron.daily/0anacron
chmod a+x /etc/cron.daily/bsdmainutils
chmod a+x /etc/cron.daily/cracklib-runtime
chmod a+x /etc/cron.daily/apt-compat
chmod a+x /etc/cron.daily/apache2
chmod a+x /etc/cron.daily/popularity-contest
chmod a+x /etc/cron.daily/update-notifier-common
chmod a+x /etc/cron.daily/logrotate
